/* eslint-disable */
import {
    itu_t,
    itu_r,
    ccitt,
    iso,
    joint_iso_itu_t,
    joint_iso_ccitt,
    OPTIONAL,
    BOOLEAN,
    INTEGER,
    BIT_STRING,
    OCTET_STRING,
    NULL,
    OBJECT_IDENTIFIER,
    ObjectDescriptor,
    EXTERNAL,
    REAL,
    INSTANCE_OF,
    ENUMERATED,
    EMBEDDED_PDV,
    UTF8String,
    RELATIVE_OID,
    SEQUENCE,
    SEQUENCE_OF,
    SET,
    SET_OF,
    GraphicString,
    NumericString,
    VisibleString,
    PrintableString,
    ISO646String,
    TeletexString,
    GeneralString,
    T61String,
    UniversalString,
    VideotexString,
    BMPString,
    IA5String,
    CharacterString,
    UTCTime,
    GeneralizedTime,
    TIME,
    DATE,
    TIME_OF_DAY,
    DATE_TIME,
    DURATION,
    OID_IRI,
    RELATIVE_OID_IRI,
    TRUE,
    FALSE,
    TRUE_BIT,
    FALSE_BIT,
    PLUS_INFINITY,
    MINUS_INFINITY,
    NOT_A_NUMBER,
    TYPE_IDENTIFIER,
    ABSTRACT_SYNTAX,
    ASN1Element as _Element,
    ASN1TagClass as _TagClass,
    ASN1Construction as _Construction,
    ASN1UniversalType as _UniversalType,
    ObjectIdentifier as _OID,
    External as _External,
    EmbeddedPDV as _PDV,
    ASN1ConstructionError as _ConstructionError,
} from 'asn1-ts';
import * as $ from 'asn1-ts/dist/functional.mjs';
import {
    TroubleType_number,
    TroubleType_number_noDialToneGroup /* IMPORTED_LONG_NAMED_INTEGER */,
    noDialToneGroup /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_noDialTone /* IMPORTED_LONG_NAMED_INTEGER */,
    noDialTone /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_slowDialTone /* IMPORTED_LONG_NAMED_INTEGER */,
    slowDialTone /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_circuitDead /* IMPORTED_LONG_NAMED_INTEGER */,
    circuitDead /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotCallOutGroup /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotCallOutGroup /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotCallOut /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotCallOut /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotBreakDialTone /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotBreakDialTone /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_dialToneAfterDialing /* IMPORTED_LONG_NAMED_INTEGER */,
    dialToneAfterDialing /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_highAndDry /* IMPORTED_LONG_NAMED_INTEGER */,
    highAndDry /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotRaise /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotRaise /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_allAccessBusy /* IMPORTED_LONG_NAMED_INTEGER */,
    allAccessBusy /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotCallOut2 /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotCallOut2 /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotCallLongDistance /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotCallLongDistance /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotCallOverseas /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotCallOverseas /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_speedCall /* IMPORTED_LONG_NAMED_INTEGER */,
    speedCall /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotBeCalledGroup /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotBeCalledGroup /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotBeCalled /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotBeCalled /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotBeCalledBusy /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotBeCalledBusy /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_doNotGetCalled /* IMPORTED_LONG_NAMED_INTEGER */,
    doNotGetCalled /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotTripRing /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotTripRing /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_falseRings /* IMPORTED_LONG_NAMED_INTEGER */,
    falseRings /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_doNotAnswer /* IMPORTED_LONG_NAMED_INTEGER */,
    doNotAnswer /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_reachRecording /* IMPORTED_LONG_NAMED_INTEGER */,
    reachRecording /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotRaiseAStation /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotRaiseAStation /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotRaiseADrop /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotRaiseADrop /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotRaiseACircuitLocation /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotRaiseACircuitLocation /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_ringNoAnswer /* IMPORTED_LONG_NAMED_INTEGER */,
    ringNoAnswer /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_reorder /* IMPORTED_LONG_NAMED_INTEGER */,
    reorder /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_alwaysBusy /* IMPORTED_LONG_NAMED_INTEGER */,
    alwaysBusy /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_bellDoesNotRing /* IMPORTED_LONG_NAMED_INTEGER */,
    bellDoesNotRing /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_bellDoesNotRing2 /* IMPORTED_LONG_NAMED_INTEGER */,
    bellDoesNotRing2 /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_bellRingsCanNotAnswer /* IMPORTED_LONG_NAMED_INTEGER */,
    bellRingsCanNotAnswer /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_bellRingsAfterAnswer /* IMPORTED_LONG_NAMED_INTEGER */,
    bellRingsAfterAnswer /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_noRingNoAnswer /* IMPORTED_LONG_NAMED_INTEGER */,
    noRingNoAnswer /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_otherRingTrouble /* IMPORTED_LONG_NAMED_INTEGER */,
    otherRingTrouble /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_receivesCallsForWrongNumber /* IMPORTED_LONG_NAMED_INTEGER */,
    receivesCallsForWrongNumber /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_recordingOnLine /* IMPORTED_LONG_NAMED_INTEGER */,
    recordingOnLine /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotBeHeardGroup /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotBeHeardGroup /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotBeHeard /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotBeHeard /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotHear /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotHear /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_fading /* IMPORTED_LONG_NAMED_INTEGER */,
    fading /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_distant /* IMPORTED_LONG_NAMED_INTEGER */,
    distant /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_reachedWrongNumberGroup /* IMPORTED_LONG_NAMED_INTEGER */,
    reachedWrongNumberGroup /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_wrongNumber /* IMPORTED_LONG_NAMED_INTEGER */,
    wrongNumber /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_circuitOperationGroup /* IMPORTED_LONG_NAMED_INTEGER */,
    circuitOperationGroup /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_open /* IMPORTED_LONG_NAMED_INTEGER */,
    open /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_falseDisconnect /* IMPORTED_LONG_NAMED_INTEGER */,
    falseDisconnect /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_grounded /* IMPORTED_LONG_NAMED_INTEGER */,
    grounded /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotBeSignalled /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotBeSignalled /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotSignal /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotSignal /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_permanentSignal /* IMPORTED_LONG_NAMED_INTEGER */,
    permanentSignal /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_improperSupervision /* IMPORTED_LONG_NAMED_INTEGER */,
    improperSupervision /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_supervision /* IMPORTED_LONG_NAMED_INTEGER */,
    supervision /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotMeet /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotMeet /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotReleaseCircuit /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotReleaseCircuit /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_hungUp /* IMPORTED_LONG_NAMED_INTEGER */,
    hungUp /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_noWinkStart /* IMPORTED_LONG_NAMED_INTEGER */,
    noWinkStart /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_noSF /* IMPORTED_LONG_NAMED_INTEGER */,
    noSF /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_lowSF /* IMPORTED_LONG_NAMED_INTEGER */,
    lowSF /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_noContinuity /* IMPORTED_LONG_NAMED_INTEGER */,
    noContinuity /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_cutCable /* IMPORTED_LONG_NAMED_INTEGER */,
    cutCable /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_openToDEMARC /* IMPORTED_LONG_NAMED_INTEGER */,
    openToDEMARC /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_noRingGenerator /* IMPORTED_LONG_NAMED_INTEGER */,
    noRingGenerator /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_badERL /* IMPORTED_LONG_NAMED_INTEGER */,
    badERL /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_echo /* IMPORTED_LONG_NAMED_INTEGER */,
    echo /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_hollow /* IMPORTED_LONG_NAMED_INTEGER */,
    hollow /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_circuitDeadNoActivity /* IMPORTED_LONG_NAMED_INTEGER */,
    circuitDeadNoActivity /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_circuitDown /* IMPORTED_LONG_NAMED_INTEGER */,
    circuitDown /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_failingCircuit /* IMPORTED_LONG_NAMED_INTEGER */,
    failingCircuit /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_noSignal /* IMPORTED_LONG_NAMED_INTEGER */,
    noSignal /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_seizureOnCircuit /* IMPORTED_LONG_NAMED_INTEGER */,
    seizureOnCircuit /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_lossEPSCSorSwitchedServices /* IMPORTED_LONG_NAMED_INTEGER */,
    lossEPSCSorSwitchedServices /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_monitorCircuit /* IMPORTED_LONG_NAMED_INTEGER */,
    monitorCircuit /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_newServiceNotWorking /* IMPORTED_LONG_NAMED_INTEGER */,
    newServiceNotWorking /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_openEPSCSorSwitchedServices /* IMPORTED_LONG_NAMED_INTEGER */,
    openEPSCSorSwitchedServices /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_otherVoiceDescribeAdditInfo /* IMPORTED_LONG_NAMED_INTEGER */,
    otherVoiceDescribeAdditInfo /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_cutOffsGroup /* IMPORTED_LONG_NAMED_INTEGER */,
    cutOffsGroup /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_cutsOff /* IMPORTED_LONG_NAMED_INTEGER */,
    cutsOff /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_noiseProblemGroup /* IMPORTED_LONG_NAMED_INTEGER */,
    noiseProblemGroup /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_intermittentNoise /* IMPORTED_LONG_NAMED_INTEGER */,
    intermittentNoise /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_noisy /* IMPORTED_LONG_NAMED_INTEGER */,
    noisy /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_foreignTone /* IMPORTED_LONG_NAMED_INTEGER */,
    foreignTone /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_clipping /* IMPORTED_LONG_NAMED_INTEGER */,
    clipping /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_crossTalk /* IMPORTED_LONG_NAMED_INTEGER */,
    crossTalk /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_staticOnLine /* IMPORTED_LONG_NAMED_INTEGER */,
    staticOnLine /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_groundHum /* IMPORTED_LONG_NAMED_INTEGER */,
    groundHum /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_hearsOtherOnLine /* IMPORTED_LONG_NAMED_INTEGER */,
    hearsOtherOnLine /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_humOnLine /* IMPORTED_LONG_NAMED_INTEGER */,
    humOnLine /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_clicking /* IMPORTED_LONG_NAMED_INTEGER */,
    clicking /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_noiseEPSCSorSwitchedServices /* IMPORTED_LONG_NAMED_INTEGER */,
    noiseEPSCSorSwitchedServices /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_levelTroublesGroup /* IMPORTED_LONG_NAMED_INTEGER */,
    levelTroublesGroup /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_lowLevels /* IMPORTED_LONG_NAMED_INTEGER */,
    lowLevels /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_highLevels /* IMPORTED_LONG_NAMED_INTEGER */,
    highLevels /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_longLevels /* IMPORTED_LONG_NAMED_INTEGER */,
    longLevels /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_hotLevels /* IMPORTED_LONG_NAMED_INTEGER */,
    hotLevels /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_highEndRollOff /* IMPORTED_LONG_NAMED_INTEGER */,
    highEndRollOff /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_lowEndRollOff /* IMPORTED_LONG_NAMED_INTEGER */,
    lowEndRollOff /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_needsEqualized /* IMPORTED_LONG_NAMED_INTEGER */,
    needsEqualized /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_lineLoss /* IMPORTED_LONG_NAMED_INTEGER */,
    lineLoss /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_doesNotPassFreqResponse /* IMPORTED_LONG_NAMED_INTEGER */,
    doesNotPassFreqResponse /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_miscellaneousTroubleGroup /* IMPORTED_LONG_NAMED_INTEGER */,
    miscellaneousTroubleGroup /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_hiCapDown /* IMPORTED_LONG_NAMED_INTEGER */,
    hiCapDown /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_carrierDown /* IMPORTED_LONG_NAMED_INTEGER */,
    carrierDown /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_biPolarViolations /* IMPORTED_LONG_NAMED_INTEGER */,
    biPolarViolations /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_frameErrorsHiCap /* IMPORTED_LONG_NAMED_INTEGER */,
    frameErrorsHiCap /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_outOfFrame /* IMPORTED_LONG_NAMED_INTEGER */,
    outOfFrame /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_lossOfSync /* IMPORTED_LONG_NAMED_INTEGER */,
    lossOfSync /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_frameSlips /* IMPORTED_LONG_NAMED_INTEGER */,
    frameSlips /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_noLoopback /* IMPORTED_LONG_NAMED_INTEGER */,
    noLoopback /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotLoopbackDEMARC /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotLoopbackDEMARC /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_recordingOnCircuit /* IMPORTED_LONG_NAMED_INTEGER */,
    recordingOnCircuit /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_linesNeedTagging /* IMPORTED_LONG_NAMED_INTEGER */,
    linesNeedTagging /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_outwatsRingingin /* IMPORTED_LONG_NAMED_INTEGER */,
    outwatsRingingin /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_remoteAccess /* IMPORTED_LONG_NAMED_INTEGER */,
    remoteAccess /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_other /* IMPORTED_LONG_NAMED_INTEGER */,
    other /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_alarm /* IMPORTED_LONG_NAMED_INTEGER */,
    alarm /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_memoryServiceProblemGroup /* IMPORTED_LONG_NAMED_INTEGER */,
    memoryServiceProblemGroup /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_dataTroubleGroup /* IMPORTED_LONG_NAMED_INTEGER */,
    dataTroubleGroup /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotReceiveData /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotReceiveData /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotSendData /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotSendData /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotTransmitCanNotReceive /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotTransmitCanNotReceive /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_noReceive /* IMPORTED_LONG_NAMED_INTEGER */,
    noReceive /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_noResponse /* IMPORTED_LONG_NAMED_INTEGER */,
    noResponse /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_delay /* IMPORTED_LONG_NAMED_INTEGER */,
    delay /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_impulseNoise /* IMPORTED_LONG_NAMED_INTEGER */,
    impulseNoise /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_phaseJitter /* IMPORTED_LONG_NAMED_INTEGER */,
    phaseJitter /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_harmonicDistortion /* IMPORTED_LONG_NAMED_INTEGER */,
    harmonicDistortion /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_highDistortion /* IMPORTED_LONG_NAMED_INTEGER */,
    highDistortion /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_noDataLoopback /* IMPORTED_LONG_NAMED_INTEGER */,
    noDataLoopback /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_noCarrier /* IMPORTED_LONG_NAMED_INTEGER */,
    noCarrier /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_notPolling /* IMPORTED_LONG_NAMED_INTEGER */,
    notPolling /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_dataFramingErrors /* IMPORTED_LONG_NAMED_INTEGER */,
    dataFramingErrors /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_dropOuts /* IMPORTED_LONG_NAMED_INTEGER */,
    dropOuts /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_hits /* IMPORTED_LONG_NAMED_INTEGER */,
    hits /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_noAnswerBack /* IMPORTED_LONG_NAMED_INTEGER */,
    noAnswerBack /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_streamer /* IMPORTED_LONG_NAMED_INTEGER */,
    streamer /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_outOfSpecification /* IMPORTED_LONG_NAMED_INTEGER */,
    outOfSpecification /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotRunToCSU /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotRunToCSU /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotRunToOSU /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotRunToOSU /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_deadDataCircuit /* IMPORTED_LONG_NAMED_INTEGER */,
    deadDataCircuit /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_circuitInLoopback /* IMPORTED_LONG_NAMED_INTEGER */,
    circuitInLoopback /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_errors /* IMPORTED_LONG_NAMED_INTEGER */,
    errors /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_garbledData /* IMPORTED_LONG_NAMED_INTEGER */,
    garbledData /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_invalidData /* IMPORTED_LONG_NAMED_INTEGER */,
    invalidData /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_crossModulation /* IMPORTED_LONG_NAMED_INTEGER */,
    crossModulation /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_slowResponse /* IMPORTED_LONG_NAMED_INTEGER */,
    slowResponse /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_otherDataDescribeAdditInfo /* IMPORTED_LONG_NAMED_INTEGER */,
    otherDataDescribeAdditInfo /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_gettingAllOnes /* IMPORTED_LONG_NAMED_INTEGER */,
    gettingAllOnes /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_slip /* IMPORTED_LONG_NAMED_INTEGER */,
    slip /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_stationTroubleGroup /* IMPORTED_LONG_NAMED_INTEGER */,
    stationTroubleGroup /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_voiceEquipment /* IMPORTED_LONG_NAMED_INTEGER */,
    voiceEquipment /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_dataEquipment /* IMPORTED_LONG_NAMED_INTEGER */,
    dataEquipment /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_videoEquipment /* IMPORTED_LONG_NAMED_INTEGER */,
    videoEquipment /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_otherEquipment /* IMPORTED_LONG_NAMED_INTEGER */,
    otherEquipment /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_stationWiring /* IMPORTED_LONG_NAMED_INTEGER */,
    stationWiring /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_physicalTroubleGroup /* IMPORTED_LONG_NAMED_INTEGER */,
    physicalTroubleGroup /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_lightBurnedOut /* IMPORTED_LONG_NAMED_INTEGER */,
    lightBurnedOut /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_dataset /* IMPORTED_LONG_NAMED_INTEGER */,
    dataset /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_ttySet /* IMPORTED_LONG_NAMED_INTEGER */,
    ttySet /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_highSpeedPrinter /* IMPORTED_LONG_NAMED_INTEGER */,
    highSpeedPrinter /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_aNI /* IMPORTED_LONG_NAMED_INTEGER */,
    aNI /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_aLI /* IMPORTED_LONG_NAMED_INTEGER */,
    aLI /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotActivatePC /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotActivatePC /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_modem /* IMPORTED_LONG_NAMED_INTEGER */,
    modem /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_cathodeRayTube /* IMPORTED_LONG_NAMED_INTEGER */,
    cathodeRayTube /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_looseJack /* IMPORTED_LONG_NAMED_INTEGER */,
    looseJack /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_offHook /* IMPORTED_LONG_NAMED_INTEGER */,
    offHook /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_physicalProblem /* IMPORTED_LONG_NAMED_INTEGER */,
    physicalProblem /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_processorDead /* IMPORTED_LONG_NAMED_INTEGER */,
    processorDead /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_wiringProblem /* IMPORTED_LONG_NAMED_INTEGER */,
    wiringProblem /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_wireBrokeSetBrokePoleDown /* IMPORTED_LONG_NAMED_INTEGER */,
    wireBrokeSetBrokePoleDown /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_noRegister /* IMPORTED_LONG_NAMED_INTEGER */,
    noRegister /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_stuckSender /* IMPORTED_LONG_NAMED_INTEGER */,
    stuckSender /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_otherStationTrouble /* IMPORTED_LONG_NAMED_INTEGER */,
    otherStationTrouble /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_otherCaseGroup /* IMPORTED_LONG_NAMED_INTEGER */,
    otherCaseGroup /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_callTransferProblem /* IMPORTED_LONG_NAMED_INTEGER */,
    callTransferProblem /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_callWaitingProblem /* IMPORTED_LONG_NAMED_INTEGER */,
    callWaitingProblem /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_customCallFeatureDoNotWork /* IMPORTED_LONG_NAMED_INTEGER */,
    customCallFeatureDoNotWork /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_information /* IMPORTED_LONG_NAMED_INTEGER */,
    information /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_threeWayCallingProblem /* IMPORTED_LONG_NAMED_INTEGER */,
    threeWayCallingProblem /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_orderWork /* IMPORTED_LONG_NAMED_INTEGER */,
    orderWork /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_releaseCktRequestedByIC /* IMPORTED_LONG_NAMED_INTEGER */,
    releaseCktRequestedByIC /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_releaseCktRequestedByEC /* IMPORTED_LONG_NAMED_INTEGER */,
    releaseCktRequestedByEC /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_releaseFacilityRequestedByIC /* IMPORTED_LONG_NAMED_INTEGER */,
    releaseFacilityRequestedByIC /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_releaseFacilityRequestedByEC /* IMPORTED_LONG_NAMED_INTEGER */,
    releaseFacilityRequestedByEC /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_requestForRoutine /* IMPORTED_LONG_NAMED_INTEGER */,
    requestForRoutine /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_release /* IMPORTED_LONG_NAMED_INTEGER */,
    release /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_requestDispatch /* IMPORTED_LONG_NAMED_INTEGER */,
    requestDispatch /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_requestMonitorOfCircuit /* IMPORTED_LONG_NAMED_INTEGER */,
    requestMonitorOfCircuit /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_routineTestFailure /* IMPORTED_LONG_NAMED_INTEGER */,
    routineTestFailure /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_lostTimerReport /* IMPORTED_LONG_NAMED_INTEGER */,
    lostTimerReport /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_historicalReports /* IMPORTED_LONG_NAMED_INTEGER */,
    historicalReports /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_switchOrTrunkRelated /* IMPORTED_LONG_NAMED_INTEGER */,
    switchOrTrunkRelated /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_testAssist /* IMPORTED_LONG_NAMED_INTEGER */,
    testAssist /* IMPORTED_SHORT_NAMED_INTEGER */,
    _decode_TroubleType_number,
    _encode_TroubleType_number,
} from '../X790ASN1Module/TroubleType-number.ta.mjs';
export {
    TroubleType_number,
    TroubleType_number_noDialToneGroup /* IMPORTED_LONG_NAMED_INTEGER */,
    noDialToneGroup /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_noDialTone /* IMPORTED_LONG_NAMED_INTEGER */,
    noDialTone /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_slowDialTone /* IMPORTED_LONG_NAMED_INTEGER */,
    slowDialTone /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_circuitDead /* IMPORTED_LONG_NAMED_INTEGER */,
    circuitDead /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotCallOutGroup /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotCallOutGroup /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotCallOut /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotCallOut /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotBreakDialTone /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotBreakDialTone /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_dialToneAfterDialing /* IMPORTED_LONG_NAMED_INTEGER */,
    dialToneAfterDialing /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_highAndDry /* IMPORTED_LONG_NAMED_INTEGER */,
    highAndDry /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotRaise /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotRaise /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_allAccessBusy /* IMPORTED_LONG_NAMED_INTEGER */,
    allAccessBusy /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotCallOut2 /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotCallOut2 /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotCallLongDistance /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotCallLongDistance /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotCallOverseas /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotCallOverseas /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_speedCall /* IMPORTED_LONG_NAMED_INTEGER */,
    speedCall /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotBeCalledGroup /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotBeCalledGroup /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotBeCalled /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotBeCalled /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotBeCalledBusy /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotBeCalledBusy /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_doNotGetCalled /* IMPORTED_LONG_NAMED_INTEGER */,
    doNotGetCalled /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotTripRing /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotTripRing /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_falseRings /* IMPORTED_LONG_NAMED_INTEGER */,
    falseRings /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_doNotAnswer /* IMPORTED_LONG_NAMED_INTEGER */,
    doNotAnswer /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_reachRecording /* IMPORTED_LONG_NAMED_INTEGER */,
    reachRecording /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotRaiseAStation /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotRaiseAStation /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotRaiseADrop /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotRaiseADrop /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotRaiseACircuitLocation /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotRaiseACircuitLocation /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_ringNoAnswer /* IMPORTED_LONG_NAMED_INTEGER */,
    ringNoAnswer /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_reorder /* IMPORTED_LONG_NAMED_INTEGER */,
    reorder /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_alwaysBusy /* IMPORTED_LONG_NAMED_INTEGER */,
    alwaysBusy /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_bellDoesNotRing /* IMPORTED_LONG_NAMED_INTEGER */,
    bellDoesNotRing /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_bellDoesNotRing2 /* IMPORTED_LONG_NAMED_INTEGER */,
    bellDoesNotRing2 /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_bellRingsCanNotAnswer /* IMPORTED_LONG_NAMED_INTEGER */,
    bellRingsCanNotAnswer /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_bellRingsAfterAnswer /* IMPORTED_LONG_NAMED_INTEGER */,
    bellRingsAfterAnswer /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_noRingNoAnswer /* IMPORTED_LONG_NAMED_INTEGER */,
    noRingNoAnswer /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_otherRingTrouble /* IMPORTED_LONG_NAMED_INTEGER */,
    otherRingTrouble /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_receivesCallsForWrongNumber /* IMPORTED_LONG_NAMED_INTEGER */,
    receivesCallsForWrongNumber /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_recordingOnLine /* IMPORTED_LONG_NAMED_INTEGER */,
    recordingOnLine /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotBeHeardGroup /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotBeHeardGroup /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotBeHeard /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotBeHeard /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotHear /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotHear /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_fading /* IMPORTED_LONG_NAMED_INTEGER */,
    fading /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_distant /* IMPORTED_LONG_NAMED_INTEGER */,
    distant /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_reachedWrongNumberGroup /* IMPORTED_LONG_NAMED_INTEGER */,
    reachedWrongNumberGroup /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_wrongNumber /* IMPORTED_LONG_NAMED_INTEGER */,
    wrongNumber /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_circuitOperationGroup /* IMPORTED_LONG_NAMED_INTEGER */,
    circuitOperationGroup /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_open /* IMPORTED_LONG_NAMED_INTEGER */,
    open /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_falseDisconnect /* IMPORTED_LONG_NAMED_INTEGER */,
    falseDisconnect /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_grounded /* IMPORTED_LONG_NAMED_INTEGER */,
    grounded /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotBeSignalled /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotBeSignalled /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotSignal /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotSignal /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_permanentSignal /* IMPORTED_LONG_NAMED_INTEGER */,
    permanentSignal /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_improperSupervision /* IMPORTED_LONG_NAMED_INTEGER */,
    improperSupervision /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_supervision /* IMPORTED_LONG_NAMED_INTEGER */,
    supervision /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotMeet /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotMeet /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotReleaseCircuit /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotReleaseCircuit /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_hungUp /* IMPORTED_LONG_NAMED_INTEGER */,
    hungUp /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_noWinkStart /* IMPORTED_LONG_NAMED_INTEGER */,
    noWinkStart /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_noSF /* IMPORTED_LONG_NAMED_INTEGER */,
    noSF /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_lowSF /* IMPORTED_LONG_NAMED_INTEGER */,
    lowSF /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_noContinuity /* IMPORTED_LONG_NAMED_INTEGER */,
    noContinuity /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_cutCable /* IMPORTED_LONG_NAMED_INTEGER */,
    cutCable /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_openToDEMARC /* IMPORTED_LONG_NAMED_INTEGER */,
    openToDEMARC /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_noRingGenerator /* IMPORTED_LONG_NAMED_INTEGER */,
    noRingGenerator /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_badERL /* IMPORTED_LONG_NAMED_INTEGER */,
    badERL /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_echo /* IMPORTED_LONG_NAMED_INTEGER */,
    echo /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_hollow /* IMPORTED_LONG_NAMED_INTEGER */,
    hollow /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_circuitDeadNoActivity /* IMPORTED_LONG_NAMED_INTEGER */,
    circuitDeadNoActivity /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_circuitDown /* IMPORTED_LONG_NAMED_INTEGER */,
    circuitDown /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_failingCircuit /* IMPORTED_LONG_NAMED_INTEGER */,
    failingCircuit /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_noSignal /* IMPORTED_LONG_NAMED_INTEGER */,
    noSignal /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_seizureOnCircuit /* IMPORTED_LONG_NAMED_INTEGER */,
    seizureOnCircuit /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_lossEPSCSorSwitchedServices /* IMPORTED_LONG_NAMED_INTEGER */,
    lossEPSCSorSwitchedServices /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_monitorCircuit /* IMPORTED_LONG_NAMED_INTEGER */,
    monitorCircuit /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_newServiceNotWorking /* IMPORTED_LONG_NAMED_INTEGER */,
    newServiceNotWorking /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_openEPSCSorSwitchedServices /* IMPORTED_LONG_NAMED_INTEGER */,
    openEPSCSorSwitchedServices /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_otherVoiceDescribeAdditInfo /* IMPORTED_LONG_NAMED_INTEGER */,
    otherVoiceDescribeAdditInfo /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_cutOffsGroup /* IMPORTED_LONG_NAMED_INTEGER */,
    cutOffsGroup /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_cutsOff /* IMPORTED_LONG_NAMED_INTEGER */,
    cutsOff /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_noiseProblemGroup /* IMPORTED_LONG_NAMED_INTEGER */,
    noiseProblemGroup /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_intermittentNoise /* IMPORTED_LONG_NAMED_INTEGER */,
    intermittentNoise /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_noisy /* IMPORTED_LONG_NAMED_INTEGER */,
    noisy /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_foreignTone /* IMPORTED_LONG_NAMED_INTEGER */,
    foreignTone /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_clipping /* IMPORTED_LONG_NAMED_INTEGER */,
    clipping /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_crossTalk /* IMPORTED_LONG_NAMED_INTEGER */,
    crossTalk /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_staticOnLine /* IMPORTED_LONG_NAMED_INTEGER */,
    staticOnLine /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_groundHum /* IMPORTED_LONG_NAMED_INTEGER */,
    groundHum /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_hearsOtherOnLine /* IMPORTED_LONG_NAMED_INTEGER */,
    hearsOtherOnLine /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_humOnLine /* IMPORTED_LONG_NAMED_INTEGER */,
    humOnLine /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_clicking /* IMPORTED_LONG_NAMED_INTEGER */,
    clicking /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_noiseEPSCSorSwitchedServices /* IMPORTED_LONG_NAMED_INTEGER */,
    noiseEPSCSorSwitchedServices /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_levelTroublesGroup /* IMPORTED_LONG_NAMED_INTEGER */,
    levelTroublesGroup /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_lowLevels /* IMPORTED_LONG_NAMED_INTEGER */,
    lowLevels /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_highLevels /* IMPORTED_LONG_NAMED_INTEGER */,
    highLevels /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_longLevels /* IMPORTED_LONG_NAMED_INTEGER */,
    longLevels /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_hotLevels /* IMPORTED_LONG_NAMED_INTEGER */,
    hotLevels /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_highEndRollOff /* IMPORTED_LONG_NAMED_INTEGER */,
    highEndRollOff /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_lowEndRollOff /* IMPORTED_LONG_NAMED_INTEGER */,
    lowEndRollOff /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_needsEqualized /* IMPORTED_LONG_NAMED_INTEGER */,
    needsEqualized /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_lineLoss /* IMPORTED_LONG_NAMED_INTEGER */,
    lineLoss /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_doesNotPassFreqResponse /* IMPORTED_LONG_NAMED_INTEGER */,
    doesNotPassFreqResponse /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_miscellaneousTroubleGroup /* IMPORTED_LONG_NAMED_INTEGER */,
    miscellaneousTroubleGroup /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_hiCapDown /* IMPORTED_LONG_NAMED_INTEGER */,
    hiCapDown /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_carrierDown /* IMPORTED_LONG_NAMED_INTEGER */,
    carrierDown /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_biPolarViolations /* IMPORTED_LONG_NAMED_INTEGER */,
    biPolarViolations /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_frameErrorsHiCap /* IMPORTED_LONG_NAMED_INTEGER */,
    frameErrorsHiCap /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_outOfFrame /* IMPORTED_LONG_NAMED_INTEGER */,
    outOfFrame /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_lossOfSync /* IMPORTED_LONG_NAMED_INTEGER */,
    lossOfSync /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_frameSlips /* IMPORTED_LONG_NAMED_INTEGER */,
    frameSlips /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_noLoopback /* IMPORTED_LONG_NAMED_INTEGER */,
    noLoopback /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotLoopbackDEMARC /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotLoopbackDEMARC /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_recordingOnCircuit /* IMPORTED_LONG_NAMED_INTEGER */,
    recordingOnCircuit /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_linesNeedTagging /* IMPORTED_LONG_NAMED_INTEGER */,
    linesNeedTagging /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_outwatsRingingin /* IMPORTED_LONG_NAMED_INTEGER */,
    outwatsRingingin /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_remoteAccess /* IMPORTED_LONG_NAMED_INTEGER */,
    remoteAccess /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_other /* IMPORTED_LONG_NAMED_INTEGER */,
    other /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_alarm /* IMPORTED_LONG_NAMED_INTEGER */,
    alarm /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_memoryServiceProblemGroup /* IMPORTED_LONG_NAMED_INTEGER */,
    memoryServiceProblemGroup /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_dataTroubleGroup /* IMPORTED_LONG_NAMED_INTEGER */,
    dataTroubleGroup /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotReceiveData /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotReceiveData /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotSendData /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotSendData /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotTransmitCanNotReceive /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotTransmitCanNotReceive /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_noReceive /* IMPORTED_LONG_NAMED_INTEGER */,
    noReceive /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_noResponse /* IMPORTED_LONG_NAMED_INTEGER */,
    noResponse /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_delay /* IMPORTED_LONG_NAMED_INTEGER */,
    delay /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_impulseNoise /* IMPORTED_LONG_NAMED_INTEGER */,
    impulseNoise /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_phaseJitter /* IMPORTED_LONG_NAMED_INTEGER */,
    phaseJitter /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_harmonicDistortion /* IMPORTED_LONG_NAMED_INTEGER */,
    harmonicDistortion /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_highDistortion /* IMPORTED_LONG_NAMED_INTEGER */,
    highDistortion /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_noDataLoopback /* IMPORTED_LONG_NAMED_INTEGER */,
    noDataLoopback /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_noCarrier /* IMPORTED_LONG_NAMED_INTEGER */,
    noCarrier /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_notPolling /* IMPORTED_LONG_NAMED_INTEGER */,
    notPolling /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_dataFramingErrors /* IMPORTED_LONG_NAMED_INTEGER */,
    dataFramingErrors /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_dropOuts /* IMPORTED_LONG_NAMED_INTEGER */,
    dropOuts /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_hits /* IMPORTED_LONG_NAMED_INTEGER */,
    hits /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_noAnswerBack /* IMPORTED_LONG_NAMED_INTEGER */,
    noAnswerBack /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_streamer /* IMPORTED_LONG_NAMED_INTEGER */,
    streamer /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_outOfSpecification /* IMPORTED_LONG_NAMED_INTEGER */,
    outOfSpecification /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotRunToCSU /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotRunToCSU /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotRunToOSU /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotRunToOSU /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_deadDataCircuit /* IMPORTED_LONG_NAMED_INTEGER */,
    deadDataCircuit /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_circuitInLoopback /* IMPORTED_LONG_NAMED_INTEGER */,
    circuitInLoopback /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_errors /* IMPORTED_LONG_NAMED_INTEGER */,
    errors /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_garbledData /* IMPORTED_LONG_NAMED_INTEGER */,
    garbledData /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_invalidData /* IMPORTED_LONG_NAMED_INTEGER */,
    invalidData /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_crossModulation /* IMPORTED_LONG_NAMED_INTEGER */,
    crossModulation /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_slowResponse /* IMPORTED_LONG_NAMED_INTEGER */,
    slowResponse /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_otherDataDescribeAdditInfo /* IMPORTED_LONG_NAMED_INTEGER */,
    otherDataDescribeAdditInfo /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_gettingAllOnes /* IMPORTED_LONG_NAMED_INTEGER */,
    gettingAllOnes /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_slip /* IMPORTED_LONG_NAMED_INTEGER */,
    slip /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_stationTroubleGroup /* IMPORTED_LONG_NAMED_INTEGER */,
    stationTroubleGroup /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_voiceEquipment /* IMPORTED_LONG_NAMED_INTEGER */,
    voiceEquipment /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_dataEquipment /* IMPORTED_LONG_NAMED_INTEGER */,
    dataEquipment /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_videoEquipment /* IMPORTED_LONG_NAMED_INTEGER */,
    videoEquipment /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_otherEquipment /* IMPORTED_LONG_NAMED_INTEGER */,
    otherEquipment /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_stationWiring /* IMPORTED_LONG_NAMED_INTEGER */,
    stationWiring /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_physicalTroubleGroup /* IMPORTED_LONG_NAMED_INTEGER */,
    physicalTroubleGroup /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_lightBurnedOut /* IMPORTED_LONG_NAMED_INTEGER */,
    lightBurnedOut /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_dataset /* IMPORTED_LONG_NAMED_INTEGER */,
    dataset /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_ttySet /* IMPORTED_LONG_NAMED_INTEGER */,
    ttySet /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_highSpeedPrinter /* IMPORTED_LONG_NAMED_INTEGER */,
    highSpeedPrinter /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_aNI /* IMPORTED_LONG_NAMED_INTEGER */,
    aNI /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_aLI /* IMPORTED_LONG_NAMED_INTEGER */,
    aLI /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_canNotActivatePC /* IMPORTED_LONG_NAMED_INTEGER */,
    canNotActivatePC /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_modem /* IMPORTED_LONG_NAMED_INTEGER */,
    modem /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_cathodeRayTube /* IMPORTED_LONG_NAMED_INTEGER */,
    cathodeRayTube /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_looseJack /* IMPORTED_LONG_NAMED_INTEGER */,
    looseJack /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_offHook /* IMPORTED_LONG_NAMED_INTEGER */,
    offHook /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_physicalProblem /* IMPORTED_LONG_NAMED_INTEGER */,
    physicalProblem /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_processorDead /* IMPORTED_LONG_NAMED_INTEGER */,
    processorDead /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_wiringProblem /* IMPORTED_LONG_NAMED_INTEGER */,
    wiringProblem /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_wireBrokeSetBrokePoleDown /* IMPORTED_LONG_NAMED_INTEGER */,
    wireBrokeSetBrokePoleDown /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_noRegister /* IMPORTED_LONG_NAMED_INTEGER */,
    noRegister /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_stuckSender /* IMPORTED_LONG_NAMED_INTEGER */,
    stuckSender /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_otherStationTrouble /* IMPORTED_LONG_NAMED_INTEGER */,
    otherStationTrouble /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_otherCaseGroup /* IMPORTED_LONG_NAMED_INTEGER */,
    otherCaseGroup /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_callTransferProblem /* IMPORTED_LONG_NAMED_INTEGER */,
    callTransferProblem /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_callWaitingProblem /* IMPORTED_LONG_NAMED_INTEGER */,
    callWaitingProblem /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_customCallFeatureDoNotWork /* IMPORTED_LONG_NAMED_INTEGER */,
    customCallFeatureDoNotWork /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_information /* IMPORTED_LONG_NAMED_INTEGER */,
    information /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_threeWayCallingProblem /* IMPORTED_LONG_NAMED_INTEGER */,
    threeWayCallingProblem /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_orderWork /* IMPORTED_LONG_NAMED_INTEGER */,
    orderWork /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_releaseCktRequestedByIC /* IMPORTED_LONG_NAMED_INTEGER */,
    releaseCktRequestedByIC /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_releaseCktRequestedByEC /* IMPORTED_LONG_NAMED_INTEGER */,
    releaseCktRequestedByEC /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_releaseFacilityRequestedByIC /* IMPORTED_LONG_NAMED_INTEGER */,
    releaseFacilityRequestedByIC /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_releaseFacilityRequestedByEC /* IMPORTED_LONG_NAMED_INTEGER */,
    releaseFacilityRequestedByEC /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_requestForRoutine /* IMPORTED_LONG_NAMED_INTEGER */,
    requestForRoutine /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_release /* IMPORTED_LONG_NAMED_INTEGER */,
    release /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_requestDispatch /* IMPORTED_LONG_NAMED_INTEGER */,
    requestDispatch /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_requestMonitorOfCircuit /* IMPORTED_LONG_NAMED_INTEGER */,
    requestMonitorOfCircuit /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_routineTestFailure /* IMPORTED_LONG_NAMED_INTEGER */,
    routineTestFailure /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_lostTimerReport /* IMPORTED_LONG_NAMED_INTEGER */,
    lostTimerReport /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_historicalReports /* IMPORTED_LONG_NAMED_INTEGER */,
    historicalReports /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_switchOrTrunkRelated /* IMPORTED_LONG_NAMED_INTEGER */,
    switchOrTrunkRelated /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleType_number_testAssist /* IMPORTED_LONG_NAMED_INTEGER */,
    testAssist /* IMPORTED_SHORT_NAMED_INTEGER */,
    _decode_TroubleType_number,
    _encode_TroubleType_number,
} from '../X790ASN1Module/TroubleType-number.ta.mjs';

/* START_OF_SYMBOL_DEFINITION TroubleType */
/**
 * @summary TroubleType
 * @description
 *
 * ### ASN.1 Definition:
 *
 * ```asn1
 * TroubleType  ::=  CHOICE {
 *   number
 *     INTEGER {-- Integer values are to be registered in the
 *              -- standard. Administrations may restrict
 *              -- the values to be used.
 *              noDialToneGroup(100), noDialTone(101), slowDialTone(102),
 *              circuitDead(103),
 *              -- No audible tone when the telephone receiver is off-hook
 *              canNotCallOutGroup(200), canNotCallOut(201),
 *              canNotBreakDialTone(203), dialToneAfterDialing(204),
 *              highAndDry(205), canNotRaise(206), allAccessBusy(207),
 *              canNotCallOut2(208), canNotCallLongDistance(209),
 *              canNotCallOverseas(210), speedCall(211), canNotBeCalledGroup(300),
 *              canNotBeCalled(301), canNotBeCalledBusy(302), doNotGetCalled(303),
 *              canNotTripRing(304), falseRings(305), doNotAnswer(306),
 *              reachRecording(307), canNotRaiseAStation(308),
 *              canNotRaiseADrop(309), canNotRaiseACircuitLocation(310),
 *              ringNoAnswer(311), reorder(312), alwaysBusy(313),
 *              bellDoesNotRing(314), bellDoesNotRing2(315),
 *              bellRingsCanNotAnswer(316), bellRingsAfterAnswer(317),
 *              noRingNoAnswer(318), otherRingTrouble(319),
 *              receivesCallsForWrongNumber(320), recordingOnLine(321),
 *              canNotBeHeardGroup(400), canNotBeHeard(401), canNotHear(402),
 *              fading(403), distant(404), reachedWrongNumberGroup(500),
 *              wrongNumber(501), circuitOperationGroup(600), open(601),
 *              falseDisconnect(602), grounded(603), canNotBeSignalled(604),
 *              canNotSignal(605), permanentSignal(606), improperSupervision(607),
 *              supervision(608), canNotMeet(609), canNotReleaseCircuit(610),
 *              hungUp(611), noWinkStart(612), noSF(613), lowSF(614),
 *              noContinuity(615), cutCable(616), openToDEMARC(617),
 *              noRingGenerator(618), badERL(619), echo(620), hollow(621),
 *              circuitDeadNoActivity(622),
 *              -- No activity on circuit at all. Circuit shows no sign of continuity with service provider
 *              circuitDown(623), failingCircuit(624), noSignal(625),
 *              seizureOnCircuit(626), lossEPSCSorSwitchedServices(627),
 *              monitorCircuit(628), newServiceNotWorking(629),
 *              openEPSCSorSwitchedServices(630),
 *              otherVoiceDescribeAdditInfo(631), cutOffsGroup(700), cutsOff(701),
 *              noiseProblemGroup(800), intermittentNoise(801), noisy(802),
 *              foreignTone(803), clipping(804), crossTalk(805),
 *              staticOnLine(806), groundHum(807), hearsOtherOnLine(808),
 *              humOnLine(809), clicking(810), noiseEPSCSorSwitchedServices(811),
 *              levelTroublesGroup(900), lowLevels(901), highLevels(902),
 *              longLevels(903), hotLevels(904), highEndRollOff(905),
 *              lowEndRollOff(906), needsEqualized(907), lineLoss(908),
 *              doesNotPassFreqResponse(909), miscellaneousTroubleGroup(1000),
 *              hiCapDown(1001), carrierDown(1002), biPolarViolations(1003),
 *              frameErrorsHiCap(1004), outOfFrame(1005), lossOfSync(1006),
 *              frameSlips(1007), noLoopback(1008), canNotLoopbackDEMARC(1009),
 *              recordingOnCircuit(1010), linesNeedTagging(1011),
 *              outwatsRingingin(1012), remoteAccess(1013), other(1014),
 *              alarm(1015), memoryServiceProblemGroup(1100),
 *              dataTroubleGroup(1200), canNotReceiveData(1201),
 *              canNotSendData(1202), canNotTransmitCanNotReceive(1203),
 *              noReceive(1204), noResponse(1205), delay(1206),
 *              impulseNoise(1207), phaseJitter(1208), harmonicDistortion(1209),
 *              highDistortion(1210), noDataLoopback(1211), noCarrier(1212),
 *              notPolling(1213), dataFramingErrors(1214), dropOuts(1215),
 *              hits(1216), noAnswerBack(1217), streamer(1218),
 *              outOfSpecification(1219), canNotRunToCSU(1220),
 *              canNotRunToOSU(1221), deadDataCircuit(1222),
 *              circuitInLoopback(1223), errors(1224), garbledData(1225),
 *              invalidData(1226), crossModulation(1227), slowResponse(1228),
 *              otherDataDescribeAdditInfo(1229), gettingAllOnes(1230),
 *              slip(1231), stationTroubleGroup(1300), voiceEquipment(1301),
 *              dataEquipment(1302), videoEquipment(1303), otherEquipment(1304),
 *              stationWiring(1305), physicalTroubleGroup(1400),
 *              lightBurnedOut(1401), dataset(1402), ttySet(1403),
 *              highSpeedPrinter(1404), aNI(1405), aLI(1406),
 *              canNotActivatePC(1407), modem(1408), cathodeRayTube(1409),
 *              looseJack(1410), offHook(1411), physicalProblem(1412),
 *              processorDead(1413), wiringProblem(1414),
 *              wireBrokeSetBrokePoleDown(1415), noRegister(1416),
 *              stuckSender(1417), otherStationTrouble(1418),
 *              otherCaseGroup(1500), callTransferProblem(1501),
 *              callWaitingProblem(1502), customCallFeatureDoNotWork(1503),
 *              information(1504), threeWayCallingProblem(1505), orderWork(1506),
 *              releaseCktRequestedByIC(1507), releaseCktRequestedByEC(1508),
 *              releaseFacilityRequestedByIC(1509),
 *              releaseFacilityRequestedByEC(1510),
 *              requestForRoutine(1511),
 *              --release    (1512)
 *              release(1512), requestDispatch(1513),
 *              requestMonitorOfCircuit(1514), routineTestFailure(1515),
 *              lostTimerReport(1516), historicalReports(1517),
 *              switchOrTrunkRelated(1518), testAssist(1519)},
 *   identifier  OBJECT IDENTIFIER,
 *   ...
 * }
 * ```
 */
export type TroubleType =
    | { number_: TroubleType_number } /* CHOICE_ALT_ROOT */
    | { identifier: OBJECT_IDENTIFIER } /* CHOICE_ALT_ROOT */
    | _Element /* CHOICE_ALT_UNRECOGNIZED_EXT */;
/* END_OF_SYMBOL_DEFINITION TroubleType */

/* START_OF_SYMBOL_DEFINITION _cached_decoder_for_TroubleType */
let _cached_decoder_for_TroubleType: $.ASN1Decoder<TroubleType> | null = null;
/* END_OF_SYMBOL_DEFINITION _cached_decoder_for_TroubleType */

/* START_OF_SYMBOL_DEFINITION _decode_TroubleType */
/**
 * @summary Decodes an ASN.1 element into a(n) TroubleType
 * @function
 * @param {_Element} el The element being decoded.
 * @returns {TroubleType} The decoded data structure.
 */
export function _decode_TroubleType(el: _Element) {
    if (!_cached_decoder_for_TroubleType) {
        _cached_decoder_for_TroubleType = $._decode_extensible_choice<TroubleType>(
            {
                'UNIVERSAL 2': ['number_', _decode_TroubleType_number],
                'UNIVERSAL 6': ['identifier', $._decodeObjectIdentifier],
            }
        );
    }
    return _cached_decoder_for_TroubleType(el);
}
/* END_OF_SYMBOL_DEFINITION _decode_TroubleType */

/* START_OF_SYMBOL_DEFINITION _cached_encoder_for_TroubleType */
let _cached_encoder_for_TroubleType: $.ASN1Encoder<TroubleType> | null = null;
/* END_OF_SYMBOL_DEFINITION _cached_encoder_for_TroubleType */

/* START_OF_SYMBOL_DEFINITION _encode_TroubleType */
/**
 * @summary Encodes a(n) TroubleType into an ASN.1 Element.
 * @function
 * @param {value} el The element being decoded.
 * @param elGetter A function that can be used to get new ASN.1 elements.
 * @returns {_Element} The TroubleType, encoded as an ASN.1 Element.
 */
export function _encode_TroubleType(
    value: TroubleType,
    elGetter: $.ASN1Encoder<TroubleType>
) {
    if (!_cached_encoder_for_TroubleType) {
        _cached_encoder_for_TroubleType = $._encode_choice<TroubleType>(
            {
                number_: _encode_TroubleType_number,
                identifier: $._encodeObjectIdentifier,
            },
            $.BER
        );
    }
    return _cached_encoder_for_TroubleType(value, elGetter);
}

/* END_OF_SYMBOL_DEFINITION _encode_TroubleType */

/* eslint-enable */
