/* eslint-disable */
import {
    itu_t,
    itu_r,
    ccitt,
    iso,
    joint_iso_itu_t,
    joint_iso_ccitt,
    OPTIONAL,
    BOOLEAN,
    INTEGER,
    BIT_STRING,
    OCTET_STRING,
    NULL,
    OBJECT_IDENTIFIER,
    ObjectDescriptor,
    EXTERNAL,
    REAL,
    INSTANCE_OF,
    ENUMERATED,
    EMBEDDED_PDV,
    UTF8String,
    RELATIVE_OID,
    SEQUENCE,
    SEQUENCE_OF,
    SET,
    SET_OF,
    GraphicString,
    NumericString,
    VisibleString,
    PrintableString,
    ISO646String,
    TeletexString,
    GeneralString,
    T61String,
    UniversalString,
    VideotexString,
    BMPString,
    IA5String,
    CharacterString,
    UTCTime,
    GeneralizedTime,
    TIME,
    DATE,
    TIME_OF_DAY,
    DATE_TIME,
    DURATION,
    OID_IRI,
    RELATIVE_OID_IRI,
    TRUE,
    FALSE,
    TRUE_BIT,
    FALSE_BIT,
    PLUS_INFINITY,
    MINUS_INFINITY,
    NOT_A_NUMBER,
    TYPE_IDENTIFIER,
    ABSTRACT_SYNTAX,
    ASN1Element as _Element,
    ASN1TagClass as _TagClass,
    ASN1Construction as _Construction,
    ASN1UniversalType as _UniversalType,
    ObjectIdentifier as _OID,
    External as _External,
    EmbeddedPDV as _PDV,
    ASN1ConstructionError as _ConstructionError,
} from 'asn1-ts';
import * as $ from 'asn1-ts/dist/functional.mjs';
import {
    TroubleFound_number,
    TroubleFound_number_pending /* IMPORTED_LONG_NAMED_INTEGER */,
    pending /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_cameClear /* IMPORTED_LONG_NAMED_INTEGER */,
    cameClear /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_centralOffice /* IMPORTED_LONG_NAMED_INTEGER */,
    centralOffice /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_switchTrouble /* IMPORTED_LONG_NAMED_INTEGER */,
    switchTrouble /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_customerProvidedEquipment /* IMPORTED_LONG_NAMED_INTEGER */,
    customerProvidedEquipment /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_facility /* IMPORTED_LONG_NAMED_INTEGER */,
    facility /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_centralOfficeFacility /* IMPORTED_LONG_NAMED_INTEGER */,
    centralOfficeFacility /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_iCfacility /* IMPORTED_LONG_NAMED_INTEGER */,
    iCfacility /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_interexchangeCarrier /* IMPORTED_LONG_NAMED_INTEGER */,
    interexchangeCarrier /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_information /* IMPORTED_LONG_NAMED_INTEGER */,
    information /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_nonplanClassified /* IMPORTED_LONG_NAMED_INTEGER */,
    nonplanClassified /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_nonplanClassifiedIC /* IMPORTED_LONG_NAMED_INTEGER */,
    nonplanClassifiedIC /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_nonplanClassifiedEA /* IMPORTED_LONG_NAMED_INTEGER */,
    nonplanClassifiedEA /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_noTroubleFound /* IMPORTED_LONG_NAMED_INTEGER */,
    noTroubleFound /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_station /* IMPORTED_LONG_NAMED_INTEGER */,
    station /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_stationProductData /* IMPORTED_LONG_NAMED_INTEGER */,
    stationProductData /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_stationProductTerminal /* IMPORTED_LONG_NAMED_INTEGER */,
    stationProductTerminal /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_stationProductVideo /* IMPORTED_LONG_NAMED_INTEGER */,
    stationProductVideo /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_stationProductVoice /* IMPORTED_LONG_NAMED_INTEGER */,
    stationProductVoice /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_stationWiring /* IMPORTED_LONG_NAMED_INTEGER */,
    stationWiring /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_otherStationEquipment /* IMPORTED_LONG_NAMED_INTEGER */,
    otherStationEquipment /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_foundOKStation /* IMPORTED_LONG_NAMED_INTEGER */,
    foundOKStation /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_servingBureau /* IMPORTED_LONG_NAMED_INTEGER */,
    servingBureau /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_testOK /* IMPORTED_LONG_NAMED_INTEGER */,
    testOK /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_publicServicesCoinSet /* IMPORTED_LONG_NAMED_INTEGER */,
    publicServicesCoinSet /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_customerOperatingInstructions /* IMPORTED_LONG_NAMED_INTEGER */,
    customerOperatingInstructions /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_testedOKVerifiedOK /* IMPORTED_LONG_NAMED_INTEGER */,
    testedOKVerifiedOK /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_coFacilityTestedFoundOK /* IMPORTED_LONG_NAMED_INTEGER */,
    coFacilityTestedFoundOK /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_outsideFacilityTestedFoundOK /* IMPORTED_LONG_NAMED_INTEGER */,
    outsideFacilityTestedFoundOK /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_referredOutToOtherDept /* IMPORTED_LONG_NAMED_INTEGER */,
    referredOutToOtherDept /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_protectiveConnectingArrang /* IMPORTED_LONG_NAMED_INTEGER */,
    protectiveConnectingArrang /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_cpeCustomerResponsibility /* IMPORTED_LONG_NAMED_INTEGER */,
    cpeCustomerResponsibility /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_preService /* IMPORTED_LONG_NAMED_INTEGER */,
    preService /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_preServiceIC /* IMPORTED_LONG_NAMED_INTEGER */,
    preServiceIC /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_preServiceEA /* IMPORTED_LONG_NAMED_INTEGER */,
    preServiceEA /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_serviceNode /* IMPORTED_LONG_NAMED_INTEGER */,
    serviceNode /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_data /* IMPORTED_LONG_NAMED_INTEGER */,
    data /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_customerReferredToVendor /* IMPORTED_LONG_NAMED_INTEGER */,
    customerReferredToVendor /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_exchangeAccess /* IMPORTED_LONG_NAMED_INTEGER */,
    exchangeAccess /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_international /* IMPORTED_LONG_NAMED_INTEGER */,
    international /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_otherProvidedAccess /* IMPORTED_LONG_NAMED_INTEGER */,
    otherProvidedAccess /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_existingReport /* IMPORTED_LONG_NAMED_INTEGER */,
    existingReport /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_cancelExclude /* IMPORTED_LONG_NAMED_INTEGER */,
    cancelExclude /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_paBX /* IMPORTED_LONG_NAMED_INTEGER */,
    paBX /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_outsideWire /* IMPORTED_LONG_NAMED_INTEGER */,
    outsideWire /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_outsideTerminals /* IMPORTED_LONG_NAMED_INTEGER */,
    outsideTerminals /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_outsidePlantEquipment /* IMPORTED_LONG_NAMED_INTEGER */,
    outsidePlantEquipment /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_outsidePlantFiberOptic /* IMPORTED_LONG_NAMED_INTEGER */,
    outsidePlantFiberOptic /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_outsidePlantOther /* IMPORTED_LONG_NAMED_INTEGER */,
    outsidePlantOther /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_coEquipmentOther /* IMPORTED_LONG_NAMED_INTEGER */,
    coEquipmentOther /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_coEquipmentFrames /* IMPORTED_LONG_NAMED_INTEGER */,
    coEquipmentFrames /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_coConcentrator /* IMPORTED_LONG_NAMED_INTEGER */,
    coConcentrator /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_receiverOffHook /* IMPORTED_LONG_NAMED_INTEGER */,
    receiverOffHook /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_cpeAuthorized /* IMPORTED_LONG_NAMED_INTEGER */,
    cpeAuthorized /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_cpeTelcoMaintained /* IMPORTED_LONG_NAMED_INTEGER */,
    cpeTelcoMaintained /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_independentCompany /* IMPORTED_LONG_NAMED_INTEGER */,
    independentCompany /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_cpeCalledNumber /* IMPORTED_LONG_NAMED_INTEGER */,
    cpeCalledNumber /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_assigningProvisioning /* IMPORTED_LONG_NAMED_INTEGER */,
    assigningProvisioning /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_interServiceCenter /* IMPORTED_LONG_NAMED_INTEGER */,
    interServiceCenter /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_referredOut /* IMPORTED_LONG_NAMED_INTEGER */,
    referredOut /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_network /* IMPORTED_LONG_NAMED_INTEGER */,
    network /* IMPORTED_SHORT_NAMED_INTEGER */,
    _decode_TroubleFound_number,
    _encode_TroubleFound_number,
} from '../X790ASN1Module/TroubleFound-number.ta.mjs';
export {
    TroubleFound_number,
    TroubleFound_number_pending /* IMPORTED_LONG_NAMED_INTEGER */,
    pending /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_cameClear /* IMPORTED_LONG_NAMED_INTEGER */,
    cameClear /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_centralOffice /* IMPORTED_LONG_NAMED_INTEGER */,
    centralOffice /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_switchTrouble /* IMPORTED_LONG_NAMED_INTEGER */,
    switchTrouble /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_customerProvidedEquipment /* IMPORTED_LONG_NAMED_INTEGER */,
    customerProvidedEquipment /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_facility /* IMPORTED_LONG_NAMED_INTEGER */,
    facility /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_centralOfficeFacility /* IMPORTED_LONG_NAMED_INTEGER */,
    centralOfficeFacility /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_iCfacility /* IMPORTED_LONG_NAMED_INTEGER */,
    iCfacility /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_interexchangeCarrier /* IMPORTED_LONG_NAMED_INTEGER */,
    interexchangeCarrier /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_information /* IMPORTED_LONG_NAMED_INTEGER */,
    information /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_nonplanClassified /* IMPORTED_LONG_NAMED_INTEGER */,
    nonplanClassified /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_nonplanClassifiedIC /* IMPORTED_LONG_NAMED_INTEGER */,
    nonplanClassifiedIC /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_nonplanClassifiedEA /* IMPORTED_LONG_NAMED_INTEGER */,
    nonplanClassifiedEA /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_noTroubleFound /* IMPORTED_LONG_NAMED_INTEGER */,
    noTroubleFound /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_station /* IMPORTED_LONG_NAMED_INTEGER */,
    station /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_stationProductData /* IMPORTED_LONG_NAMED_INTEGER */,
    stationProductData /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_stationProductTerminal /* IMPORTED_LONG_NAMED_INTEGER */,
    stationProductTerminal /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_stationProductVideo /* IMPORTED_LONG_NAMED_INTEGER */,
    stationProductVideo /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_stationProductVoice /* IMPORTED_LONG_NAMED_INTEGER */,
    stationProductVoice /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_stationWiring /* IMPORTED_LONG_NAMED_INTEGER */,
    stationWiring /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_otherStationEquipment /* IMPORTED_LONG_NAMED_INTEGER */,
    otherStationEquipment /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_foundOKStation /* IMPORTED_LONG_NAMED_INTEGER */,
    foundOKStation /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_servingBureau /* IMPORTED_LONG_NAMED_INTEGER */,
    servingBureau /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_testOK /* IMPORTED_LONG_NAMED_INTEGER */,
    testOK /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_publicServicesCoinSet /* IMPORTED_LONG_NAMED_INTEGER */,
    publicServicesCoinSet /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_customerOperatingInstructions /* IMPORTED_LONG_NAMED_INTEGER */,
    customerOperatingInstructions /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_testedOKVerifiedOK /* IMPORTED_LONG_NAMED_INTEGER */,
    testedOKVerifiedOK /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_coFacilityTestedFoundOK /* IMPORTED_LONG_NAMED_INTEGER */,
    coFacilityTestedFoundOK /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_outsideFacilityTestedFoundOK /* IMPORTED_LONG_NAMED_INTEGER */,
    outsideFacilityTestedFoundOK /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_referredOutToOtherDept /* IMPORTED_LONG_NAMED_INTEGER */,
    referredOutToOtherDept /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_protectiveConnectingArrang /* IMPORTED_LONG_NAMED_INTEGER */,
    protectiveConnectingArrang /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_cpeCustomerResponsibility /* IMPORTED_LONG_NAMED_INTEGER */,
    cpeCustomerResponsibility /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_preService /* IMPORTED_LONG_NAMED_INTEGER */,
    preService /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_preServiceIC /* IMPORTED_LONG_NAMED_INTEGER */,
    preServiceIC /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_preServiceEA /* IMPORTED_LONG_NAMED_INTEGER */,
    preServiceEA /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_serviceNode /* IMPORTED_LONG_NAMED_INTEGER */,
    serviceNode /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_data /* IMPORTED_LONG_NAMED_INTEGER */,
    data /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_customerReferredToVendor /* IMPORTED_LONG_NAMED_INTEGER */,
    customerReferredToVendor /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_exchangeAccess /* IMPORTED_LONG_NAMED_INTEGER */,
    exchangeAccess /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_international /* IMPORTED_LONG_NAMED_INTEGER */,
    international /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_otherProvidedAccess /* IMPORTED_LONG_NAMED_INTEGER */,
    otherProvidedAccess /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_existingReport /* IMPORTED_LONG_NAMED_INTEGER */,
    existingReport /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_cancelExclude /* IMPORTED_LONG_NAMED_INTEGER */,
    cancelExclude /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_paBX /* IMPORTED_LONG_NAMED_INTEGER */,
    paBX /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_outsideWire /* IMPORTED_LONG_NAMED_INTEGER */,
    outsideWire /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_outsideTerminals /* IMPORTED_LONG_NAMED_INTEGER */,
    outsideTerminals /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_outsidePlantEquipment /* IMPORTED_LONG_NAMED_INTEGER */,
    outsidePlantEquipment /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_outsidePlantFiberOptic /* IMPORTED_LONG_NAMED_INTEGER */,
    outsidePlantFiberOptic /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_outsidePlantOther /* IMPORTED_LONG_NAMED_INTEGER */,
    outsidePlantOther /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_coEquipmentOther /* IMPORTED_LONG_NAMED_INTEGER */,
    coEquipmentOther /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_coEquipmentFrames /* IMPORTED_LONG_NAMED_INTEGER */,
    coEquipmentFrames /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_coConcentrator /* IMPORTED_LONG_NAMED_INTEGER */,
    coConcentrator /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_receiverOffHook /* IMPORTED_LONG_NAMED_INTEGER */,
    receiverOffHook /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_cpeAuthorized /* IMPORTED_LONG_NAMED_INTEGER */,
    cpeAuthorized /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_cpeTelcoMaintained /* IMPORTED_LONG_NAMED_INTEGER */,
    cpeTelcoMaintained /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_independentCompany /* IMPORTED_LONG_NAMED_INTEGER */,
    independentCompany /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_cpeCalledNumber /* IMPORTED_LONG_NAMED_INTEGER */,
    cpeCalledNumber /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_assigningProvisioning /* IMPORTED_LONG_NAMED_INTEGER */,
    assigningProvisioning /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_interServiceCenter /* IMPORTED_LONG_NAMED_INTEGER */,
    interServiceCenter /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_referredOut /* IMPORTED_LONG_NAMED_INTEGER */,
    referredOut /* IMPORTED_SHORT_NAMED_INTEGER */,
    TroubleFound_number_network /* IMPORTED_LONG_NAMED_INTEGER */,
    network /* IMPORTED_SHORT_NAMED_INTEGER */,
    _decode_TroubleFound_number,
    _encode_TroubleFound_number,
} from '../X790ASN1Module/TroubleFound-number.ta.mjs';

/* START_OF_SYMBOL_DEFINITION TroubleFound */
/**
 * @summary TroubleFound
 * @description
 *
 * ### ASN.1 Definition:
 *
 * ```asn1
 * TroubleFound  ::=  CHOICE {
 *   number
 *     INTEGER {-- Integer values are to be registered in the
 *              -- standard. Administrations may restrict
 *              -- the values to be used.
 *              pending(0), cameClear(1), centralOffice(2), switchTrouble(3),
 *              customerProvidedEquipment(4), facility(5),
 *              centralOfficeFacility(6), iCfacility(7), interexchangeCarrier(8),
 *              information(9), nonplanClassified(10), nonplanClassifiedIC(11),
 *              nonplanClassifiedEA(12), noTroubleFound(13), station(14),
 *              stationProductData(15), stationProductTerminal(16),
 *              stationProductVideo(17), stationProductVoice(18),
 *              stationWiring(19), otherStationEquipment(20), foundOKStation(21),
 *              servingBureau(22), testOK(23), publicServicesCoinSet(24),
 *              customerOperatingInstructions(25), testedOKVerifiedOK(26),
 *              coFacilityTestedFoundOK(27), outsideFacilityTestedFoundOK(28),
 *              referredOutToOtherDept(29), protectiveConnectingArrang(30),
 *              cpeCustomerResponsibility(31), preService(32), preServiceIC(33),
 *              preServiceEA(34), serviceNode(35), data(36),
 *              customerReferredToVendor(37), exchangeAccess(38),
 *              international(39), otherProvidedAccess(40), existingReport(41),
 *              cancelExclude(42), paBX(43), outsideWire(44),
 *              outsideTerminals(45), outsidePlantEquipment(46),
 *              outsidePlantFiberOptic(47), outsidePlantOther(48),
 *              coEquipmentOther(49), coEquipmentFrames(50), coConcentrator(51),
 *              receiverOffHook(52), cpeAuthorized(53), cpeTelcoMaintained(54),
 *              independentCompany(55), cpeCalledNumber(56),
 *              assigningProvisioning(57), interServiceCenter(58),
 *              referredOut(59), network(60)},
 *   identifier           OBJECT IDENTIFIER,
 *   noTroubleFoundValue  NULL, -- used when Trouble Found not relevant
 *   ...
 * }
 * ```
 */
export type TroubleFound =
    | { number_: TroubleFound_number } /* CHOICE_ALT_ROOT */
    | { identifier: OBJECT_IDENTIFIER } /* CHOICE_ALT_ROOT */
    | { noTroubleFoundValue: NULL } /* CHOICE_ALT_ROOT */
    | _Element /* CHOICE_ALT_UNRECOGNIZED_EXT */;
/* END_OF_SYMBOL_DEFINITION TroubleFound */

/* START_OF_SYMBOL_DEFINITION _cached_decoder_for_TroubleFound */
let _cached_decoder_for_TroubleFound: $.ASN1Decoder<TroubleFound> | null = null;
/* END_OF_SYMBOL_DEFINITION _cached_decoder_for_TroubleFound */

/* START_OF_SYMBOL_DEFINITION _decode_TroubleFound */
/**
 * @summary Decodes an ASN.1 element into a(n) TroubleFound
 * @function
 * @param {_Element} el The element being decoded.
 * @returns {TroubleFound} The decoded data structure.
 */
export function _decode_TroubleFound(el: _Element) {
    if (!_cached_decoder_for_TroubleFound) {
        _cached_decoder_for_TroubleFound = $._decode_extensible_choice<TroubleFound>(
            {
                'UNIVERSAL 2': ['number_', _decode_TroubleFound_number],
                'UNIVERSAL 6': ['identifier', $._decodeObjectIdentifier],
                'UNIVERSAL 5': ['noTroubleFoundValue', $._decodeNull],
            }
        );
    }
    return _cached_decoder_for_TroubleFound(el);
}
/* END_OF_SYMBOL_DEFINITION _decode_TroubleFound */

/* START_OF_SYMBOL_DEFINITION _cached_encoder_for_TroubleFound */
let _cached_encoder_for_TroubleFound: $.ASN1Encoder<TroubleFound> | null = null;
/* END_OF_SYMBOL_DEFINITION _cached_encoder_for_TroubleFound */

/* START_OF_SYMBOL_DEFINITION _encode_TroubleFound */
/**
 * @summary Encodes a(n) TroubleFound into an ASN.1 Element.
 * @function
 * @param {value} el The element being decoded.
 * @param elGetter A function that can be used to get new ASN.1 elements.
 * @returns {_Element} The TroubleFound, encoded as an ASN.1 Element.
 */
export function _encode_TroubleFound(
    value: TroubleFound,
    elGetter: $.ASN1Encoder<TroubleFound>
) {
    if (!_cached_encoder_for_TroubleFound) {
        _cached_encoder_for_TroubleFound = $._encode_choice<TroubleFound>(
            {
                number_: _encode_TroubleFound_number,
                identifier: $._encodeObjectIdentifier,
                noTroubleFoundValue: $._encodeNull,
            },
            $.BER
        );
    }
    return _cached_encoder_for_TroubleFound(value, elGetter);
}

/* END_OF_SYMBOL_DEFINITION _encode_TroubleFound */

/* eslint-enable */
