export type {
    CRLReason,
} from "@wildboar/pki-stub";
export {
    _decode_CRLReason,
    _encode_CRLReason,
    unspecified,
    keyCompromise,
    cACompromise,
    affiliationChanged,
    superseded,
    cessationOfOperation,
    certificateHold,
    removeFromCRL,
    privilegeWithdrawn,
    aACompromise,
    weakAlgorithmOrKey,
    CRLReason_unspecified,
    CRLReason_keyCompromise,
    CRLReason_cACompromise,
    CRLReason_affiliationChanged,
    CRLReason_superseded,
    CRLReason_cessationOfOperation,
    CRLReason_certificateHold,
    CRLReason_removeFromCRL,
    CRLReason_privilegeWithdrawn,
    CRLReason_aACompromise,
    CRLReason_weakAlgorithmOrKey,
    _enum_for_CRLReason,
} from "@wildboar/pki-stub";
