/* eslint-disable */
import {
    ASN1Element as _Element,
    ASN1TagClass as _TagClass,
    ASN1Construction as _Construction,
    ASN1UniversalType as _UniversalType,
    ObjectIdentifier as _OID,
    External as _External,
    EmbeddedPDV as _PDV,
    ASN1ConstructionError as _ConstructionError,
} from '@wildboar/asn1';
import * as $ from '@wildboar/asn1/functional';

/**
 * @summary DLExpansionProhibited
 * @description
 *
 * `DLExpansionProhibited`. This argument indicates whether DL-expansion within the MTS
 * shall occur for any recipient-name which denotes a DL. It may be generated by the
 * originator of the message. See ITU-T X.411 (1999), §8.2.1.1.1.6. ENUMERATED value `0`
 * is a named variant, not a sentinel for 'absent' or 'unspecified'.
 *
 * ### ASN.1 Definition:
 *
 * ```asn1
 * DLExpansionProhibited  ::=  ENUMERATED {
 *   dl-expansion-allowed(0), dl-expansion-prohibited(1)}
 * ```
 *
 * @enum {number}
 */
export enum _enum_for_DLExpansionProhibited {
    dl_expansion_allowed = 0,
    dl_expansion_prohibited = 1,
}

/**
 * @summary DLExpansionProhibited
 * @description
 *
 * ### ASN.1 Definition:
 *
 * ```asn1
 * DLExpansionProhibited  ::=  ENUMERATED {
 *   dl-expansion-allowed(0), dl-expansion-prohibited(1)}
 * ```
 *
 * @enum {number}
 */
export type DLExpansionProhibited = _enum_for_DLExpansionProhibited;

/**
 * @summary DLExpansionProhibited
 * @description
 *
 * ### ASN.1 Definition:
 *
 * ```asn1
 * DLExpansionProhibited  ::=  ENUMERATED {
 *   dl-expansion-allowed(0), dl-expansion-prohibited(1)}
 * ```
 *
 * @enum {number}
 */
export const DLExpansionProhibited = _enum_for_DLExpansionProhibited;

/**
 * @summary DLExpansionProhibited_dl_expansion_allowed
 * @constant
 * @type {number}
 */
export const DLExpansionProhibited_dl_expansion_allowed: DLExpansionProhibited =
    DLExpansionProhibited.dl_expansion_allowed; /* LONG_NAMED_ENUMERATED_VALUE */

/**
 * @summary dl_expansion_allowed
 * @constant
 * @type {number}
 */
export const dl_expansion_allowed: DLExpansionProhibited =
    DLExpansionProhibited.dl_expansion_allowed; /* SHORT_NAMED_ENUMERATED_VALUE */

/**
 * @summary DLExpansionProhibited_dl_expansion_prohibited
 * @constant
 * @type {number}
 */
export const DLExpansionProhibited_dl_expansion_prohibited: DLExpansionProhibited =
    DLExpansionProhibited.dl_expansion_prohibited; /* LONG_NAMED_ENUMERATED_VALUE */

/**
 * @summary dl_expansion_prohibited
 * @constant
 * @type {number}
 */
export const dl_expansion_prohibited: DLExpansionProhibited =
    DLExpansionProhibited.dl_expansion_prohibited; /* SHORT_NAMED_ENUMERATED_VALUE */


export const _decode_DLExpansionProhibited = $._decodeEnumerated;


export const _encode_DLExpansionProhibited = $._encodeEnumerated;


/* eslint-enable */
