/* eslint-disable */
import {
    ASN1Element as _Element,
    ASN1TagClass as _TagClass,
    ASN1Construction as _Construction,
    ASN1UniversalType as _UniversalType,
    ObjectIdentifier as _OID,
    External as _External,
    EmbeddedPDV as _PDV,
    ASN1ConstructionError as _ConstructionError,
} from '@wildboar/asn1';
import * as $ from '@wildboar/asn1/functional';
import {
    Certificates,
    _decode_Certificates,
    _encode_Certificates,
} from '@wildboar/x500/AuthenticationFramework';
/**
 * @summary OriginatingMTACertificate
 * @description
 *
 * `OriginatingMTACertificate`. This result contains the certificate of the MTA to which
 * the message has been submitted (the originating-MTA). It shall be generated by a
 * trusted source (e.g., a certification-authority), and may be supplied by the
 * originating-MTA, if the originator of the message requested proof-of-submission (see
 * 8.2.1.1.1.31) and an asymmetric-encryption-algorithm is used to compute the
 * proof-of-submission. See ITU-T X.411 (1999), §8.2.1.1.2.3.
 *
 * ### ASN.1 Definition:
 *
 * ```asn1
 * OriginatingMTACertificate  ::=  Certificates
 * ```
 */
export type OriginatingMTACertificate = Certificates; // DefinedType

let _cached_decoder_for_OriginatingMTACertificate: $.ASN1Decoder<OriginatingMTACertificate> | null = null;

/**
 * @summary Decodes an ASN.1 element into a(n) OriginatingMTACertificate
 * @function
 * @param {_Element} el The element being decoded.
 * @returns {OriginatingMTACertificate} The decoded data structure.
 */
export function _decode_OriginatingMTACertificate(el: _Element): OriginatingMTACertificate {
    if (!_cached_decoder_for_OriginatingMTACertificate) {
        _cached_decoder_for_OriginatingMTACertificate = _decode_Certificates;
    }
    return _cached_decoder_for_OriginatingMTACertificate(el);
}

let _cached_encoder_for_OriginatingMTACertificate: $.ASN1Encoder<OriginatingMTACertificate> | null = null;

/**
 * @summary Encodes a(n) OriginatingMTACertificate into an ASN.1 Element.
 * @function
 * @param value The element being encoded.
 * @param elGetter A function that can be used to get new ASN.1 elements.
 * @returns {_Element} The OriginatingMTACertificate, encoded as an ASN.1 Element.
 */
export function _encode_OriginatingMTACertificate(
    value: OriginatingMTACertificate,
    elGetter: $.ASN1Encoder<OriginatingMTACertificate>
): _Element {
    if (!_cached_encoder_for_OriginatingMTACertificate) {
        _cached_encoder_for_OriginatingMTACertificate = _encode_Certificates;
    }
    return _cached_encoder_for_OriginatingMTACertificate(value, elGetter);
}


/* eslint-enable */
