/* eslint-disable */
import {
    ASN1Element as _Element,
    ASN1TagClass as _TagClass,
    ASN1Construction as _Construction,
    ASN1UniversalType as _UniversalType,
    ObjectIdentifier as _OID,
    External as _External,
    EmbeddedPDV as _PDV,
    ASN1ConstructionError as _ConstructionError,
} from '@wildboar/asn1';
import {
    _decode_ExtensionType,
    _encode_ExtensionType,
} from '../MTSAbstractService/ExtensionType.ta.mjs';
import {
    _decode_Criticality,
    _encode_Criticality,
} from '../MTSAbstractService/Criticality.ta.mjs';
import {
    PhysicalForwardingAddress,
    _decode_PhysicalForwardingAddress,
    _encode_PhysicalForwardingAddress,
} from '../MTSAbstractService/PhysicalForwardingAddress.ta.mjs';
import { type EXTENSION } from '../MTSAbstractService/EXTENSION.oca.mjs';
/**
 * @summary physical_forwarding_address
 * @description
 *
 * Information object `physical_forwarding_address`. This argument contains the new
 * postal-OR-address of the physical-recipient of the message. It may be generated by the
 * associated PDAU of the originating-MTA of the report, if the originator of the message
 * requested the physical-forwarding-address of the recipient (see 8.2.1.1.1.16). See
 * ITU-T X.411 (1999), §8.3.1.2.1.8.
 *
 * ### ASN.1 Definition:
 *
 * ```asn1
 * physical-forwarding-address EXTENSION ::= {
 *   PhysicalForwardingAddress,
 *   IDENTIFIED BY  standard-extension:27
 * }
 * ```
 *
 * @constant
 * @type {EXTENSION<PhysicalForwardingAddress>}
 * @implements {EXTENSION<PhysicalForwardingAddress>}
 */
export const physical_forwarding_address: EXTENSION<PhysicalForwardingAddress> = {
    class: 'EXTENSION',
    decoderFor: {
        '&Type': _decode_PhysicalForwardingAddress,
    },
    encoderFor: {
        '&Type': _encode_PhysicalForwardingAddress,
    },
    '&id': {
        standard_extension: 27,
    } /* OBJECT_FIELD_SETTING */ /* UNIQUE_OBJECT_FIELD_SETTING */,
    '&Type': 0 as never /* OBJECT_FIELD_SETTING OBJECT_TYPE_FIELD_SETTING */,
    '&recommended': new Uint8ClampedArray(
        []
    ) /* OBJECT_FIELD_SETTING DEFAULT_OBJECT_FIELD_SETTING */,
};

/* eslint-enable */
