/* eslint-disable */
import {
    TeletexString,
    ASN1Element as _Element,
    ASN1TagClass as _TagClass,
    ASN1Construction as _Construction,
    ASN1UniversalType as _UniversalType,
    ObjectIdentifier as _OID,
    External as _External,
    EmbeddedPDV as _PDV,
    ASN1ConstructionError as _ConstructionError,
} from '@wildboar/asn1';
import * as $ from '@wildboar/asn1/functional';

/**
 * @summary RecipientNumberForAdvice
 * @description
 *
 * `RecipientNumberForAdvice`. This argument contains the Telephone, Telex or Teletex
 * number of the recipient, to be used in conjunction with the
 * counter-collection-with-advice and bureau-fax-delivery physical-delivery-modes . It
 * may be generated by the originator of the message if the requested-delivery-method
 * argument specifies that physical-delivery is required to the recipient, or if the
 * originator of the message supplied a… See ITU-T X.411 (1999), §8.2.1.1.1.19.
 *
 * ### ASN.1 Definition:
 *
 * ```asn1
 * RecipientNumberForAdvice  ::=
 *   TeletexString(SIZE (1..ub-recipient-number-for-advice-length))
 * ```
 */
export type RecipientNumberForAdvice = TeletexString; // TeletexString


export const _decode_RecipientNumberForAdvice = $._decodeTeletexString;


export const _encode_RecipientNumberForAdvice = $._encodeTeletexString;


/* eslint-enable */
