/* eslint-disable */
import {
    INTEGER,
    ASN1Element as _Element,
    ASN1TagClass as _TagClass,
    ASN1Construction as _Construction,
    ASN1UniversalType as _UniversalType,
    ObjectIdentifier as _OID,
    External as _External,
    EmbeddedPDV as _PDV,
    ASN1ConstructionError as _ConstructionError,
} from '@wildboar/asn1';
import * as $ from '@wildboar/asn1/functional';

/**
 * @summary RegisteredMailType
 * @description
 *
 * `RegisteredMailType`. This argument indicates the type of registered mail service to
 * be used to physically deliver the message to the recipient. It may be generated by the
 * originator of the message if the requested-delivery-method argument specifies that
 * physical-delivery is required to the recipient, or if the originator of the message
 * supplied a postal-OR-address for the recipient. See ITU-T X.411 (1999), §8.2.1.1.1.18.
 *
 * ### ASN.1 Definition:
 *
 * ```asn1
 * RegisteredMailType  ::=  INTEGER {
 *   non-registered-mail(0), registered-mail(1),
 *   registered-mail-to-addressee-in-person(2)}(0..ub-integer-options)
 * ```
 */
export type RegisteredMailType = INTEGER;

/**
 * @summary RegisteredMailType_non_registered_mail
 * @constant
 * @type {number}
 */
export const RegisteredMailType_non_registered_mail: RegisteredMailType = 0; /* LONG_NAMED_INTEGER_VALUE */

/**
 * @summary RegisteredMailType_non_registered_mail
 * @constant
 * @type {number}
 */
export const non_registered_mail: RegisteredMailType = RegisteredMailType_non_registered_mail; /* SHORT_NAMED_INTEGER_VALUE */

/**
 * @summary RegisteredMailType_registered_mail
 * @constant
 * @type {number}
 */
export const RegisteredMailType_registered_mail: RegisteredMailType = 1; /* LONG_NAMED_INTEGER_VALUE */

/**
 * @summary RegisteredMailType_registered_mail
 * @constant
 * @type {number}
 */
export const registered_mail: RegisteredMailType = RegisteredMailType_registered_mail; /* SHORT_NAMED_INTEGER_VALUE */

/**
 * @summary RegisteredMailType_registered_mail_to_addressee_in_person
 * @constant
 * @type {number}
 */
export const RegisteredMailType_registered_mail_to_addressee_in_person: RegisteredMailType = 2; /* LONG_NAMED_INTEGER_VALUE */

/**
 * @summary RegisteredMailType_registered_mail_to_addressee_in_person
 * @constant
 * @type {number}
 */
export const registered_mail_to_addressee_in_person: RegisteredMailType = RegisteredMailType_registered_mail_to_addressee_in_person; /* SHORT_NAMED_INTEGER_VALUE */


export const _decode_RegisteredMailType = $._decodeInteger;


export const _encode_RegisteredMailType = $._encodeInteger;


/* eslint-enable */
