/* eslint-disable */
import {
    itu_t,
    itu_r,
    ccitt,
    iso,
    joint_iso_itu_t,
    joint_iso_ccitt,
    OPTIONAL,
    BOOLEAN,
    INTEGER,
    BIT_STRING,
    OCTET_STRING,
    NULL,
    OBJECT_IDENTIFIER,
    ObjectDescriptor,
    EXTERNAL,
    REAL,
    INSTANCE_OF,
    ENUMERATED,
    EMBEDDED_PDV,
    UTF8String,
    RELATIVE_OID,
    SEQUENCE,
    SEQUENCE_OF,
    SET,
    SET_OF,
    GraphicString,
    NumericString,
    VisibleString,
    PrintableString,
    ISO646String,
    TeletexString,
    GeneralString,
    T61String,
    UniversalString,
    VideotexString,
    BMPString,
    IA5String,
    CharacterString,
    UTCTime,
    GeneralizedTime,
    TIME,
    DATE,
    TIME_OF_DAY,
    DATE_TIME,
    DURATION,
    OID_IRI,
    RELATIVE_OID_IRI,
    TRUE,
    FALSE,
    TRUE_BIT,
    FALSE_BIT,
    PLUS_INFINITY,
    MINUS_INFINITY,
    NOT_A_NUMBER,
    TYPE_IDENTIFIER,
    ABSTRACT_SYNTAX,
    ASN1Element as _Element,
    ASN1TagClass as _TagClass,
    ASN1Construction as _Construction,
    ASN1UniversalType as _UniversalType,
    ObjectIdentifier as _OID,
    External as _External,
    EmbeddedPDV as _PDV,
    ASN1ConstructionError as _ConstructionError,
} from 'asn1-ts';
import * as $ from 'asn1-ts/dist/functional.mjs';
import {
    Priority,
    _decode_Priority,
    _encode_Priority,
} from '@wildboar/rose/src/lib/modules/Remote-Operations-Information-Objects/Priority.ta.js';
export {
    Priority,
    _decode_Priority,
    _encode_Priority,
} from '@wildboar/rose/src/lib/modules/Remote-Operations-Information-Objects/Priority.ta.js';
import {
    Code,
    _decode_Code,
    _encode_Code,
} from '@wildboar/rose/src/lib/modules/Remote-Operations-Information-Objects/Code.ta.js';
export {
    Code,
    _decode_Code,
    _encode_Code,
} from '@wildboar/rose/src/lib/modules/Remote-Operations-Information-Objects/Code.ta.js';
import {
    SecurityProblem,
    SecurityProblem_assemby_instructions_conflict_with_security_services /* IMPORTED_LONG_NAMED_INTEGER */,
    assemby_instructions_conflict_with_security_services /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_authentication_problem /* IMPORTED_LONG_NAMED_INTEGER */,
    authentication_problem /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_authentication_failure_on_subject_message /* IMPORTED_LONG_NAMED_INTEGER */,
    authentication_failure_on_subject_message /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_confidentiality_association_problem /* IMPORTED_LONG_NAMED_INTEGER */,
    confidentiality_association_problem /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_decryption_failed /* IMPORTED_LONG_NAMED_INTEGER */,
    decryption_failed /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_decryption_key_unobtainable /* IMPORTED_LONG_NAMED_INTEGER */,
    decryption_key_unobtainable /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_failure_of_proof_of_message /* IMPORTED_LONG_NAMED_INTEGER */,
    failure_of_proof_of_message /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_forbidden_user_security_label_register /* IMPORTED_LONG_NAMED_INTEGER */,
    forbidden_user_security_label_register /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_incompatible_change_with_original_security_context /* IMPORTED_LONG_NAMED_INTEGER */,
    incompatible_change_with_original_security_context /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_integrity_failure_on_subject_message /* IMPORTED_LONG_NAMED_INTEGER */,
    integrity_failure_on_subject_message /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_invalid_security_label /* IMPORTED_LONG_NAMED_INTEGER */,
    invalid_security_label /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_invalid_security_label_update /* IMPORTED_LONG_NAMED_INTEGER */,
    invalid_security_label_update /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_key_failure /* IMPORTED_LONG_NAMED_INTEGER */,
    key_failure /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_mandatory_parameter_absence /* IMPORTED_LONG_NAMED_INTEGER */,
    mandatory_parameter_absence /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_operation_security_failure /* IMPORTED_LONG_NAMED_INTEGER */,
    operation_security_failure /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_redirection_prohibited /* IMPORTED_LONG_NAMED_INTEGER */,
    redirection_prohibited /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_refused_alternate_recipient_name /* IMPORTED_LONG_NAMED_INTEGER */,
    refused_alternate_recipient_name /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_repudiation_failure_of_message /* IMPORTED_LONG_NAMED_INTEGER */,
    repudiation_failure_of_message /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_responder_credentials_checking_problem /* IMPORTED_LONG_NAMED_INTEGER */,
    responder_credentials_checking_problem /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_security_context_failure /* IMPORTED_LONG_NAMED_INTEGER */,
    security_context_failure /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_security_context_problem /* IMPORTED_LONG_NAMED_INTEGER */,
    security_context_problem /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_security_policy_violation /* IMPORTED_LONG_NAMED_INTEGER */,
    security_policy_violation /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_security_services_refusal /* IMPORTED_LONG_NAMED_INTEGER */,
    security_services_refusal /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_token_decryption_failed /* IMPORTED_LONG_NAMED_INTEGER */,
    token_decryption_failed /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_token_error /* IMPORTED_LONG_NAMED_INTEGER */,
    token_error /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_unable_to_aggregate_security_labels /* IMPORTED_LONG_NAMED_INTEGER */,
    unable_to_aggregate_security_labels /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_unauthorised_dl_name /* IMPORTED_LONG_NAMED_INTEGER */,
    unauthorised_dl_name /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_unauthorised_entry_class /* IMPORTED_LONG_NAMED_INTEGER */,
    unauthorised_entry_class /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_unauthorised_originally_intended_recipient_name /* IMPORTED_LONG_NAMED_INTEGER */,
    unauthorised_originally_intended_recipient_name /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_unauthorised_originator_name /* IMPORTED_LONG_NAMED_INTEGER */,
    unauthorised_originator_name /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_unauthorised_recipient_name /* IMPORTED_LONG_NAMED_INTEGER */,
    unauthorised_recipient_name /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_unauthorised_security_label_update /* IMPORTED_LONG_NAMED_INTEGER */,
    unauthorised_security_label_update /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_unauthorised_user_name /* IMPORTED_LONG_NAMED_INTEGER */,
    unauthorised_user_name /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_unknown_security_label /* IMPORTED_LONG_NAMED_INTEGER */,
    unknown_security_label /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_unsupported_algorithm_identifier /* IMPORTED_LONG_NAMED_INTEGER */,
    unsupported_algorithm_identifier /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_unsupported_security_policy /* IMPORTED_LONG_NAMED_INTEGER */,
    unsupported_security_policy /* IMPORTED_SHORT_NAMED_INTEGER */,
    _decode_SecurityProblem,
    _encode_SecurityProblem,
} from '../MTSAbstractService/SecurityProblem.ta.js';
export {
    SecurityProblem,
    SecurityProblem_assemby_instructions_conflict_with_security_services /* IMPORTED_LONG_NAMED_INTEGER */,
    assemby_instructions_conflict_with_security_services /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_authentication_problem /* IMPORTED_LONG_NAMED_INTEGER */,
    authentication_problem /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_authentication_failure_on_subject_message /* IMPORTED_LONG_NAMED_INTEGER */,
    authentication_failure_on_subject_message /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_confidentiality_association_problem /* IMPORTED_LONG_NAMED_INTEGER */,
    confidentiality_association_problem /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_decryption_failed /* IMPORTED_LONG_NAMED_INTEGER */,
    decryption_failed /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_decryption_key_unobtainable /* IMPORTED_LONG_NAMED_INTEGER */,
    decryption_key_unobtainable /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_failure_of_proof_of_message /* IMPORTED_LONG_NAMED_INTEGER */,
    failure_of_proof_of_message /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_forbidden_user_security_label_register /* IMPORTED_LONG_NAMED_INTEGER */,
    forbidden_user_security_label_register /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_incompatible_change_with_original_security_context /* IMPORTED_LONG_NAMED_INTEGER */,
    incompatible_change_with_original_security_context /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_integrity_failure_on_subject_message /* IMPORTED_LONG_NAMED_INTEGER */,
    integrity_failure_on_subject_message /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_invalid_security_label /* IMPORTED_LONG_NAMED_INTEGER */,
    invalid_security_label /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_invalid_security_label_update /* IMPORTED_LONG_NAMED_INTEGER */,
    invalid_security_label_update /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_key_failure /* IMPORTED_LONG_NAMED_INTEGER */,
    key_failure /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_mandatory_parameter_absence /* IMPORTED_LONG_NAMED_INTEGER */,
    mandatory_parameter_absence /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_operation_security_failure /* IMPORTED_LONG_NAMED_INTEGER */,
    operation_security_failure /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_redirection_prohibited /* IMPORTED_LONG_NAMED_INTEGER */,
    redirection_prohibited /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_refused_alternate_recipient_name /* IMPORTED_LONG_NAMED_INTEGER */,
    refused_alternate_recipient_name /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_repudiation_failure_of_message /* IMPORTED_LONG_NAMED_INTEGER */,
    repudiation_failure_of_message /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_responder_credentials_checking_problem /* IMPORTED_LONG_NAMED_INTEGER */,
    responder_credentials_checking_problem /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_security_context_failure /* IMPORTED_LONG_NAMED_INTEGER */,
    security_context_failure /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_security_context_problem /* IMPORTED_LONG_NAMED_INTEGER */,
    security_context_problem /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_security_policy_violation /* IMPORTED_LONG_NAMED_INTEGER */,
    security_policy_violation /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_security_services_refusal /* IMPORTED_LONG_NAMED_INTEGER */,
    security_services_refusal /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_token_decryption_failed /* IMPORTED_LONG_NAMED_INTEGER */,
    token_decryption_failed /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_token_error /* IMPORTED_LONG_NAMED_INTEGER */,
    token_error /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_unable_to_aggregate_security_labels /* IMPORTED_LONG_NAMED_INTEGER */,
    unable_to_aggregate_security_labels /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_unauthorised_dl_name /* IMPORTED_LONG_NAMED_INTEGER */,
    unauthorised_dl_name /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_unauthorised_entry_class /* IMPORTED_LONG_NAMED_INTEGER */,
    unauthorised_entry_class /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_unauthorised_originally_intended_recipient_name /* IMPORTED_LONG_NAMED_INTEGER */,
    unauthorised_originally_intended_recipient_name /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_unauthorised_originator_name /* IMPORTED_LONG_NAMED_INTEGER */,
    unauthorised_originator_name /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_unauthorised_recipient_name /* IMPORTED_LONG_NAMED_INTEGER */,
    unauthorised_recipient_name /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_unauthorised_security_label_update /* IMPORTED_LONG_NAMED_INTEGER */,
    unauthorised_security_label_update /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_unauthorised_user_name /* IMPORTED_LONG_NAMED_INTEGER */,
    unauthorised_user_name /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_unknown_security_label /* IMPORTED_LONG_NAMED_INTEGER */,
    unknown_security_label /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_unsupported_algorithm_identifier /* IMPORTED_LONG_NAMED_INTEGER */,
    unsupported_algorithm_identifier /* IMPORTED_SHORT_NAMED_INTEGER */,
    SecurityProblem_unsupported_security_policy /* IMPORTED_LONG_NAMED_INTEGER */,
    unsupported_security_policy /* IMPORTED_SHORT_NAMED_INTEGER */,
    _decode_SecurityProblem,
    _encode_SecurityProblem,
} from '../MTSAbstractService/SecurityProblem.ta.js';
import { err_security_error } from '../MTSAccessProtocol/err-security-error.va.js';
export { err_security_error } from '../MTSAccessProtocol/err-security-error.va.js';
import { ABSTRACT_ERROR } from '../MTSAbstractService/ABSTRACT-ERROR.oca.js';
export { ABSTRACT_ERROR } from '../MTSAbstractService/ABSTRACT-ERROR.oca.js';

/* START_OF_SYMBOL_DEFINITION security_error */
/**
 * @summary security_error
 * @description
 *
 * ### ASN.1 Definition:
 *
 * ```asn1
 * security-error ABSTRACT-ERROR ::= {
 *   PARAMETER  SecurityProblem
 *   CODE       err-security-error
 * }
 * ```
 *
 * @constant
 * @type {ABSTRACT_ERROR<SecurityProblem>}
 * @implements {ABSTRACT_ERROR<SecurityProblem>}
 */
export const security_error: ABSTRACT_ERROR<SecurityProblem> = {
    class: 'ERROR',
    decoderFor: {
        '&ParameterType': _decode_SecurityProblem,
    },
    encoderFor: {
        '&ParameterType': _encode_SecurityProblem,
    },
    '&errorCode': err_security_error /* OBJECT_FIELD_SETTING */ /* UNIQUE_OBJECT_FIELD_SETTING */,
    '&ParameterType': 0 as never /* OBJECT_FIELD_SETTING OBJECT_TYPE_FIELD_SETTING */,
    '&ErrorPriority': 0 as never /* OBJECT_FIELD_SETTING OBJECT_VALUE_SET_FIELD_SETTING */,
};
/* END_OF_SYMBOL_DEFINITION security_error */

/* eslint-enable */
