/* eslint-disable */
import {
    PrintableString,
    ASN1Element as _Element,
    ASN1TagClass as _TagClass,
    ASN1Construction as _Construction,
    ASN1UniversalType as _UniversalType,
    ObjectIdentifier as _OID,
    External as _External,
    EmbeddedPDV as _PDV,
    ASN1ConstructionError as _ConstructionError,
} from '@wildboar/asn1';
import * as $ from '@wildboar/asn1/functional';

/**
 * @summary SupplementaryInformation
 * @description
 *
 * This argument may contain information supplied by the originator of the report, as a
 * printable string. It may be generated by the originating-MTA of the report or an
 * associated access-unit. See ITU-T X.411 (1999), §8.3.1.2.1.7.
 *
 * ### ASN.1 Definition:
 *
 * ```asn1
 * SupplementaryInformation  ::=
 *   PrintableString(SIZE (1..ub-supplementary-info-length))
 * ```
 */
export type SupplementaryInformation = PrintableString; // PrintableString


export const _decode_SupplementaryInformation = $._decodePrintableString;


export const _encode_SupplementaryInformation = $._encodePrintableString;


/* eslint-enable */
