/* eslint-disable */
import {
    UTCTime,
    ASN1Element as _Element,
    ASN1TagClass as _TagClass,
    ASN1Construction as _Construction,
    ASN1UniversalType as _UniversalType,
    ObjectIdentifier as _OID,
    External as _External,
    EmbeddedPDV as _PDV,
    ASN1ConstructionError as _ConstructionError,
} from '@wildboar/asn1';
import * as $ from '@wildboar/asn1/functional';

/**
 * @summary Time
 * @description
 *
 * This argument specifies the Time before which the message should not be delivered to the
 * recipient(s). It may be generated by the originator of the message. See ITU-T X.411
 * (1999), §8.2.1.1.1.12.
 *
 * ### ASN.1 Definition:
 *
 * ```asn1
 * Time  ::=  UTCTime
 * ```
 */
export type Time = UTCTime; // UTCTime


export const _decode_Time = $._decodeUTCTime;


export const _encode_Time = $._encodeUTCTime;


/* eslint-enable */
