/* eslint-disable */
import {
    ASN1Element as _Element,
    ASN1SizeError,
    OCTET_STRING
} from "@wildboar/asn1";
import * as $ from "@wildboar/asn1/functional";



/**
 * @summary GPRSChargingID
 * @description
 *
 * Unique four-octet Charging ID generated by the GGSN when a PDP Context is
 * activated. Encoding is defined in 3GPP TS 29.060 (3GPP TS 29.002 V19.1.0
 * clause 17.7.1).
 *
 * ### ASN.1 Definition:
 * 
 * ```asn1
 * GPRSChargingID  ::=  OCTET STRING (SIZE (4))
 * ```
 */
export
type GPRSChargingID = OCTET_STRING; // OctetStringType

/**
 * @summary Decodes an ASN.1 element into a(n) GPRSChargingID
 * @function
 * @param el The element being decoded.
 * @returns The decoded data structure.
 */
export const _decode_GPRSChargingID = (el: _Element): GPRSChargingID => {
    const value = $._decodeOctetString(el);
    if (value.length < 4 || value.length > 4) {
        throw new ASN1SizeError("GPRSChargingID violates SIZE constraint");
    }
    return value;
};

/**
 * @summary Encodes a(n) GPRSChargingID into an ASN.1 Element.
 * @function
 * @param value The value being encoded.
 * @param elGetter A function that can be used to get new ASN.1 elements.
 * @returns {_Element} The GPRSChargingID, encoded as an ASN.1 Element.
 */
export const _encode_GPRSChargingID = $._encodeOctetString;


/* eslint-enable */
