/* eslint-disable */
import {
    INTEGER,
    ASN1Element as _Element,
    ASN1TagClass as _TagClass,
    ASN1Construction as _Construction,
    ASN1UniversalType as _UniversalType,
    ObjectIdentifier as _OID,
    External as _External,
    EmbeddedPDV as _PDV,
    ASN1ConstructionError as _ConstructionError,
} from '@wildboar/asn1';
import * as $ from '@wildboar/asn1/functional';

/**
 * @summary Label
 * @description
 *
 * `Label`. This argument associates a security-label with the message (or probe). It may
 * be generated by the originator of the message (or probe), in line with the
 * security-policy in force. See ITU-T X.411 (1999), §8.2.1.1.1.30.
 *
 * ### ASN.1 Definition:
 *
 * ```asn1
 * Label  ::=  INTEGER
 * ```
 */
export type Label = INTEGER;


export const _decode_Label = $._decodeInteger;


export const _encode_Label = $._encodeInteger;


/* eslint-enable */
