/**
 * CBEFF `BiometricType` (ISO/IEC 19785-3:2020 Clause 6.2), used as
 * `Modality.type` in ISO/IEC 29120-1:2022 Clause 6.4.2.3. Mandatory
 * when `processedLevel` is neither `comparison-score` nor
 * `comparison-result`.
 */
export {
    type BiometricType,
    BiometricType_no_value_available,
    no_value_available,
    BiometricType_multiple_biometric_types,
    multiple_biometric_types,
    BiometricType_scent,
    scent,
    BiometricType_dna,
    dna,
    BiometricType_ear,
    ear,
    BiometricType_face,
    face,
    BiometricType_finger,
    finger,
    BiometricType_foot,
    foot,
    BiometricType_hand_geometry,
    hand_geometry,
    BiometricType_vein,
    vein,
    BiometricType_iris,
    iris,
    BiometricType_retina,
    retina,
    BiometricType_voice,
    voice,
    BiometricType_gait,
    gait,
    BiometricType_keystroke,
    keystroke,
    BiometricType_lip_movement,
    lip_movement,
    BiometricType_signature_sign,
    signature_sign,
    _decode_BiometricType,
    _encode_BiometricType,
} from "@wildboar/cbeff";
