/* eslint-disable */
import {
    UTCTime,
    ASN1Element as _Element,
    ASN1TagClass as _TagClass,
    ASN1Construction as _Construction,
    ASN1UniversalType as _UniversalType,
    ObjectIdentifier as _OID,
    External as _External,
    EmbeddedPDV as _PDV,
    ASN1ConstructionError as _ConstructionError,
} from '@wildboar/asn1';
import * as $ from '@wildboar/asn1/functional';

/**
 * @summary DeferredDeliveryCancellationTime
 * @description
 *
 * This general-attribute indicates the time at which the MTS confirmed the successful
 * cancellation of the deferred-delivery of a previously submitted message (see 8.3.3). It
 * is generated by the MS. See ITU-T X.413 (1999), §11.2.22.
 *
 * ### ASN.1 Definition:
 *
 * ```asn1
 * DeferredDeliveryCancellationTime  ::=  UTCTime
 * ```
 */
export type DeferredDeliveryCancellationTime = UTCTime; // UTCTime


export const _decode_DeferredDeliveryCancellationTime = $._decodeUTCTime;


export const _encode_DeferredDeliveryCancellationTime = $._encodeUTCTime;


/* eslint-enable */
