/* eslint-disable */
import {
    OCTET_STRING,
    ASN1ConstructionError as _ConstructionError,
    ASN1Element as _Element,
    ASN1TagClass as _TagClass
} from "@wildboar/asn1";
import * as $ from "@wildboar/asn1/functional";
import { RemoteOpId, _decode_RemoteOpId, _encode_RemoteOpId } from "../RSPDefinitions/RemoteOpId.ta.mjs";
import { TransactionId, _decode_TransactionId, _encode_TransactionId } from "../RSPDefinitions/TransactionId.ta.mjs";
import { ControlRefTemplate, _decode_ControlRefTemplate, _encode_ControlRefTemplate } from "../RSPDefinitions/ControlRefTemplate.ta.mjs";


/**
 * @summary InitialiseSecureChannelRequest
 * @description
 * 
 * ES8+.InitialiseSecureChannel, the first and only clear TLV of a Bound Profile
 * Package. It opens the BPP Security Protocol session: remote operation,
 * TransactionID, key description, the SM-DP+ one-time public key (otPK.DP.KA),
 * and a signature under SK.DPpb.SIG covering those fields plus the eUICC
 * one-time public key from PrepareDownload. The eUICC rejects the command if a
 * secure-channel session is already open. Session keys S-ENC and S-MAC and the
 * initial MAC chaining value are derived from the two one-time keys. SGP.22
 * v3.1 §5.5.1 and §2.6.4.
 * 
 * ### ASN.1 Definition:
 * 
 * ```asn1
 * InitialiseSecureChannelRequest ::= [35] SEQUENCE { -- Tag 'BF23'
 *     remoteOpId RemoteOpId, -- Remote Operation Type Identifier (value SHALL be set to installBoundProfilePackage)
 *     transactionId [0] TransactionId, -- The TransactionID generated by the SM-DP+
 *     controlRefTemplate[6] IMPLICIT ControlRefTemplate, -- Control Reference Template (Key Agreement). Current specification considers a subset of CRT specified in GlobalPlatform Card Specification [8] section 6.4.2.3 for the Mutual Authentication Data Field
 *     smdpOtpk [APPLICATION 73] OCTET STRING, -- otPK.DP.ECKA as specified in GlobalPlatform Card Specification [8] section 6.4.2.3 for ePK.OCE.ECKA, tag '5F49'
 *     smdpSign [APPLICATION 55] OCTET STRING -- SM-DP's signature, tag '5F37'
 * }
 * ```
 * 
 * @class
 */
export
class InitialiseSecureChannelRequest {
    constructor (
        /**
         * @summary `remoteOpId`.
         * @description
         * 
         * Must be `installBoundProfilePackage`. That value also fixes the key
         * usage to MAC and encryption. SGP.22 v3.1 §5.5.1.
         * 
         * @public
         * @readonly
         */
        readonly remoteOpId: RemoteOpId,
        /**
         * @summary `transactionId`.
         * @description
         * 
         * Must match the ongoing RSP session from ES10b.PrepareDownload.
         * Otherwise `invalidTransactionId`. SGP.22 v3.1 §5.5.1.
         * 
         * @public
         * @readonly
         */
        readonly transactionId: TransactionId,
        /**
         * @summary `controlRefTemplate`.
         * @description
         * 
         * Key type, key length, and host id for the key agreement. Checked
         * against the selected algorithm. SGP.22 v3.1 §5.5.1.
         * 
         * @public
         * @readonly
         */
        readonly controlRefTemplate: ControlRefTemplate,
        /**
         * @summary `smdpOtpk`.
         * @description
         * 
         * otPK.DP.KA, tag `'5F49'`. The eUICC combines it with otSK.EUICC.KA to
         * derive S-ENC, S-MAC, and the initial MAC chaining value. SGP.22 v3.1
         * §2.6.4 and §5.5.1.
         * 
         * @public
         * @readonly
         */
        readonly smdpOtpk: OCTET_STRING,
        /**
         * @summary `smdpSign`.
         * @description
         * 
         * Signature under SK.DPpb.SIG over `remoteOpId`, `transactionId`,
         * `controlRefTemplate`, `smdpOtpk`, and the `euiccOtpk` from
         * PrepareDownload. Tag `'5F37'`. Failure is `invalidSignature`, the
         * session context is discarded, and installation stops. SGP.22 v3.1
         * §5.5.1.
         * 
         * @public
         * @readonly
         */
        readonly smdpSign: OCTET_STRING
    ) {}

    /**
     * @summary Restructures an object into a InitialiseSecureChannelRequest
     * @description
     * 
     * This takes an `object` and converts it to a `InitialiseSecureChannelRequest`.
     * 
     * @public
     * @static
     * @method
     * @param {Object} _o An object having all of the keys and values of a `InitialiseSecureChannelRequest`.
     * @returns {InitialiseSecureChannelRequest}
     */
    public static _from_object (_o: { [_K in keyof (InitialiseSecureChannelRequest)]: (InitialiseSecureChannelRequest)[_K] }): InitialiseSecureChannelRequest {
        return new InitialiseSecureChannelRequest(_o.remoteOpId, _o.transactionId, _o.controlRefTemplate, _o.smdpOtpk, _o.smdpSign);
    }


}

/**
 * @summary The Leading Root Component Types of InitialiseSecureChannelRequest
 * @description
 * 
 * This is an array of `ComponentSpec`s that define how to decode the leading root component type list of a SET or SEQUENCE.
 * 
 * @constant
 */
export
const _root_component_type_list_1_spec_for_InitialiseSecureChannelRequest: $.ComponentSpec[] = [
    new $.ComponentSpec("remoteOpId", false, $.hasTag(_TagClass.context, 2)),
    new $.ComponentSpec("transactionId", false, $.hasTag(_TagClass.context, 0)),
    new $.ComponentSpec("controlRefTemplate", false, $.hasTag(_TagClass.context, 6)),
    new $.ComponentSpec("smdpOtpk", false, $.hasTag(_TagClass.application, 73)),
    new $.ComponentSpec("smdpSign", false, $.hasTag(_TagClass.application, 55))
];

/**
 * @summary The Trailing Root Component Types of InitialiseSecureChannelRequest
 * @description
 * 
 * This is an array of `ComponentSpec`s that define how to decode the trailing root component type list of a SET or SEQUENCE.
 * 
 * @constant
 */
export
const _root_component_type_list_2_spec_for_InitialiseSecureChannelRequest: $.ComponentSpec[] = [
    
];

/**
 * @summary The Extension Addition Component Types of InitialiseSecureChannelRequest
 * @description
 * 
 * This is an array of `ComponentSpec`s that define how to decode the extension addition component type list of a SET or SEQUENCE.
 * 
 * @constant
 */
export
const _extension_additions_list_spec_for_InitialiseSecureChannelRequest: $.ComponentSpec[] = [
    
];

let _cached_decoder_for_InitialiseSecureChannelRequest: $.ASN1Decoder<InitialiseSecureChannelRequest> | null = null;

/**
 * @summary Decodes an ASN.1 element into a(n) InitialiseSecureChannelRequest
 * @function
 * @param el The element being decoded.
 * @returns The decoded data structure.
 */
export
function _decode_InitialiseSecureChannelRequest (el: _Element): InitialiseSecureChannelRequest {
    if (!_cached_decoder_for_InitialiseSecureChannelRequest) { _cached_decoder_for_InitialiseSecureChannelRequest = $._decode_implicit<InitialiseSecureChannelRequest>(() => function (el: _Element): InitialiseSecureChannelRequest {
    const sequence: _Element[] = el.sequence;
    if (sequence.length < 5) {
        throw new _ConstructionError("InitialiseSecureChannelRequest contained only " + sequence.length.toString() + " elements.");
    }
    sequence[0].name = "remoteOpId";
    sequence[1].name = "transactionId";
    sequence[2].name = "controlRefTemplate";
    sequence[3].name = "smdpOtpk";
    sequence[4].name = "smdpSign";
    let remoteOpId!: RemoteOpId;
    let transactionId!: TransactionId;
    let controlRefTemplate!: ControlRefTemplate;
    let smdpOtpk!: OCTET_STRING;
    let smdpSign!: OCTET_STRING;
    remoteOpId = _decode_RemoteOpId(sequence[0]);
    transactionId = $._decode_implicit<TransactionId>(() => _decode_TransactionId)(sequence[1]);
    controlRefTemplate = $._decode_implicit<ControlRefTemplate>(() => _decode_ControlRefTemplate)(sequence[2]);
    smdpOtpk = $._decode_implicit<OCTET_STRING>(() => $._decodeOctetString)(sequence[3]);
    smdpSign = $._decode_implicit<OCTET_STRING>(() => $._decodeOctetString)(sequence[4]);
    return new InitialiseSecureChannelRequest(
        remoteOpId,
        transactionId,
        controlRefTemplate,
        smdpOtpk,
        smdpSign,

    );
}); }
    return _cached_decoder_for_InitialiseSecureChannelRequest(el);
}

let _cached_encoder_for_InitialiseSecureChannelRequest: $.ASN1Encoder<InitialiseSecureChannelRequest> | null = null;

/**
 * @summary Encodes a(n) InitialiseSecureChannelRequest into an ASN.1 Element.
 * @function
 * @param value The value being encoded.
 * @param elGetter A function that can be used to get new ASN.1 elements.
 * @returns {_Element} The InitialiseSecureChannelRequest, encoded as an ASN.1 Element.
 */
export
function _encode_InitialiseSecureChannelRequest (value: InitialiseSecureChannelRequest, elGetter: $.ASN1Encoder<any>): _Element {
    if (!_cached_encoder_for_InitialiseSecureChannelRequest) { _cached_encoder_for_InitialiseSecureChannelRequest = $._encode_implicit(_TagClass.context, 35, () => function (value: InitialiseSecureChannelRequest): _Element {
    return $._encodeSequence(([] as (_Element | undefined)[]).concat(
        [
            /* REQUIRED   */ _encode_RemoteOpId(value.remoteOpId, $.BER),
            /* REQUIRED   */ $._encode_implicit(_TagClass.context, 0, () => _encode_TransactionId, $.BER)(value.transactionId, $.BER),
            /* REQUIRED   */ $._encode_implicit(_TagClass.context, 6, () => _encode_ControlRefTemplate, $.BER)(value.controlRefTemplate, $.BER),
            /* REQUIRED   */ $._encode_implicit(_TagClass.application, 73, () => $._encodeOctetString, $.BER)(value.smdpOtpk, $.BER),
            /* REQUIRED   */ $._encode_implicit(_TagClass.application, 55, () => $._encodeOctetString, $.BER)(value.smdpSign, $.BER)
        ],
    ).filter((c: (_Element | undefined)): c is _Element => (!!c)), $.BER);
}, $.BER); }
    return _cached_encoder_for_InitialiseSecureChannelRequest(value, elGetter);
}


/* eslint-enable */
