/* eslint-disable */
import {
    itu_t,
    itu_r,
    ccitt,
    iso,
    joint_iso_itu_t,
    joint_iso_ccitt,
    OPTIONAL,
    BOOLEAN,
    INTEGER,
    BIT_STRING,
    OCTET_STRING,
    NULL,
    OBJECT_IDENTIFIER,
    ObjectDescriptor,
    EXTERNAL,
    REAL,
    INSTANCE_OF,
    ENUMERATED,
    EMBEDDED_PDV,
    UTF8String,
    RELATIVE_OID,
    SEQUENCE,
    SEQUENCE_OF,
    SET,
    SET_OF,
    GraphicString,
    NumericString,
    VisibleString,
    PrintableString,
    ISO646String,
    TeletexString,
    GeneralString,
    T61String,
    UniversalString,
    VideotexString,
    BMPString,
    IA5String,
    CharacterString,
    UTCTime,
    GeneralizedTime,
    TIME,
    DATE,
    TIME_OF_DAY,
    DATE_TIME,
    DURATION,
    OID_IRI,
    RELATIVE_OID_IRI,
    TRUE,
    FALSE,
    TRUE_BIT,
    FALSE_BIT,
    PLUS_INFINITY,
    MINUS_INFINITY,
    NOT_A_NUMBER,
    TYPE_IDENTIFIER,
    ABSTRACT_SYNTAX,
    ASN1Element as _Element,
    ASN1TagClass as _TagClass,
    ASN1Construction as _Construction,
    ASN1UniversalType as _UniversalType,
    ObjectIdentifier as _OID,
    External as _External,
    EmbeddedPDV as _PDV,
    ASN1ConstructionError as _ConstructionError,
} from "@wildboar/asn1";
import * as $ from "@wildboar/asn1/functional";
import { TransactionId, _decode_TransactionId, _encode_TransactionId } from "../RSPDefinitions/TransactionId.ta.mjs";
// export { TransactionId, _decode_TransactionId, _encode_TransactionId } from "../RSPDefinitions/TransactionId.ta.mjs";
import { NotificationMetadata, _decode_NotificationMetadata, _encode_NotificationMetadata } from "../RSPDefinitions/NotificationMetadata.ta.mjs";
// export { NotificationMetadata, _decode_NotificationMetadata, _encode_NotificationMetadata } from "../RSPDefinitions/NotificationMetadata.ta.mjs";
import { ProfileInstallationResultData_finalResult, _decode_ProfileInstallationResultData_finalResult, _encode_ProfileInstallationResultData_finalResult } from "../RSPDefinitions/ProfileInstallationResultData-finalResult.ta.mjs";
// export { ProfileInstallationResultData_finalResult, _decode_ProfileInstallationResultData_finalResult, _encode_ProfileInstallationResultData_finalResult } from "../RSPDefinitions/ProfileInstallationResultData-finalResult.ta.mjs";


/**
 * @summary ProfileInstallationResultData
 * @description
 * 
 * ### ASN.1 Definition:
 * 
 * ```asn1
 * ProfileInstallationResultData ::= [39] SEQUENCE { -- Tag 'BF27'
 *     transactionId[0] TransactionId, -- The TransactionID generated by the SM-DP+
 *     notificationMetadata[47] NotificationMetadata,
 *     smdpOid OBJECT IDENTIFIER, -- SM-DP+ OID (same value as in CERT.DPpb.ECDSA)
 *     finalResult [2] CHOICE {
 *         successResult SuccessResult,
 *         errorResult ErrorResult
 *     }
 * }
 * ```
 * 
 * @class
 */
export
class ProfileInstallationResultData {
    constructor (
        /**
         * @summary `transactionId`.
         * @public
         * @readonly
         */
        readonly transactionId: TransactionId,
        /**
         * @summary `notificationMetadata`.
         * @public
         * @readonly
         */
        readonly notificationMetadata: NotificationMetadata,
        /**
         * @summary `smdpOid`.
         * @public
         * @readonly
         */
        readonly smdpOid: OBJECT_IDENTIFIER,
        /**
         * @summary `finalResult`.
         * @public
         * @readonly
         */
        readonly finalResult: ProfileInstallationResultData_finalResult
    ) {}

    /**
     * @summary Restructures an object into a ProfileInstallationResultData
     * @description
     * 
     * This takes an `object` and converts it to a `ProfileInstallationResultData`.
     * 
     * @public
     * @static
     * @method
     * @param {Object} _o An object having all of the keys and values of a `ProfileInstallationResultData`.
     * @returns {ProfileInstallationResultData}
     */
    public static _from_object (_o: { [_K in keyof (ProfileInstallationResultData)]: (ProfileInstallationResultData)[_K] }): ProfileInstallationResultData {
        return new ProfileInstallationResultData(_o.transactionId, _o.notificationMetadata, _o.smdpOid, _o.finalResult);
    }


}

/**
 * @summary The Leading Root Component Types of ProfileInstallationResultData
 * @description
 * 
 * This is an array of `ComponentSpec`s that define how to decode the leading root component type list of a SET or SEQUENCE.
 * 
 * @constant
 */
export
const _root_component_type_list_1_spec_for_ProfileInstallationResultData: $.ComponentSpec[] = [
    new $.ComponentSpec("transactionId", false, $.hasTag(_TagClass.context, 0)),
    new $.ComponentSpec("notificationMetadata", false, $.hasTag(_TagClass.context, 47)),
    new $.ComponentSpec("smdpOid", false, $.hasTag(_TagClass.universal, 6)),
    new $.ComponentSpec("finalResult", false, $.hasTag(_TagClass.context, 2))
];

/**
 * @summary The Trailing Root Component Types of ProfileInstallationResultData
 * @description
 * 
 * This is an array of `ComponentSpec`s that define how to decode the trailing root component type list of a SET or SEQUENCE.
 * 
 * @constant
 */
export
const _root_component_type_list_2_spec_for_ProfileInstallationResultData: $.ComponentSpec[] = [
    
];

/**
 * @summary The Extension Addition Component Types of ProfileInstallationResultData
 * @description
 * 
 * This is an array of `ComponentSpec`s that define how to decode the extension addition component type list of a SET or SEQUENCE.
 * 
 * @constant
 */
export
const _extension_additions_list_spec_for_ProfileInstallationResultData: $.ComponentSpec[] = [
    
];

let _cached_decoder_for_ProfileInstallationResultData: $.ASN1Decoder<ProfileInstallationResultData> | null = null;

/**
 * @summary Decodes an ASN.1 element into a(n) ProfileInstallationResultData
 * @function
 * @param el The element being decoded.
 * @returns The decoded data structure.
 */
export
function _decode_ProfileInstallationResultData (el: _Element): ProfileInstallationResultData {
    if (!_cached_decoder_for_ProfileInstallationResultData) { _cached_decoder_for_ProfileInstallationResultData = $._decode_implicit<ProfileInstallationResultData>(() => function (el: _Element): ProfileInstallationResultData {
    const sequence: _Element[] = el.sequence;
    if (sequence.length < 4) {
        throw new _ConstructionError("ProfileInstallationResultData contained only " + sequence.length.toString() + " elements.");
    }
    sequence[0].name = "transactionId";
    sequence[1].name = "notificationMetadata";
    sequence[2].name = "smdpOid";
    sequence[3].name = "finalResult";
    let transactionId!: TransactionId;
    let notificationMetadata!: NotificationMetadata;
    let smdpOid!: OBJECT_IDENTIFIER;
    let finalResult!: ProfileInstallationResultData_finalResult;
    transactionId = $._decode_implicit<TransactionId>(() => _decode_TransactionId)(sequence[0]);
    notificationMetadata = $._decode_implicit<NotificationMetadata>(() => _decode_NotificationMetadata)(sequence[1]);
    smdpOid = $._decodeObjectIdentifier(sequence[2]);
    finalResult = $._decode_explicit<ProfileInstallationResultData_finalResult>(() => _decode_ProfileInstallationResultData_finalResult)(sequence[3]);
    return new ProfileInstallationResultData(
        transactionId,
        notificationMetadata,
        smdpOid,
        finalResult,

    );
}); }
    return _cached_decoder_for_ProfileInstallationResultData(el);
}

let _cached_encoder_for_ProfileInstallationResultData: $.ASN1Encoder<ProfileInstallationResultData> | null = null;

/**
 * @summary Encodes a(n) ProfileInstallationResultData into an ASN.1 Element.
 * @function
 * @param value The value being encoded.
 * @param elGetter A function that can be used to get new ASN.1 elements.
 * @returns {_Element} The ProfileInstallationResultData, encoded as an ASN.1 Element.
 */
export
function _encode_ProfileInstallationResultData (value: ProfileInstallationResultData, elGetter: $.ASN1Encoder<any>): _Element {
    if (!_cached_encoder_for_ProfileInstallationResultData) { _cached_encoder_for_ProfileInstallationResultData = $._encode_implicit(_TagClass.context, 39, () => function (value: ProfileInstallationResultData, elGetter: $.ASN1Encoder<ProfileInstallationResultData>): _Element {
    return $._encodeSequence(([] as (_Element | undefined)[]).concat(
        [
            /* REQUIRED   */ $._encode_implicit(_TagClass.context, 0, () => _encode_TransactionId, $.BER)(value.transactionId, $.BER),
            /* REQUIRED   */ $._encode_implicit(_TagClass.context, 47, () => _encode_NotificationMetadata, $.BER)(value.notificationMetadata, $.BER),
            /* REQUIRED   */ $._encodeObjectIdentifier(value.smdpOid, $.BER),
            /* REQUIRED   */ $._encode_explicit(_TagClass.context, 2, () => _encode_ProfileInstallationResultData_finalResult, $.BER)(value.finalResult, $.BER)
        ],
    ).filter((c: (_Element | undefined)): c is _Element => (!!c)), $.BER);
}, $.BER); }
    return _cached_encoder_for_ProfileInstallationResultData(value, elGetter);
}


/* eslint-enable */
