/* eslint-disable */
import {
    UTF8String,
    ASN1ConstructionError as _ConstructionError,
    ASN1Element as _Element,
    ASN1TagClass as _TagClass
} from "@wildboar/asn1";
import * as $ from "@wildboar/asn1/functional";
import { TransactionId, _decode_TransactionId, _encode_TransactionId } from "../RSPDefinitions/TransactionId.ta.mjs";
// export { TransactionId, _decode_TransactionId, _encode_TransactionId } from "../RSPDefinitions/TransactionId.ta.mjs";
import { Octet16, _decode_Octet16, _encode_Octet16 } from "../RSPDefinitions/Octet16.ta.mjs";
// export { Octet16, _decode_Octet16, _encode_Octet16 } from "../RSPDefinitions/Octet16.ta.mjs";


/**
 * @summary ServerSigned1
 * @description
 * 
 * ### ASN.1 Definition:
 * 
 * ```asn1
 * ServerSigned1 ::= SEQUENCE {
 *     transactionId [0] TransactionId,    -- The Transaction ID generated by the RSP Server
 *     euiccChallenge [1] Octet16,        -- The eUICC Challenge
 *     serverAddress [3] UTF8String,         -- The RSP Server address as an FQDN
 *     serverChallenge [4] Octet16        -- The RSP Server Challenge
 * }
 * ```
 * 
 * @class
 */
export
class ServerSigned1 {
    constructor (
        /**
         * @summary `transactionId`.
         * @public
         * @readonly
         */
        readonly transactionId: TransactionId,
        /**
         * @summary `euiccChallenge`.
         * @public
         * @readonly
         */
        readonly euiccChallenge: Octet16,
        /**
         * @summary `serverAddress`.
         * @public
         * @readonly
         */
        readonly serverAddress: UTF8String,
        /**
         * @summary `serverChallenge`.
         * @public
         * @readonly
         */
        readonly serverChallenge: Octet16
    ) {}

    /**
     * @summary Restructures an object into a ServerSigned1
     * @description
     * 
     * This takes an `object` and converts it to a `ServerSigned1`.
     * 
     * @public
     * @static
     * @method
     * @param {Object} _o An object having all of the keys and values of a `ServerSigned1`.
     * @returns {ServerSigned1}
     */
    public static _from_object (_o: { [_K in keyof (ServerSigned1)]: (ServerSigned1)[_K] }): ServerSigned1 {
        return new ServerSigned1(_o.transactionId, _o.euiccChallenge, _o.serverAddress, _o.serverChallenge);
    }


}

/**
 * @summary The Leading Root Component Types of ServerSigned1
 * @description
 * 
 * This is an array of `ComponentSpec`s that define how to decode the leading root component type list of a SET or SEQUENCE.
 * 
 * @constant
 */
export
const _root_component_type_list_1_spec_for_ServerSigned1: $.ComponentSpec[] = [
    new $.ComponentSpec("transactionId", false, $.hasTag(_TagClass.context, 0)),
    new $.ComponentSpec("euiccChallenge", false, $.hasTag(_TagClass.context, 1)),
    new $.ComponentSpec("serverAddress", false, $.hasTag(_TagClass.context, 3)),
    new $.ComponentSpec("serverChallenge", false, $.hasTag(_TagClass.context, 4))
];

/**
 * @summary The Trailing Root Component Types of ServerSigned1
 * @description
 * 
 * This is an array of `ComponentSpec`s that define how to decode the trailing root component type list of a SET or SEQUENCE.
 * 
 * @constant
 */
export
const _root_component_type_list_2_spec_for_ServerSigned1: $.ComponentSpec[] = [
    
];

/**
 * @summary The Extension Addition Component Types of ServerSigned1
 * @description
 * 
 * This is an array of `ComponentSpec`s that define how to decode the extension addition component type list of a SET or SEQUENCE.
 * 
 * @constant
 */
export
const _extension_additions_list_spec_for_ServerSigned1: $.ComponentSpec[] = [
    
];

let _cached_decoder_for_ServerSigned1: $.ASN1Decoder<ServerSigned1> | null = null;

/**
 * @summary Decodes an ASN.1 element into a(n) ServerSigned1
 * @function
 * @param el The element being decoded.
 * @returns The decoded data structure.
 */
export
function _decode_ServerSigned1 (el: _Element): ServerSigned1 {
    if (!_cached_decoder_for_ServerSigned1) { _cached_decoder_for_ServerSigned1 = function (el: _Element): ServerSigned1 {
    const sequence: _Element[] = el.sequence;
    if (sequence.length < 4) {
        throw new _ConstructionError("ServerSigned1 contained only " + sequence.length.toString() + " elements.");
    }
    sequence[0].name = "transactionId";
    sequence[1].name = "euiccChallenge";
    sequence[2].name = "serverAddress";
    sequence[3].name = "serverChallenge";
    let transactionId!: TransactionId;
    let euiccChallenge!: Octet16;
    let serverAddress!: UTF8String;
    let serverChallenge!: Octet16;
    transactionId = $._decode_implicit<TransactionId>(() => _decode_TransactionId)(sequence[0]);
    euiccChallenge = $._decode_implicit<Octet16>(() => _decode_Octet16)(sequence[1]);
    serverAddress = $._decode_implicit<UTF8String>(() => $._decodeUTF8String)(sequence[2]);
    serverChallenge = $._decode_implicit<Octet16>(() => _decode_Octet16)(sequence[3]);
    return new ServerSigned1(
        transactionId,
        euiccChallenge,
        serverAddress,
        serverChallenge,

    );
}; }
    return _cached_decoder_for_ServerSigned1(el);
}

let _cached_encoder_for_ServerSigned1: $.ASN1Encoder<ServerSigned1> | null = null;

/**
 * @summary Encodes a(n) ServerSigned1 into an ASN.1 Element.
 * @function
 * @param value The value being encoded.
 * @param elGetter A function that can be used to get new ASN.1 elements.
 * @returns {_Element} The ServerSigned1, encoded as an ASN.1 Element.
 */
export
function _encode_ServerSigned1 (value: ServerSigned1, elGetter: $.ASN1Encoder<any>): _Element {
    if (!_cached_encoder_for_ServerSigned1) { _cached_encoder_for_ServerSigned1 = function (value: ServerSigned1, elGetter: $.ASN1Encoder<ServerSigned1>): _Element {
    return $._encodeSequence(([] as (_Element | undefined)[]).concat(
        [
            /* REQUIRED   */ $._encode_implicit(_TagClass.context, 0, () => _encode_TransactionId, $.BER)(value.transactionId, $.BER),
            /* REQUIRED   */ $._encode_implicit(_TagClass.context, 1, () => _encode_Octet16, $.BER)(value.euiccChallenge, $.BER),
            /* REQUIRED   */ $._encode_implicit(_TagClass.context, 3, () => $._encodeUTF8String, $.BER)(value.serverAddress, $.BER),
            /* REQUIRED   */ $._encode_implicit(_TagClass.context, 4, () => _encode_Octet16, $.BER)(value.serverChallenge, $.BER)
        ],
    ).filter((c: (_Element | undefined)): c is _Element => (!!c)), $.BER);
}; }
    return _cached_encoder_for_ServerSigned1(value, elGetter);
}


/* eslint-enable */
