/* eslint-disable */
import {
    BOOLEAN,
    OCTET_STRING,
    OPTIONAL,
    ASN1Element as _Element,
    ASN1TagClass as _TagClass
} from "@wildboar/asn1";
import * as $ from "@wildboar/asn1/functional";
import { TransactionId, _decode_TransactionId, _encode_TransactionId } from "../RSPDefinitions/TransactionId.ta.mjs";


/**
 * @summary SmdpSigned2
 * @description
 * 
 * Data signed by the SM-DP+ Profile Package Binding key and checked by the
 * eUICC in ES10b.PrepareDownload. `ccRequiredFlag` tells the LPA to collect a
 * Confirmation Code from the End User before continuing. `bppEuiccOtpk`, when
 * present, is an otPK.EUICC.KA already used to bind a BPP, so the eUICC can
 * reuse that key pair instead of generating a new one. SGP.22 v3.1 §5.7.5.
 * 
 * ### ASN.1 Definition:
 * 
 * ```asn1
 * SmdpSigned2 ::= SEQUENCE {
 *     transactionId [0] TransactionId,    -- The TransactionID generated by the SM DP+
 *     ccRequiredFlag BOOLEAN,    --Indicates if the Confirmation Code is required
 *     bppEuiccOtpk [APPLICATION 73] OCTET STRING OPTIONAL     -- otPK.EUICC.ECKA already used for binding the BPP, tag '5F49'
 * }
 * ```
 * 
 * @class
 */
export
class SmdpSigned2 {
    constructor (
        /**
         * @summary `transactionId`.
         * @description
         * 
         * Session id the SM-DP+ assigned. SGP.22 v3.1 §5.7.5.
         * 
         * @public
         * @readonly
         */
        readonly transactionId: TransactionId,
        /**
         * @summary `ccRequiredFlag`.
         * @description
         * 
         * True when the End User must enter the Confirmation Code before the
         * LPA calls GetBoundProfilePackage. The code is distributed out of
         * band. SGP.22 v3.1 §4.7 and §5.7.5.
         * 
         * @public
         * @readonly
         */
        readonly ccRequiredFlag: BOOLEAN,
        /**
         * @summary `bppEuiccOtpk`.
         * @description
         * 
         * otPK.EUICC.KA already used to bind a BPP for this eUICC, tag
         * `'5F49'`. Present when the SM-DP+ wants the eUICC to reuse that key
         * pair so a previously generated package can be re-signed rather than
         * rebuilt. SGP.22 v3.1 §5.6.2 and §5.7.5.
         * 
         * @public
         * @readonly
         */
        readonly bppEuiccOtpk: OPTIONAL<OCTET_STRING>
    ) {}

    /**
     * @summary Restructures an object into a SmdpSigned2
     * @description
     * 
     * This takes an `object` and converts it to a `SmdpSigned2`.
     * 
     * @public
     * @static
     * @method
     * @param {Object} _o An object having all of the keys and values of a `SmdpSigned2`.
     * @returns {SmdpSigned2}
     */
    public static _from_object (_o: { [_K in keyof (SmdpSigned2)]: (SmdpSigned2)[_K] }): SmdpSigned2 {
        return new SmdpSigned2(_o.transactionId, _o.ccRequiredFlag, _o.bppEuiccOtpk);
    }


}

/**
 * @summary The Leading Root Component Types of SmdpSigned2
 * @description
 * 
 * This is an array of `ComponentSpec`s that define how to decode the leading root component type list of a SET or SEQUENCE.
 * 
 * @constant
 */
export
const _root_component_type_list_1_spec_for_SmdpSigned2: $.ComponentSpec[] = [
    new $.ComponentSpec("transactionId", false, $.hasTag(_TagClass.context, 0)),
    new $.ComponentSpec("ccRequiredFlag", false, $.hasTag(_TagClass.universal, 1)),
    new $.ComponentSpec("bppEuiccOtpk", true, $.hasTag(_TagClass.application, 73))
];

/**
 * @summary The Trailing Root Component Types of SmdpSigned2
 * @description
 * 
 * This is an array of `ComponentSpec`s that define how to decode the trailing root component type list of a SET or SEQUENCE.
 * 
 * @constant
 */
export
const _root_component_type_list_2_spec_for_SmdpSigned2: $.ComponentSpec[] = [
    
];

/**
 * @summary The Extension Addition Component Types of SmdpSigned2
 * @description
 * 
 * This is an array of `ComponentSpec`s that define how to decode the extension addition component type list of a SET or SEQUENCE.
 * 
 * @constant
 */
export
const _extension_additions_list_spec_for_SmdpSigned2: $.ComponentSpec[] = [
    
];

let _cached_decoder_for_SmdpSigned2: $.ASN1Decoder<SmdpSigned2> | null = null;

/**
 * @summary Decodes an ASN.1 element into a(n) SmdpSigned2
 * @function
 * @param el The element being decoded.
 * @returns The decoded data structure.
 */
export
function _decode_SmdpSigned2 (el: _Element): SmdpSigned2 {
    if (!_cached_decoder_for_SmdpSigned2) { _cached_decoder_for_SmdpSigned2 = function (el: _Element): SmdpSigned2 {
    let transactionId!: TransactionId;
    let ccRequiredFlag!: BOOLEAN;
    let bppEuiccOtpk: OPTIONAL<OCTET_STRING>;
    const callbacks: $.DecodingMap = {
        "transactionId": (_el: _Element): void => { transactionId = $._decode_implicit<TransactionId>(() => _decode_TransactionId)(_el); },
        "ccRequiredFlag": (_el: _Element): void => { ccRequiredFlag = $._decodeBoolean(_el); },
        "bppEuiccOtpk": (_el: _Element): void => { bppEuiccOtpk = $._decode_implicit<OCTET_STRING>(() => $._decodeOctetString)(_el); }
    };
    $._parse_sequence(el, callbacks,
        _root_component_type_list_1_spec_for_SmdpSigned2,
        _extension_additions_list_spec_for_SmdpSigned2,
        _root_component_type_list_2_spec_for_SmdpSigned2,
        undefined,
    );
    return new SmdpSigned2(
        transactionId,
        ccRequiredFlag,
        bppEuiccOtpk
    );
}; }
    return _cached_decoder_for_SmdpSigned2(el);
}

let _cached_encoder_for_SmdpSigned2: $.ASN1Encoder<SmdpSigned2> | null = null;

/**
 * @summary Encodes a(n) SmdpSigned2 into an ASN.1 Element.
 * @function
 * @param value The value being encoded.
 * @param elGetter A function that can be used to get new ASN.1 elements.
 * @returns {_Element} The SmdpSigned2, encoded as an ASN.1 Element.
 */
export
function _encode_SmdpSigned2 (value: SmdpSigned2, elGetter: $.ASN1Encoder<any>): _Element {
    if (!_cached_encoder_for_SmdpSigned2) { _cached_encoder_for_SmdpSigned2 = function (value: SmdpSigned2): _Element {
    return $._encodeSequence(([] as (_Element | undefined)[]).concat(
        [
            /* REQUIRED   */ $._encode_implicit(_TagClass.context, 0, () => _encode_TransactionId, $.BER)(value.transactionId, $.BER),
            /* REQUIRED   */ $._encodeBoolean(value.ccRequiredFlag, $.BER),
            /* IF_ABSENT  */ ((value.bppEuiccOtpk === undefined) ? undefined : $._encode_implicit(_TagClass.application, 73, () => $._encodeOctetString, $.BER)(value.bppEuiccOtpk, $.BER))
        ],
    ).filter((c: (_Element | undefined)): c is _Element => (!!c)), $.BER);
}; }
    return _cached_encoder_for_SmdpSigned2(value, elGetter);
}


/* eslint-enable */
