/* eslint-disable */
import {
    UTCTime,
    ASN1Element as _Element,
    ASN1TagClass as _TagClass,
    ASN1Construction as _Construction,
    ASN1UniversalType as _UniversalType,
    ObjectIdentifier as _OID,
    External as _External,
    EmbeddedPDV as _PDV,
    ASN1ConstructionError as _ConstructionError,
} from '@wildboar/asn1';
import * as $ from '@wildboar/asn1/functional';

/**
 * @summary CreationTime
 * @description
 *
 * This general-attribute indicates the time at which an entry was created in the MS. It is
 * generated by the MS. See ITU-T X.413 (1999), §11.2.21.
 *
 * ### ASN.1 Definition:
 *
 * ```asn1
 * CreationTime  ::=  UTCTime
 * ```
 */
export type CreationTime = UTCTime; // UTCTime


export const _decode_CreationTime = $._decodeUTCTime;


export const _encode_CreationTime = $._encodeUTCTime;


/* eslint-enable */
