/* eslint-disable */
import {
    itu_t,
    itu_r,
    ccitt,
    iso,
    joint_iso_itu_t,
    joint_iso_ccitt,
    OPTIONAL,
    BOOLEAN,
    INTEGER,
    BIT_STRING,
    OCTET_STRING,
    NULL,
    OBJECT_IDENTIFIER,
    ObjectDescriptor,
    EXTERNAL,
    REAL,
    INSTANCE_OF,
    ENUMERATED,
    EMBEDDED_PDV,
    UTF8String,
    RELATIVE_OID,
    SEQUENCE,
    SEQUENCE_OF,
    SET,
    SET_OF,
    GraphicString,
    NumericString,
    VisibleString,
    PrintableString,
    ISO646String,
    TeletexString,
    GeneralString,
    T61String,
    UniversalString,
    VideotexString,
    BMPString,
    IA5String,
    CharacterString,
    UTCTime,
    GeneralizedTime,
    TIME,
    DATE,
    TIME_OF_DAY,
    DATE_TIME,
    DURATION,
    OID_IRI,
    RELATIVE_OID_IRI,
    TRUE,
    FALSE,
    TRUE_BIT,
    FALSE_BIT,
    PLUS_INFINITY,
    MINUS_INFINITY,
    NOT_A_NUMBER,
    TYPE_IDENTIFIER,
    ABSTRACT_SYNTAX,
    ASN1Element as _Element,
    ASN1TagClass as _TagClass,
    ASN1Construction as _Construction,
    ASN1UniversalType as _UniversalType,
    ObjectIdentifier as _OID,
    External as _External,
    EmbeddedPDV as _PDV,
    ASN1ConstructionError as _ConstructionError,
} from "@wildboar/asn1";
import * as $ from "@wildboar/asn1/functional";
import { TransactionId, _decode_TransactionId, _encode_TransactionId } from "../RSPDefinitions/TransactionId.ta.mjs";
// export { TransactionId, _decode_TransactionId, _encode_TransactionId } from "../RSPDefinitions/TransactionId.ta.mjs";
import { ProfileDownloadTriggerRequest, _decode_ProfileDownloadTriggerRequest, _encode_ProfileDownloadTriggerRequest } from "../SGP32Definitions/ProfileDownloadTriggerRequest.ta.mjs";
// export { ProfileDownloadTriggerRequest, _decode_ProfileDownloadTriggerRequest, _encode_ProfileDownloadTriggerRequest } from "../SGP32Definitions/ProfileDownloadTriggerRequest.ta.mjs";


/**
 * @summary AuthenticateClientOkDSEsipa
 * @description
 * 
 * ### ASN.1 Definition:
 * 
 * ```asn1
 * AuthenticateClientOkDSEsipa ::= SEQUENCE {
 *     transactionId [0] TransactionId, -- The TransactionID generated by the SM-DS
 *     profileDownloadTrigger [84] ProfileDownloadTriggerRequest OPTIONAL -- Tag 'BF54'
 * }
 * ```
 * 
 * @class
 */
export
class AuthenticateClientOkDSEsipa {
    constructor (
        /**
         * @summary `transactionId`.
         * @public
         * @readonly
         */
        readonly transactionId: TransactionId,
        /**
         * @summary `profileDownloadTrigger`.
         * @public
         * @readonly
         */
        readonly profileDownloadTrigger: OPTIONAL<ProfileDownloadTriggerRequest>
    ) {}

    /**
     * @summary Restructures an object into a AuthenticateClientOkDSEsipa
     * @description
     * 
     * This takes an `object` and converts it to a `AuthenticateClientOkDSEsipa`.
     * 
     * @public
     * @static
     * @method
     * @param {Object} _o An object having all of the keys and values of a `AuthenticateClientOkDSEsipa`.
     * @returns {AuthenticateClientOkDSEsipa}
     */
    public static _from_object (_o: { [_K in keyof (AuthenticateClientOkDSEsipa)]: (AuthenticateClientOkDSEsipa)[_K] }): AuthenticateClientOkDSEsipa {
        return new AuthenticateClientOkDSEsipa(_o.transactionId, _o.profileDownloadTrigger);
    }


}

/**
 * @summary The Leading Root Component Types of AuthenticateClientOkDSEsipa
 * @description
 * 
 * This is an array of `ComponentSpec`s that define how to decode the leading root component type list of a SET or SEQUENCE.
 * 
 * @constant
 */
export
const _root_component_type_list_1_spec_for_AuthenticateClientOkDSEsipa: $.ComponentSpec[] = [
    new $.ComponentSpec("transactionId", false, $.hasTag(_TagClass.context, 0)),
    new $.ComponentSpec("profileDownloadTrigger", true, $.hasTag(_TagClass.context, 84))
];

/**
 * @summary The Trailing Root Component Types of AuthenticateClientOkDSEsipa
 * @description
 * 
 * This is an array of `ComponentSpec`s that define how to decode the trailing root component type list of a SET or SEQUENCE.
 * 
 * @constant
 */
export
const _root_component_type_list_2_spec_for_AuthenticateClientOkDSEsipa: $.ComponentSpec[] = [
    
];

/**
 * @summary The Extension Addition Component Types of AuthenticateClientOkDSEsipa
 * @description
 * 
 * This is an array of `ComponentSpec`s that define how to decode the extension addition component type list of a SET or SEQUENCE.
 * 
 * @constant
 */
export
const _extension_additions_list_spec_for_AuthenticateClientOkDSEsipa: $.ComponentSpec[] = [
    
];

let _cached_decoder_for_AuthenticateClientOkDSEsipa: $.ASN1Decoder<AuthenticateClientOkDSEsipa> | null = null;

/**
 * @summary Decodes an ASN.1 element into a(n) AuthenticateClientOkDSEsipa
 * @function
 * @param el The element being decoded.
 * @returns The decoded data structure.
 */
export
function _decode_AuthenticateClientOkDSEsipa (el: _Element): AuthenticateClientOkDSEsipa {
    if (!_cached_decoder_for_AuthenticateClientOkDSEsipa) { _cached_decoder_for_AuthenticateClientOkDSEsipa = function (el: _Element): AuthenticateClientOkDSEsipa {
    let transactionId!: TransactionId;
    let profileDownloadTrigger: OPTIONAL<ProfileDownloadTriggerRequest>;
    const callbacks: $.DecodingMap = {
        "transactionId": (_el: _Element): void => { transactionId = $._decode_implicit<TransactionId>(() => _decode_TransactionId)(_el); },
        "profileDownloadTrigger": (_el: _Element): void => { profileDownloadTrigger = $._decode_implicit<ProfileDownloadTriggerRequest>(() => _decode_ProfileDownloadTriggerRequest)(_el); }
    };
    $._parse_sequence(el, callbacks,
        _root_component_type_list_1_spec_for_AuthenticateClientOkDSEsipa,
        _extension_additions_list_spec_for_AuthenticateClientOkDSEsipa,
        _root_component_type_list_2_spec_for_AuthenticateClientOkDSEsipa,
        undefined,
    );
    return new AuthenticateClientOkDSEsipa(
        transactionId,
        profileDownloadTrigger
    );
}; }
    return _cached_decoder_for_AuthenticateClientOkDSEsipa(el);
}

let _cached_encoder_for_AuthenticateClientOkDSEsipa: $.ASN1Encoder<AuthenticateClientOkDSEsipa> | null = null;

/**
 * @summary Encodes a(n) AuthenticateClientOkDSEsipa into an ASN.1 Element.
 * @function
 * @param value The value being encoded.
 * @param elGetter A function that can be used to get new ASN.1 elements.
 * @returns {_Element} The AuthenticateClientOkDSEsipa, encoded as an ASN.1 Element.
 */
export
function _encode_AuthenticateClientOkDSEsipa (value: AuthenticateClientOkDSEsipa, elGetter: $.ASN1Encoder<any>): _Element {
    if (!_cached_encoder_for_AuthenticateClientOkDSEsipa) { _cached_encoder_for_AuthenticateClientOkDSEsipa = function (value: AuthenticateClientOkDSEsipa, elGetter: $.ASN1Encoder<AuthenticateClientOkDSEsipa>): _Element {
    return $._encodeSequence(([] as (_Element | undefined)[]).concat(
        [
            /* REQUIRED   */ $._encode_implicit(_TagClass.context, 0, () => _encode_TransactionId, $.BER)(value.transactionId, $.BER),
            /* IF_ABSENT  */ ((value.profileDownloadTrigger === undefined) ? undefined : $._encode_implicit(_TagClass.context, 84, () => _encode_ProfileDownloadTriggerRequest, $.BER)(value.profileDownloadTrigger, $.BER))
        ],
    ).filter((c: (_Element | undefined)): c is _Element => (!!c)), $.BER);
}; }
    return _cached_encoder_for_AuthenticateClientOkDSEsipa(value, elGetter);
}


/* eslint-enable */
