/* eslint-disable */
import {
    itu_t,
    itu_r,
    ccitt,
    iso,
    joint_iso_itu_t,
    joint_iso_ccitt,
    OPTIONAL,
    BOOLEAN,
    INTEGER,
    BIT_STRING,
    OCTET_STRING,
    NULL,
    OBJECT_IDENTIFIER,
    ObjectDescriptor,
    EXTERNAL,
    REAL,
    INSTANCE_OF,
    ENUMERATED,
    EMBEDDED_PDV,
    UTF8String,
    RELATIVE_OID,
    SEQUENCE,
    SEQUENCE_OF,
    SET,
    SET_OF,
    GraphicString,
    NumericString,
    VisibleString,
    PrintableString,
    ISO646String,
    TeletexString,
    GeneralString,
    T61String,
    UniversalString,
    VideotexString,
    BMPString,
    IA5String,
    CharacterString,
    UTCTime,
    GeneralizedTime,
    TIME,
    DATE,
    TIME_OF_DAY,
    DATE_TIME,
    DURATION,
    OID_IRI,
    RELATIVE_OID_IRI,
    TRUE,
    FALSE,
    TRUE_BIT,
    FALSE_BIT,
    PLUS_INFINITY,
    MINUS_INFINITY,
    NOT_A_NUMBER,
    TYPE_IDENTIFIER,
    ABSTRACT_SYNTAX,
    ASN1Element as _Element,
    ASN1TagClass as _TagClass,
    ASN1Construction as _Construction,
    ASN1UniversalType as _UniversalType,
    ObjectIdentifier as _OID,
    External as _External,
    EmbeddedPDV as _PDV,
    ASN1ConstructionError as _ConstructionError,
} from "@wildboar/asn1";
import * as $ from "@wildboar/asn1/functional";
import { TransactionId, _decode_TransactionId, _encode_TransactionId } from "../RSPDefinitions/TransactionId.ta.mjs";
// export { TransactionId, _decode_TransactionId, _encode_TransactionId } from "../RSPDefinitions/TransactionId.ta.mjs";
import { AuthenticateServerResponse, _decode_AuthenticateServerResponse, _encode_AuthenticateServerResponse } from "../SGP32Definitions/AuthenticateServerResponse.ta.mjs";
// export { AuthenticateServerResponse, _decode_AuthenticateServerResponse, _encode_AuthenticateServerResponse } from "../SGP32Definitions/AuthenticateServerResponse.ta.mjs";


/**
 * @summary AuthenticateClientRequestEsipa
 * @description
 * 
 * ### ASN.1 Definition:
 * 
 * ```asn1
 * AuthenticateClientRequestEsipa ::= [59] SEQUENCE { -- Tag 'BF3B'
 *     transactionId [0] TransactionId, -- The TransactionID generated by the SM-DP+/SM-DS
 *     authenticateServerResponse [56] AuthenticateServerResponse -- This is the response from ES10b.AuthenticateServer, possibly in compact format
 * }
 * ```
 * 
 * @class
 */
export
class AuthenticateClientRequestEsipa {
    constructor (
        /**
         * @summary `transactionId`.
         * @public
         * @readonly
         */
        readonly transactionId: TransactionId,
        /**
         * @summary `authenticateServerResponse`.
         * @public
         * @readonly
         */
        readonly authenticateServerResponse: AuthenticateServerResponse
    ) {}

    /**
     * @summary Restructures an object into a AuthenticateClientRequestEsipa
     * @description
     * 
     * This takes an `object` and converts it to a `AuthenticateClientRequestEsipa`.
     * 
     * @public
     * @static
     * @method
     * @param {Object} _o An object having all of the keys and values of a `AuthenticateClientRequestEsipa`.
     * @returns {AuthenticateClientRequestEsipa}
     */
    public static _from_object (_o: { [_K in keyof (AuthenticateClientRequestEsipa)]: (AuthenticateClientRequestEsipa)[_K] }): AuthenticateClientRequestEsipa {
        return new AuthenticateClientRequestEsipa(_o.transactionId, _o.authenticateServerResponse);
    }


}

/**
 * @summary The Leading Root Component Types of AuthenticateClientRequestEsipa
 * @description
 * 
 * This is an array of `ComponentSpec`s that define how to decode the leading root component type list of a SET or SEQUENCE.
 * 
 * @constant
 */
export
const _root_component_type_list_1_spec_for_AuthenticateClientRequestEsipa: $.ComponentSpec[] = [
    new $.ComponentSpec("transactionId", false, $.hasTag(_TagClass.context, 0)),
    new $.ComponentSpec("authenticateServerResponse", false, $.hasTag(_TagClass.context, 56))
];

/**
 * @summary The Trailing Root Component Types of AuthenticateClientRequestEsipa
 * @description
 * 
 * This is an array of `ComponentSpec`s that define how to decode the trailing root component type list of a SET or SEQUENCE.
 * 
 * @constant
 */
export
const _root_component_type_list_2_spec_for_AuthenticateClientRequestEsipa: $.ComponentSpec[] = [
    
];

/**
 * @summary The Extension Addition Component Types of AuthenticateClientRequestEsipa
 * @description
 * 
 * This is an array of `ComponentSpec`s that define how to decode the extension addition component type list of a SET or SEQUENCE.
 * 
 * @constant
 */
export
const _extension_additions_list_spec_for_AuthenticateClientRequestEsipa: $.ComponentSpec[] = [
    
];

let _cached_decoder_for_AuthenticateClientRequestEsipa: $.ASN1Decoder<AuthenticateClientRequestEsipa> | null = null;

/**
 * @summary Decodes an ASN.1 element into a(n) AuthenticateClientRequestEsipa
 * @function
 * @param el The element being decoded.
 * @returns The decoded data structure.
 */
export
function _decode_AuthenticateClientRequestEsipa (el: _Element): AuthenticateClientRequestEsipa {
    if (!_cached_decoder_for_AuthenticateClientRequestEsipa) { _cached_decoder_for_AuthenticateClientRequestEsipa = $._decode_implicit<AuthenticateClientRequestEsipa>(() => function (el: _Element): AuthenticateClientRequestEsipa {
    const sequence: _Element[] = el.sequence;
    if (sequence.length < 2) {
        throw new _ConstructionError("AuthenticateClientRequestEsipa contained only " + sequence.length.toString() + " elements.");
    }
    sequence[0].name = "transactionId";
    sequence[1].name = "authenticateServerResponse";
    let transactionId!: TransactionId;
    let authenticateServerResponse!: AuthenticateServerResponse;
    transactionId = $._decode_implicit<TransactionId>(() => _decode_TransactionId)(sequence[0]);
    authenticateServerResponse = $._decode_implicit<AuthenticateServerResponse>(() => _decode_AuthenticateServerResponse)(sequence[1]);
    return new AuthenticateClientRequestEsipa(
        transactionId,
        authenticateServerResponse,

    );
}); }
    return _cached_decoder_for_AuthenticateClientRequestEsipa(el);
}

let _cached_encoder_for_AuthenticateClientRequestEsipa: $.ASN1Encoder<AuthenticateClientRequestEsipa> | null = null;

/**
 * @summary Encodes a(n) AuthenticateClientRequestEsipa into an ASN.1 Element.
 * @function
 * @param value The value being encoded.
 * @param elGetter A function that can be used to get new ASN.1 elements.
 * @returns {_Element} The AuthenticateClientRequestEsipa, encoded as an ASN.1 Element.
 */
export
function _encode_AuthenticateClientRequestEsipa (value: AuthenticateClientRequestEsipa, elGetter: $.ASN1Encoder<any>): _Element {
    if (!_cached_encoder_for_AuthenticateClientRequestEsipa) { _cached_encoder_for_AuthenticateClientRequestEsipa = $._encode_implicit(_TagClass.context, 59, () => function (value: AuthenticateClientRequestEsipa, elGetter: $.ASN1Encoder<AuthenticateClientRequestEsipa>): _Element {
    return $._encodeSequence(([] as (_Element | undefined)[]).concat(
        [
            /* REQUIRED   */ $._encode_implicit(_TagClass.context, 0, () => _encode_TransactionId, $.BER)(value.transactionId, $.BER),
            /* REQUIRED   */ $._encode_implicit(_TagClass.context, 56, () => _encode_AuthenticateServerResponse, $.BER)(value.authenticateServerResponse, $.BER)
        ],
    ).filter((c: (_Element | undefined)): c is _Element => (!!c)), $.BER);
}, $.BER); }
    return _cached_encoder_for_AuthenticateClientRequestEsipa(value, elGetter);
}


/* eslint-enable */
