/* eslint-disable */
import {
    itu_t,
    itu_r,
    ccitt,
    iso,
    joint_iso_itu_t,
    joint_iso_ccitt,
    OPTIONAL,
    BOOLEAN,
    INTEGER,
    BIT_STRING,
    OCTET_STRING,
    NULL,
    OBJECT_IDENTIFIER,
    ObjectDescriptor,
    EXTERNAL,
    REAL,
    INSTANCE_OF,
    ENUMERATED,
    EMBEDDED_PDV,
    UTF8String,
    RELATIVE_OID,
    SEQUENCE,
    SEQUENCE_OF,
    SET,
    SET_OF,
    GraphicString,
    NumericString,
    VisibleString,
    PrintableString,
    ISO646String,
    TeletexString,
    GeneralString,
    T61String,
    UniversalString,
    VideotexString,
    BMPString,
    IA5String,
    CharacterString,
    UTCTime,
    GeneralizedTime,
    TIME,
    DATE,
    TIME_OF_DAY,
    DATE_TIME,
    DURATION,
    OID_IRI,
    RELATIVE_OID_IRI,
    TRUE,
    FALSE,
    TRUE_BIT,
    FALSE_BIT,
    PLUS_INFINITY,
    MINUS_INFINITY,
    NOT_A_NUMBER,
    TYPE_IDENTIFIER,
    ABSTRACT_SYNTAX,
    ASN1Element as _Element,
    ASN1TagClass as _TagClass,
    ASN1Construction as _Construction,
    ASN1UniversalType as _UniversalType,
    ObjectIdentifier as _OID,
    External as _External,
    EmbeddedPDV as _PDV,
    ASN1ConstructionError as _ConstructionError,
} from "@wildboar/asn1";
import * as $ from "@wildboar/asn1/functional";
import { TransactionId, _decode_TransactionId, _encode_TransactionId } from "../RSPDefinitions/TransactionId.ta.mjs";
// export { TransactionId, _decode_TransactionId, _encode_TransactionId } from "../RSPDefinitions/TransactionId.ta.mjs";
import { StoreMetadataRequest, _decode_StoreMetadataRequest, _encode_StoreMetadataRequest } from "../SGP32Definitions/StoreMetadataRequest.ta.mjs";
// export { StoreMetadataRequest, _decode_StoreMetadataRequest, _encode_StoreMetadataRequest } from "../SGP32Definitions/StoreMetadataRequest.ta.mjs";
import { SmdpSigned2, _decode_SmdpSigned2, _encode_SmdpSigned2 } from "../RSPDefinitions/SmdpSigned2.ta.mjs";
// export { SmdpSigned2, _decode_SmdpSigned2, _encode_SmdpSigned2 } from "../RSPDefinitions/SmdpSigned2.ta.mjs";
import { Certificate, _decode_Certificate, _encode_Certificate } from "../PKIX1Explicit88/Certificate.ta.mjs";
// export { Certificate, _decode_Certificate, _encode_Certificate } from "../PKIX1Explicit88/Certificate.ta.mjs";
import { Octet32, _decode_Octet32, _encode_Octet32 } from "../RSPDefinitions/Octet32.ta.mjs";
// export { Octet32, _decode_Octet32, _encode_Octet32 } from "../RSPDefinitions/Octet32.ta.mjs";


/**
 * @summary AuthenticateClientOkDPEsipa
 * @description
 * 
 * ### ASN.1 Definition:
 * 
 * ```asn1
 * AuthenticateClientOkDPEsipa ::= SEQUENCE {
 *     transactionId [0] TransactionId OPTIONAL, -- The TransactionID generated by the SM-DP+
 *     profileMetaData [37] StoreMetadataRequest OPTIONAL,
 *     smdpSigned2 SmdpSigned2, -- Signed information
 *     smdpSignature2 [APPLICATION 55] OCTET STRING, -- Tag '5F37'
 *     smdpCertificate Certificate, -- CERT.DPpb.ECDSA
 *     hashCc Octet32 OPTIONAL -- Hash of confirmation code
 * }
 * ```
 * 
 * @class
 */
export
class AuthenticateClientOkDPEsipa {
    constructor (
        /**
         * @summary `transactionId`.
         * @public
         * @readonly
         */
        readonly transactionId: OPTIONAL<TransactionId>,
        /**
         * @summary `profileMetaData`.
         * @public
         * @readonly
         */
        readonly profileMetaData: OPTIONAL<StoreMetadataRequest>,
        /**
         * @summary `smdpSigned2`.
         * @public
         * @readonly
         */
        readonly smdpSigned2: SmdpSigned2,
        /**
         * @summary `smdpSignature2`.
         * @public
         * @readonly
         */
        readonly smdpSignature2: OCTET_STRING,
        /**
         * @summary `smdpCertificate`.
         * @public
         * @readonly
         */
        readonly smdpCertificate: Certificate,
        /**
         * @summary `hashCc`.
         * @public
         * @readonly
         */
        readonly hashCc: OPTIONAL<Octet32>
    ) {}

    /**
     * @summary Restructures an object into a AuthenticateClientOkDPEsipa
     * @description
     * 
     * This takes an `object` and converts it to a `AuthenticateClientOkDPEsipa`.
     * 
     * @public
     * @static
     * @method
     * @param {Object} _o An object having all of the keys and values of a `AuthenticateClientOkDPEsipa`.
     * @returns {AuthenticateClientOkDPEsipa}
     */
    public static _from_object (_o: { [_K in keyof (AuthenticateClientOkDPEsipa)]: (AuthenticateClientOkDPEsipa)[_K] }): AuthenticateClientOkDPEsipa {
        return new AuthenticateClientOkDPEsipa(_o.transactionId, _o.profileMetaData, _o.smdpSigned2, _o.smdpSignature2, _o.smdpCertificate, _o.hashCc);
    }


}

/**
 * @summary The Leading Root Component Types of AuthenticateClientOkDPEsipa
 * @description
 * 
 * This is an array of `ComponentSpec`s that define how to decode the leading root component type list of a SET or SEQUENCE.
 * 
 * @constant
 */
export
const _root_component_type_list_1_spec_for_AuthenticateClientOkDPEsipa: $.ComponentSpec[] = [
    new $.ComponentSpec("transactionId", true, $.hasTag(_TagClass.context, 0)),
    new $.ComponentSpec("profileMetaData", true, $.hasTag(_TagClass.context, 37)),
    new $.ComponentSpec("smdpSigned2", false, $.hasTag(_TagClass.universal, 16)),
    new $.ComponentSpec("smdpSignature2", false, $.hasTag(_TagClass.application, 55)),
    new $.ComponentSpec("smdpCertificate", false, $.hasTag(_TagClass.universal, 16)),
    new $.ComponentSpec("hashCc", true, $.hasTag(_TagClass.universal, 4))
];

/**
 * @summary The Trailing Root Component Types of AuthenticateClientOkDPEsipa
 * @description
 * 
 * This is an array of `ComponentSpec`s that define how to decode the trailing root component type list of a SET or SEQUENCE.
 * 
 * @constant
 */
export
const _root_component_type_list_2_spec_for_AuthenticateClientOkDPEsipa: $.ComponentSpec[] = [
    
];

/**
 * @summary The Extension Addition Component Types of AuthenticateClientOkDPEsipa
 * @description
 * 
 * This is an array of `ComponentSpec`s that define how to decode the extension addition component type list of a SET or SEQUENCE.
 * 
 * @constant
 */
export
const _extension_additions_list_spec_for_AuthenticateClientOkDPEsipa: $.ComponentSpec[] = [
    
];

let _cached_decoder_for_AuthenticateClientOkDPEsipa: $.ASN1Decoder<AuthenticateClientOkDPEsipa> | null = null;

/**
 * @summary Decodes an ASN.1 element into a(n) AuthenticateClientOkDPEsipa
 * @function
 * @param el The element being decoded.
 * @returns The decoded data structure.
 */
export
function _decode_AuthenticateClientOkDPEsipa (el: _Element): AuthenticateClientOkDPEsipa {
    if (!_cached_decoder_for_AuthenticateClientOkDPEsipa) { _cached_decoder_for_AuthenticateClientOkDPEsipa = function (el: _Element): AuthenticateClientOkDPEsipa {
    let transactionId: OPTIONAL<TransactionId>;
    let profileMetaData: OPTIONAL<StoreMetadataRequest>;
    let smdpSigned2!: SmdpSigned2;
    let smdpSignature2!: OCTET_STRING;
    let smdpCertificate!: Certificate;
    let hashCc: OPTIONAL<Octet32>;
    const callbacks: $.DecodingMap = {
        "transactionId": (_el: _Element): void => { transactionId = $._decode_implicit<TransactionId>(() => _decode_TransactionId)(_el); },
        "profileMetaData": (_el: _Element): void => { profileMetaData = $._decode_implicit<StoreMetadataRequest>(() => _decode_StoreMetadataRequest)(_el); },
        "smdpSigned2": (_el: _Element): void => { smdpSigned2 = _decode_SmdpSigned2(_el); },
        "smdpSignature2": (_el: _Element): void => { smdpSignature2 = $._decode_implicit<OCTET_STRING>(() => $._decodeOctetString)(_el); },
        "smdpCertificate": (_el: _Element): void => { smdpCertificate = _decode_Certificate(_el); },
        "hashCc": (_el: _Element): void => { hashCc = _decode_Octet32(_el); }
    };
    $._parse_sequence(el, callbacks,
        _root_component_type_list_1_spec_for_AuthenticateClientOkDPEsipa,
        _extension_additions_list_spec_for_AuthenticateClientOkDPEsipa,
        _root_component_type_list_2_spec_for_AuthenticateClientOkDPEsipa,
        undefined,
    );
    return new AuthenticateClientOkDPEsipa(
        transactionId,
        profileMetaData,
        smdpSigned2,
        smdpSignature2,
        smdpCertificate,
        hashCc
    );
}; }
    return _cached_decoder_for_AuthenticateClientOkDPEsipa(el);
}

let _cached_encoder_for_AuthenticateClientOkDPEsipa: $.ASN1Encoder<AuthenticateClientOkDPEsipa> | null = null;

/**
 * @summary Encodes a(n) AuthenticateClientOkDPEsipa into an ASN.1 Element.
 * @function
 * @param value The value being encoded.
 * @param elGetter A function that can be used to get new ASN.1 elements.
 * @returns {_Element} The AuthenticateClientOkDPEsipa, encoded as an ASN.1 Element.
 */
export
function _encode_AuthenticateClientOkDPEsipa (value: AuthenticateClientOkDPEsipa, elGetter: $.ASN1Encoder<any>): _Element {
    if (!_cached_encoder_for_AuthenticateClientOkDPEsipa) { _cached_encoder_for_AuthenticateClientOkDPEsipa = function (value: AuthenticateClientOkDPEsipa, elGetter: $.ASN1Encoder<AuthenticateClientOkDPEsipa>): _Element {
    return $._encodeSequence(([] as (_Element | undefined)[]).concat(
        [
            /* IF_ABSENT  */ ((value.transactionId === undefined) ? undefined : $._encode_implicit(_TagClass.context, 0, () => _encode_TransactionId, $.BER)(value.transactionId, $.BER)),
            /* IF_ABSENT  */ ((value.profileMetaData === undefined) ? undefined : $._encode_implicit(_TagClass.context, 37, () => _encode_StoreMetadataRequest, $.BER)(value.profileMetaData, $.BER)),
            /* REQUIRED   */ _encode_SmdpSigned2(value.smdpSigned2, $.BER),
            /* REQUIRED   */ $._encode_implicit(_TagClass.application, 55, () => $._encodeOctetString, $.BER)(value.smdpSignature2, $.BER),
            /* REQUIRED   */ _encode_Certificate(value.smdpCertificate, $.BER),
            /* IF_ABSENT  */ ((value.hashCc === undefined) ? undefined : _encode_Octet32(value.hashCc, $.BER))
        ],
    ).filter((c: (_Element | undefined)): c is _Element => (!!c)), $.BER);
}; }
    return _cached_encoder_for_AuthenticateClientOkDPEsipa(value, elGetter);
}


/* eslint-enable */
