/* eslint-disable */
import {
    itu_t,
    itu_r,
    ccitt,
    iso,
    joint_iso_itu_t,
    joint_iso_ccitt,
    OPTIONAL,
    BOOLEAN,
    INTEGER,
    BIT_STRING,
    OCTET_STRING,
    NULL,
    OBJECT_IDENTIFIER,
    ObjectDescriptor,
    EXTERNAL,
    REAL,
    INSTANCE_OF,
    ENUMERATED,
    EMBEDDED_PDV,
    UTF8String,
    RELATIVE_OID,
    SEQUENCE,
    SEQUENCE_OF,
    SET,
    SET_OF,
    GraphicString,
    NumericString,
    VisibleString,
    PrintableString,
    ISO646String,
    TeletexString,
    GeneralString,
    T61String,
    UniversalString,
    VideotexString,
    BMPString,
    IA5String,
    CharacterString,
    UTCTime,
    GeneralizedTime,
    TIME,
    DATE,
    TIME_OF_DAY,
    DATE_TIME,
    DURATION,
    OID_IRI,
    RELATIVE_OID_IRI,
    TRUE,
    FALSE,
    TRUE_BIT,
    FALSE_BIT,
    PLUS_INFINITY,
    MINUS_INFINITY,
    NOT_A_NUMBER,
    TYPE_IDENTIFIER,
    ABSTRACT_SYNTAX,
    ASN1Element as _Element,
    ASN1TagClass as _TagClass,
    ASN1Construction as _Construction,
    ASN1UniversalType as _UniversalType,
    ObjectIdentifier as _OID,
    External as _External,
    EmbeddedPDV as _PDV,
    ASN1ConstructionError as _ConstructionError,
} from "@wildboar/asn1";
import * as $ from "@wildboar/asn1/functional";
import { TransactionId, _decode_TransactionId, _encode_TransactionId } from "../RSPDefinitions/TransactionId.ta.mjs";
// export { TransactionId, _decode_TransactionId, _encode_TransactionId } from "../RSPDefinitions/TransactionId.ta.mjs";
import { CancelSessionResponse, _decode_CancelSessionResponse, _encode_CancelSessionResponse } from "../SGP32Definitions/CancelSessionResponse.ta.mjs";
// export { CancelSessionResponse, _decode_CancelSessionResponse, _encode_CancelSessionResponse } from "../SGP32Definitions/CancelSessionResponse.ta.mjs";


/**
 * @summary CancelSessionRequestEsipa
 * @description
 * 
 * ### ASN.1 Definition:
 * 
 * ```asn1
 * CancelSessionRequestEsipa ::= [65] SEQUENCE { -- Tag 'BF41'
 *     transactionId TransactionId, -- The TransactionID generated by the SM-DP+
 *     cancelSessionResponse CancelSessionResponse -- This is the response from ES10b. CancelSession function, possibly in compact format
 * }
 * ```
 * 
 * @class
 */
export
class CancelSessionRequestEsipa {
    constructor (
        /**
         * @summary `transactionId`.
         * @public
         * @readonly
         */
        readonly transactionId: TransactionId,
        /**
         * @summary `cancelSessionResponse`.
         * @public
         * @readonly
         */
        readonly cancelSessionResponse: CancelSessionResponse
    ) {}

    /**
     * @summary Restructures an object into a CancelSessionRequestEsipa
     * @description
     * 
     * This takes an `object` and converts it to a `CancelSessionRequestEsipa`.
     * 
     * @public
     * @static
     * @method
     * @param {Object} _o An object having all of the keys and values of a `CancelSessionRequestEsipa`.
     * @returns {CancelSessionRequestEsipa}
     */
    public static _from_object (_o: { [_K in keyof (CancelSessionRequestEsipa)]: (CancelSessionRequestEsipa)[_K] }): CancelSessionRequestEsipa {
        return new CancelSessionRequestEsipa(_o.transactionId, _o.cancelSessionResponse);
    }


}

/**
 * @summary The Leading Root Component Types of CancelSessionRequestEsipa
 * @description
 * 
 * This is an array of `ComponentSpec`s that define how to decode the leading root component type list of a SET or SEQUENCE.
 * 
 * @constant
 */
export
const _root_component_type_list_1_spec_for_CancelSessionRequestEsipa: $.ComponentSpec[] = [
    new $.ComponentSpec("transactionId", false, $.hasTag(_TagClass.context, 0)),
    new $.ComponentSpec("cancelSessionResponse", false, $.hasTag(_TagClass.context, 1))
];

/**
 * @summary The Trailing Root Component Types of CancelSessionRequestEsipa
 * @description
 * 
 * This is an array of `ComponentSpec`s that define how to decode the trailing root component type list of a SET or SEQUENCE.
 * 
 * @constant
 */
export
const _root_component_type_list_2_spec_for_CancelSessionRequestEsipa: $.ComponentSpec[] = [
    
];

/**
 * @summary The Extension Addition Component Types of CancelSessionRequestEsipa
 * @description
 * 
 * This is an array of `ComponentSpec`s that define how to decode the extension addition component type list of a SET or SEQUENCE.
 * 
 * @constant
 */
export
const _extension_additions_list_spec_for_CancelSessionRequestEsipa: $.ComponentSpec[] = [
    
];

let _cached_decoder_for_CancelSessionRequestEsipa: $.ASN1Decoder<CancelSessionRequestEsipa> | null = null;

/**
 * @summary Decodes an ASN.1 element into a(n) CancelSessionRequestEsipa
 * @function
 * @param el The element being decoded.
 * @returns The decoded data structure.
 */
export
function _decode_CancelSessionRequestEsipa (el: _Element): CancelSessionRequestEsipa {
    if (!_cached_decoder_for_CancelSessionRequestEsipa) { _cached_decoder_for_CancelSessionRequestEsipa = $._decode_implicit<CancelSessionRequestEsipa>(() => function (el: _Element): CancelSessionRequestEsipa {
    const sequence: _Element[] = el.sequence;
    if (sequence.length < 2) {
        throw new _ConstructionError("CancelSessionRequestEsipa contained only " + sequence.length.toString() + " elements.");
    }
    sequence[0].name = "transactionId";
    sequence[1].name = "cancelSessionResponse";
    let transactionId!: TransactionId;
    let cancelSessionResponse!: CancelSessionResponse;
    transactionId = _decode_TransactionId(sequence[0]);
    cancelSessionResponse = _decode_CancelSessionResponse(sequence[1]);
    return new CancelSessionRequestEsipa(
        transactionId,
        cancelSessionResponse,

    );
}); }
    return _cached_decoder_for_CancelSessionRequestEsipa(el);
}

let _cached_encoder_for_CancelSessionRequestEsipa: $.ASN1Encoder<CancelSessionRequestEsipa> | null = null;

/**
 * @summary Encodes a(n) CancelSessionRequestEsipa into an ASN.1 Element.
 * @function
 * @param value The value being encoded.
 * @param elGetter A function that can be used to get new ASN.1 elements.
 * @returns {_Element} The CancelSessionRequestEsipa, encoded as an ASN.1 Element.
 */
export
function _encode_CancelSessionRequestEsipa (value: CancelSessionRequestEsipa, elGetter: $.ASN1Encoder<any>): _Element {
    if (!_cached_encoder_for_CancelSessionRequestEsipa) { _cached_encoder_for_CancelSessionRequestEsipa = $._encode_implicit(_TagClass.context, 65, () => function (value: CancelSessionRequestEsipa, elGetter: $.ASN1Encoder<CancelSessionRequestEsipa>): _Element {
    return $._encodeSequence(([] as (_Element | undefined)[]).concat(
        [
            /* REQUIRED   */ _encode_TransactionId(value.transactionId, $.BER),
            /* REQUIRED   */ _encode_CancelSessionResponse(value.cancelSessionResponse, $.BER)
        ],
    ).filter((c: (_Element | undefined)): c is _Element => (!!c)), $.BER);
}, $.BER); }
    return _cached_encoder_for_CancelSessionRequestEsipa(value, elGetter);
}


/* eslint-enable */
