/* eslint-disable */
import {
    BOOLEAN,
    INTEGER,
    OPTIONAL,
    ASN1Element as _Element,
    ASN1TagClass as _TagClass
} from "@wildboar/asn1";
import * as $ from "@wildboar/asn1/functional";
import { TransactionId, _decode_TransactionId, _encode_TransactionId } from "../RSPDefinitions/TransactionId.ta.mjs";
// export { TransactionId, _decode_TransactionId, _encode_TransactionId } from "../RSPDefinitions/TransactionId.ta.mjs";
import { CompactProfileInstallationResultData_compactFinalResult, _decode_CompactProfileInstallationResultData_compactFinalResult, _encode_CompactProfileInstallationResultData_compactFinalResult } from "../SGP32Definitions/CompactProfileInstallationResultData-compactFinalResult.ta.mjs";
// export { CompactProfileInstallationResultData_compactFinalResult, _decode_CompactProfileInstallationResultData_compactFinalResult, _encode_CompactProfileInstallationResultData_compactFinalResult } from "../SGP32Definitions/CompactProfileInstallationResultData-compactFinalResult.ta.mjs";


/**
 * @summary CompactProfileInstallationResultData
 * @description
 * 
 * ### ASN.1 Definition:
 * 
 * ```asn1
 * CompactProfileInstallationResultData ::= SEQUENCE {
 *     transactionId [0] TransactionId, -- The TransactionID generated by the SM-DP+
 *     seqNumber INTEGER,
 *     iccidPresent BOOLEAN DEFAULT TRUE,
 *     compactFinalResult [2] CHOICE {
 *         compactSuccessResult CompactSuccessResult,
 *         errorResult ErrorResult
 *     }
 * }
 * ```
 * 
 * @class
 */
export
class CompactProfileInstallationResultData {
    constructor (
        /**
         * @summary `transactionId`.
         * @public
         * @readonly
         */
        readonly transactionId: TransactionId,
        /**
         * @summary `seqNumber`.
         * @public
         * @readonly
         */
        readonly seqNumber: INTEGER,
        /**
         * @summary `iccidPresent`.
         * @public
         * @readonly
         */
        readonly iccidPresent: OPTIONAL<BOOLEAN>,
        /**
         * @summary `compactFinalResult`.
         * @public
         * @readonly
         */
        readonly compactFinalResult: CompactProfileInstallationResultData_compactFinalResult
    ) {}

    /**
     * @summary Restructures an object into a CompactProfileInstallationResultData
     * @description
     * 
     * This takes an `object` and converts it to a `CompactProfileInstallationResultData`.
     * 
     * @public
     * @static
     * @method
     * @param {Object} _o An object having all of the keys and values of a `CompactProfileInstallationResultData`.
     * @returns {CompactProfileInstallationResultData}
     */
    public static _from_object (_o: { [_K in keyof (CompactProfileInstallationResultData)]: (CompactProfileInstallationResultData)[_K] }): CompactProfileInstallationResultData {
        return new CompactProfileInstallationResultData(_o.transactionId, _o.seqNumber, _o.iccidPresent, _o.compactFinalResult);
    }

    /**
     * @summary Getter that returns the default value for `iccidPresent`.
     * @public
     * @static
     * @method
     */
    public static get _default_value_for_iccidPresent () { return true; }
}

/**
 * @summary The Leading Root Component Types of CompactProfileInstallationResultData
 * @description
 * 
 * This is an array of `ComponentSpec`s that define how to decode the leading root component type list of a SET or SEQUENCE.
 * 
 * @constant
 */
export
const _root_component_type_list_1_spec_for_CompactProfileInstallationResultData: $.ComponentSpec[] = [
    new $.ComponentSpec("transactionId", false, $.hasTag(_TagClass.context, 0)),
    new $.ComponentSpec("seqNumber", false, $.hasTag(_TagClass.universal, 2)),
    new $.ComponentSpec("iccidPresent", true, $.hasTag(_TagClass.universal, 1)),
    new $.ComponentSpec("compactFinalResult", false, $.hasTag(_TagClass.context, 2))
];

/**
 * @summary The Trailing Root Component Types of CompactProfileInstallationResultData
 * @description
 * 
 * This is an array of `ComponentSpec`s that define how to decode the trailing root component type list of a SET or SEQUENCE.
 * 
 * @constant
 */
export
const _root_component_type_list_2_spec_for_CompactProfileInstallationResultData: $.ComponentSpec[] = [
    
];

/**
 * @summary The Extension Addition Component Types of CompactProfileInstallationResultData
 * @description
 * 
 * This is an array of `ComponentSpec`s that define how to decode the extension addition component type list of a SET or SEQUENCE.
 * 
 * @constant
 */
export
const _extension_additions_list_spec_for_CompactProfileInstallationResultData: $.ComponentSpec[] = [
    
];

let _cached_decoder_for_CompactProfileInstallationResultData: $.ASN1Decoder<CompactProfileInstallationResultData> | null = null;

/**
 * @summary Decodes an ASN.1 element into a(n) CompactProfileInstallationResultData
 * @function
 * @param el The element being decoded.
 * @returns The decoded data structure.
 */
export
function _decode_CompactProfileInstallationResultData (el: _Element): CompactProfileInstallationResultData {
    if (!_cached_decoder_for_CompactProfileInstallationResultData) { _cached_decoder_for_CompactProfileInstallationResultData = function (el: _Element): CompactProfileInstallationResultData {
    let transactionId!: TransactionId;
    let seqNumber!: INTEGER;
    let iccidPresent: OPTIONAL<BOOLEAN> = CompactProfileInstallationResultData._default_value_for_iccidPresent;
    let compactFinalResult!: CompactProfileInstallationResultData_compactFinalResult;
    const callbacks: $.DecodingMap = {
        "transactionId": (_el: _Element): void => { transactionId = $._decode_implicit<TransactionId>(() => _decode_TransactionId)(_el); },
        "seqNumber": (_el: _Element): void => { seqNumber = $._decodeInteger(_el); },
        "iccidPresent": (_el: _Element): void => { iccidPresent = $._decodeBoolean(_el); },
        "compactFinalResult": (_el: _Element): void => { compactFinalResult = $._decode_explicit<CompactProfileInstallationResultData_compactFinalResult>(() => _decode_CompactProfileInstallationResultData_compactFinalResult)(_el); }
    };
    $._parse_sequence(el, callbacks,
        _root_component_type_list_1_spec_for_CompactProfileInstallationResultData,
        _extension_additions_list_spec_for_CompactProfileInstallationResultData,
        _root_component_type_list_2_spec_for_CompactProfileInstallationResultData,
        undefined,
    );
    return new CompactProfileInstallationResultData(
        transactionId,
        seqNumber,
        iccidPresent,
        compactFinalResult
    );
}; }
    return _cached_decoder_for_CompactProfileInstallationResultData(el);
}

let _cached_encoder_for_CompactProfileInstallationResultData: $.ASN1Encoder<CompactProfileInstallationResultData> | null = null;

/**
 * @summary Encodes a(n) CompactProfileInstallationResultData into an ASN.1 Element.
 * @function
 * @param value The value being encoded.
 * @param elGetter A function that can be used to get new ASN.1 elements.
 * @returns {_Element} The CompactProfileInstallationResultData, encoded as an ASN.1 Element.
 */
export
function _encode_CompactProfileInstallationResultData (value: CompactProfileInstallationResultData, elGetter: $.ASN1Encoder<any>): _Element {
    if (!_cached_encoder_for_CompactProfileInstallationResultData) { _cached_encoder_for_CompactProfileInstallationResultData = function (value: CompactProfileInstallationResultData, elGetter: $.ASN1Encoder<CompactProfileInstallationResultData>): _Element {
    return $._encodeSequence(([] as (_Element | undefined)[]).concat(
        [
            /* REQUIRED   */ $._encode_implicit(_TagClass.context, 0, () => _encode_TransactionId, $.BER)(value.transactionId, $.BER),
            /* REQUIRED   */ $._encodeInteger(value.seqNumber, $.BER),
            /* IF_DEFAULT */ (value.iccidPresent === undefined || $.deepEq(value.iccidPresent, CompactProfileInstallationResultData._default_value_for_iccidPresent) ? undefined : $._encodeBoolean(value.iccidPresent, $.BER)),
            /* REQUIRED   */ $._encode_explicit(_TagClass.context, 2, () => _encode_CompactProfileInstallationResultData_compactFinalResult, $.BER)(value.compactFinalResult, $.BER)
        ],
    ).filter((c: (_Element | undefined)): c is _Element => (!!c)), $.BER);
}; }
    return _cached_encoder_for_CompactProfileInstallationResultData(value, elGetter);
}


/* eslint-enable */
