/* eslint-disable */
import {
    itu_t,
    itu_r,
    ccitt,
    iso,
    joint_iso_itu_t,
    joint_iso_ccitt,
    OPTIONAL,
    BOOLEAN,
    INTEGER,
    BIT_STRING,
    OCTET_STRING,
    NULL,
    OBJECT_IDENTIFIER,
    ObjectDescriptor,
    EXTERNAL,
    REAL,
    INSTANCE_OF,
    ENUMERATED,
    EMBEDDED_PDV,
    UTF8String,
    RELATIVE_OID,
    SEQUENCE,
    SEQUENCE_OF,
    SET,
    SET_OF,
    GraphicString,
    NumericString,
    VisibleString,
    PrintableString,
    ISO646String,
    TeletexString,
    GeneralString,
    T61String,
    UniversalString,
    VideotexString,
    BMPString,
    IA5String,
    CharacterString,
    UTCTime,
    GeneralizedTime,
    TIME,
    DATE,
    TIME_OF_DAY,
    DATE_TIME,
    DURATION,
    OID_IRI,
    RELATIVE_OID_IRI,
    TRUE,
    FALSE,
    TRUE_BIT,
    FALSE_BIT,
    PLUS_INFINITY,
    MINUS_INFINITY,
    NOT_A_NUMBER,
    TYPE_IDENTIFIER,
    ABSTRACT_SYNTAX,
    ASN1Element as _Element,
    ASN1TagClass as _TagClass,
    ASN1Construction as _Construction,
    ASN1UniversalType as _UniversalType,
    ObjectIdentifier as _OID,
    External as _External,
    EmbeddedPDV as _PDV,
    ASN1ConstructionError as _ConstructionError,
} from "@wildboar/asn1";
import * as $ from "@wildboar/asn1/functional";
import { TransactionId, _decode_TransactionId, _encode_TransactionId } from "../RSPDefinitions/TransactionId.ta.mjs";
// export { TransactionId, _decode_TransactionId, _encode_TransactionId } from "../RSPDefinitions/TransactionId.ta.mjs";
import { BoundProfilePackage, _decode_BoundProfilePackage, _encode_BoundProfilePackage } from "../RSPDefinitions/BoundProfilePackage.ta.mjs";
// export { BoundProfilePackage, _decode_BoundProfilePackage, _encode_BoundProfilePackage } from "../RSPDefinitions/BoundProfilePackage.ta.mjs";


/**
 * @summary GetBoundProfilePackageOkEsipa
 * @description
 * 
 * ### ASN.1 Definition:
 * 
 * ```asn1
 * GetBoundProfilePackageOkEsipa ::= SEQUENCE {
 *     transactionId [0] TransactionId OPTIONAL, -- The TransactionID generated by the SM-DP+
 *     boundProfilePackage [54] BoundProfilePackage
 * }
 * ```
 * 
 * @class
 */
export
class GetBoundProfilePackageOkEsipa {
    constructor (
        /**
         * @summary `transactionId`.
         * @public
         * @readonly
         */
        readonly transactionId: OPTIONAL<TransactionId>,
        /**
         * @summary `boundProfilePackage`.
         * @public
         * @readonly
         */
        readonly boundProfilePackage: BoundProfilePackage
    ) {}

    /**
     * @summary Restructures an object into a GetBoundProfilePackageOkEsipa
     * @description
     * 
     * This takes an `object` and converts it to a `GetBoundProfilePackageOkEsipa`.
     * 
     * @public
     * @static
     * @method
     * @param {Object} _o An object having all of the keys and values of a `GetBoundProfilePackageOkEsipa`.
     * @returns {GetBoundProfilePackageOkEsipa}
     */
    public static _from_object (_o: { [_K in keyof (GetBoundProfilePackageOkEsipa)]: (GetBoundProfilePackageOkEsipa)[_K] }): GetBoundProfilePackageOkEsipa {
        return new GetBoundProfilePackageOkEsipa(_o.transactionId, _o.boundProfilePackage);
    }


}

/**
 * @summary The Leading Root Component Types of GetBoundProfilePackageOkEsipa
 * @description
 * 
 * This is an array of `ComponentSpec`s that define how to decode the leading root component type list of a SET or SEQUENCE.
 * 
 * @constant
 */
export
const _root_component_type_list_1_spec_for_GetBoundProfilePackageOkEsipa: $.ComponentSpec[] = [
    new $.ComponentSpec("transactionId", true, $.hasTag(_TagClass.context, 0)),
    new $.ComponentSpec("boundProfilePackage", false, $.hasTag(_TagClass.context, 54))
];

/**
 * @summary The Trailing Root Component Types of GetBoundProfilePackageOkEsipa
 * @description
 * 
 * This is an array of `ComponentSpec`s that define how to decode the trailing root component type list of a SET or SEQUENCE.
 * 
 * @constant
 */
export
const _root_component_type_list_2_spec_for_GetBoundProfilePackageOkEsipa: $.ComponentSpec[] = [
    
];

/**
 * @summary The Extension Addition Component Types of GetBoundProfilePackageOkEsipa
 * @description
 * 
 * This is an array of `ComponentSpec`s that define how to decode the extension addition component type list of a SET or SEQUENCE.
 * 
 * @constant
 */
export
const _extension_additions_list_spec_for_GetBoundProfilePackageOkEsipa: $.ComponentSpec[] = [
    
];

let _cached_decoder_for_GetBoundProfilePackageOkEsipa: $.ASN1Decoder<GetBoundProfilePackageOkEsipa> | null = null;

/**
 * @summary Decodes an ASN.1 element into a(n) GetBoundProfilePackageOkEsipa
 * @function
 * @param el The element being decoded.
 * @returns The decoded data structure.
 */
export
function _decode_GetBoundProfilePackageOkEsipa (el: _Element): GetBoundProfilePackageOkEsipa {
    if (!_cached_decoder_for_GetBoundProfilePackageOkEsipa) { _cached_decoder_for_GetBoundProfilePackageOkEsipa = function (el: _Element): GetBoundProfilePackageOkEsipa {
    let transactionId: OPTIONAL<TransactionId>;
    let boundProfilePackage!: BoundProfilePackage;
    const callbacks: $.DecodingMap = {
        "transactionId": (_el: _Element): void => { transactionId = $._decode_implicit<TransactionId>(() => _decode_TransactionId)(_el); },
        "boundProfilePackage": (_el: _Element): void => { boundProfilePackage = $._decode_implicit<BoundProfilePackage>(() => _decode_BoundProfilePackage)(_el); }
    };
    $._parse_sequence(el, callbacks,
        _root_component_type_list_1_spec_for_GetBoundProfilePackageOkEsipa,
        _extension_additions_list_spec_for_GetBoundProfilePackageOkEsipa,
        _root_component_type_list_2_spec_for_GetBoundProfilePackageOkEsipa,
        undefined,
    );
    return new GetBoundProfilePackageOkEsipa(
        transactionId,
        boundProfilePackage
    );
}; }
    return _cached_decoder_for_GetBoundProfilePackageOkEsipa(el);
}

let _cached_encoder_for_GetBoundProfilePackageOkEsipa: $.ASN1Encoder<GetBoundProfilePackageOkEsipa> | null = null;

/**
 * @summary Encodes a(n) GetBoundProfilePackageOkEsipa into an ASN.1 Element.
 * @function
 * @param value The value being encoded.
 * @param elGetter A function that can be used to get new ASN.1 elements.
 * @returns {_Element} The GetBoundProfilePackageOkEsipa, encoded as an ASN.1 Element.
 */
export
function _encode_GetBoundProfilePackageOkEsipa (value: GetBoundProfilePackageOkEsipa, elGetter: $.ASN1Encoder<any>): _Element {
    if (!_cached_encoder_for_GetBoundProfilePackageOkEsipa) { _cached_encoder_for_GetBoundProfilePackageOkEsipa = function (value: GetBoundProfilePackageOkEsipa, elGetter: $.ASN1Encoder<GetBoundProfilePackageOkEsipa>): _Element {
    return $._encodeSequence(([] as (_Element | undefined)[]).concat(
        [
            /* IF_ABSENT  */ ((value.transactionId === undefined) ? undefined : $._encode_implicit(_TagClass.context, 0, () => _encode_TransactionId, $.BER)(value.transactionId, $.BER)),
            /* REQUIRED   */ $._encode_implicit(_TagClass.context, 54, () => _encode_BoundProfilePackage, $.BER)(value.boundProfilePackage, $.BER)
        ],
    ).filter((c: (_Element | undefined)): c is _Element => (!!c)), $.BER);
}; }
    return _cached_encoder_for_GetBoundProfilePackageOkEsipa(value, elGetter);
}


/* eslint-enable */
