/* eslint-disable */
import {
    itu_t,
    itu_r,
    ccitt,
    iso,
    joint_iso_itu_t,
    joint_iso_ccitt,
    OPTIONAL,
    BOOLEAN,
    INTEGER,
    BIT_STRING,
    OCTET_STRING,
    NULL,
    OBJECT_IDENTIFIER,
    ObjectDescriptor,
    EXTERNAL,
    REAL,
    INSTANCE_OF,
    ENUMERATED,
    EMBEDDED_PDV,
    UTF8String,
    RELATIVE_OID,
    SEQUENCE,
    SEQUENCE_OF,
    SET,
    SET_OF,
    GraphicString,
    NumericString,
    VisibleString,
    PrintableString,
    ISO646String,
    TeletexString,
    GeneralString,
    T61String,
    UniversalString,
    VideotexString,
    BMPString,
    IA5String,
    CharacterString,
    UTCTime,
    GeneralizedTime,
    TIME,
    DATE,
    TIME_OF_DAY,
    DATE_TIME,
    DURATION,
    OID_IRI,
    RELATIVE_OID_IRI,
    TRUE,
    FALSE,
    TRUE_BIT,
    FALSE_BIT,
    PLUS_INFINITY,
    MINUS_INFINITY,
    NOT_A_NUMBER,
    TYPE_IDENTIFIER,
    ABSTRACT_SYNTAX,
    ASN1Element as _Element,
    ASN1TagClass as _TagClass,
    ASN1Construction as _Construction,
    ASN1UniversalType as _UniversalType,
    ObjectIdentifier as _OID,
    External as _External,
    EmbeddedPDV as _PDV,
    ASN1ConstructionError as _ConstructionError,
} from "@wildboar/asn1";
import * as $ from "@wildboar/asn1/functional";
import { TransactionId, _decode_TransactionId, _encode_TransactionId } from "../RSPDefinitions/TransactionId.ta.mjs";
// export { TransactionId, _decode_TransactionId, _encode_TransactionId } from "../RSPDefinitions/TransactionId.ta.mjs";
import { PrepareDownloadResponse, _decode_PrepareDownloadResponse, _encode_PrepareDownloadResponse } from "../SGP32Definitions/PrepareDownloadResponse.ta.mjs";
// export { PrepareDownloadResponse, _decode_PrepareDownloadResponse, _encode_PrepareDownloadResponse } from "../SGP32Definitions/PrepareDownloadResponse.ta.mjs";


/**
 * @summary GetBoundProfilePackageRequestEsipa
 * @description
 * 
 * ### ASN.1 Definition:
 * 
 * ```asn1
 * GetBoundProfilePackageRequestEsipa ::= [58] SEQUENCE { -- Tag 'BF3A'
 *     transactionId [0] TransactionId, -- The TransactionID generated by the SM-DP+
 *     prepareDownloadResponse [33] PrepareDownloadResponse -- This is the response from ES10b.PrepareDownload, possibly in compact format
 * }
 * ```
 * 
 * @class
 */
export
class GetBoundProfilePackageRequestEsipa {
    constructor (
        /**
         * @summary `transactionId`.
         * @public
         * @readonly
         */
        readonly transactionId: TransactionId,
        /**
         * @summary `prepareDownloadResponse`.
         * @public
         * @readonly
         */
        readonly prepareDownloadResponse: PrepareDownloadResponse
    ) {}

    /**
     * @summary Restructures an object into a GetBoundProfilePackageRequestEsipa
     * @description
     * 
     * This takes an `object` and converts it to a `GetBoundProfilePackageRequestEsipa`.
     * 
     * @public
     * @static
     * @method
     * @param {Object} _o An object having all of the keys and values of a `GetBoundProfilePackageRequestEsipa`.
     * @returns {GetBoundProfilePackageRequestEsipa}
     */
    public static _from_object (_o: { [_K in keyof (GetBoundProfilePackageRequestEsipa)]: (GetBoundProfilePackageRequestEsipa)[_K] }): GetBoundProfilePackageRequestEsipa {
        return new GetBoundProfilePackageRequestEsipa(_o.transactionId, _o.prepareDownloadResponse);
    }


}

/**
 * @summary The Leading Root Component Types of GetBoundProfilePackageRequestEsipa
 * @description
 * 
 * This is an array of `ComponentSpec`s that define how to decode the leading root component type list of a SET or SEQUENCE.
 * 
 * @constant
 */
export
const _root_component_type_list_1_spec_for_GetBoundProfilePackageRequestEsipa: $.ComponentSpec[] = [
    new $.ComponentSpec("transactionId", false, $.hasTag(_TagClass.context, 0)),
    new $.ComponentSpec("prepareDownloadResponse", false, $.hasTag(_TagClass.context, 33))
];

/**
 * @summary The Trailing Root Component Types of GetBoundProfilePackageRequestEsipa
 * @description
 * 
 * This is an array of `ComponentSpec`s that define how to decode the trailing root component type list of a SET or SEQUENCE.
 * 
 * @constant
 */
export
const _root_component_type_list_2_spec_for_GetBoundProfilePackageRequestEsipa: $.ComponentSpec[] = [
    
];

/**
 * @summary The Extension Addition Component Types of GetBoundProfilePackageRequestEsipa
 * @description
 * 
 * This is an array of `ComponentSpec`s that define how to decode the extension addition component type list of a SET or SEQUENCE.
 * 
 * @constant
 */
export
const _extension_additions_list_spec_for_GetBoundProfilePackageRequestEsipa: $.ComponentSpec[] = [
    
];

let _cached_decoder_for_GetBoundProfilePackageRequestEsipa: $.ASN1Decoder<GetBoundProfilePackageRequestEsipa> | null = null;

/**
 * @summary Decodes an ASN.1 element into a(n) GetBoundProfilePackageRequestEsipa
 * @function
 * @param el The element being decoded.
 * @returns The decoded data structure.
 */
export
function _decode_GetBoundProfilePackageRequestEsipa (el: _Element): GetBoundProfilePackageRequestEsipa {
    if (!_cached_decoder_for_GetBoundProfilePackageRequestEsipa) { _cached_decoder_for_GetBoundProfilePackageRequestEsipa = $._decode_implicit<GetBoundProfilePackageRequestEsipa>(() => function (el: _Element): GetBoundProfilePackageRequestEsipa {
    const sequence: _Element[] = el.sequence;
    if (sequence.length < 2) {
        throw new _ConstructionError("GetBoundProfilePackageRequestEsipa contained only " + sequence.length.toString() + " elements.");
    }
    sequence[0].name = "transactionId";
    sequence[1].name = "prepareDownloadResponse";
    let transactionId!: TransactionId;
    let prepareDownloadResponse!: PrepareDownloadResponse;
    transactionId = $._decode_implicit<TransactionId>(() => _decode_TransactionId)(sequence[0]);
    prepareDownloadResponse = $._decode_implicit<PrepareDownloadResponse>(() => _decode_PrepareDownloadResponse)(sequence[1]);
    return new GetBoundProfilePackageRequestEsipa(
        transactionId,
        prepareDownloadResponse,

    );
}); }
    return _cached_decoder_for_GetBoundProfilePackageRequestEsipa(el);
}

let _cached_encoder_for_GetBoundProfilePackageRequestEsipa: $.ASN1Encoder<GetBoundProfilePackageRequestEsipa> | null = null;

/**
 * @summary Encodes a(n) GetBoundProfilePackageRequestEsipa into an ASN.1 Element.
 * @function
 * @param value The value being encoded.
 * @param elGetter A function that can be used to get new ASN.1 elements.
 * @returns {_Element} The GetBoundProfilePackageRequestEsipa, encoded as an ASN.1 Element.
 */
export
function _encode_GetBoundProfilePackageRequestEsipa (value: GetBoundProfilePackageRequestEsipa, elGetter: $.ASN1Encoder<any>): _Element {
    if (!_cached_encoder_for_GetBoundProfilePackageRequestEsipa) { _cached_encoder_for_GetBoundProfilePackageRequestEsipa = $._encode_implicit(_TagClass.context, 58, () => function (value: GetBoundProfilePackageRequestEsipa, elGetter: $.ASN1Encoder<GetBoundProfilePackageRequestEsipa>): _Element {
    return $._encodeSequence(([] as (_Element | undefined)[]).concat(
        [
            /* REQUIRED   */ $._encode_implicit(_TagClass.context, 0, () => _encode_TransactionId, $.BER)(value.transactionId, $.BER),
            /* REQUIRED   */ $._encode_implicit(_TagClass.context, 33, () => _encode_PrepareDownloadResponse, $.BER)(value.prepareDownloadResponse, $.BER)
        ],
    ).filter((c: (_Element | undefined)): c is _Element => (!!c)), $.BER);
}, $.BER); }
    return _cached_encoder_for_GetBoundProfilePackageRequestEsipa(value, elGetter);
}


/* eslint-enable */
