/* eslint-disable */
import {
    OCTET_STRING,
    OPTIONAL,
    UTF8String,
    ASN1Element as _Element,
    ASN1TagClass as _TagClass
} from "@wildboar/asn1";
import * as $ from "@wildboar/asn1/functional";
import { TransactionId, _decode_TransactionId, _encode_TransactionId } from "../RSPDefinitions/TransactionId.ta.mjs";
// export { TransactionId, _decode_TransactionId, _encode_TransactionId } from "../RSPDefinitions/TransactionId.ta.mjs";
import { ServerSigned1, _decode_ServerSigned1, _encode_ServerSigned1 } from "../RSPDefinitions/ServerSigned1.ta.mjs";
// export { ServerSigned1, _decode_ServerSigned1, _encode_ServerSigned1 } from "../RSPDefinitions/ServerSigned1.ta.mjs";
import { Certificate, _decode_Certificate, _encode_Certificate } from "../PKIX1Explicit88/Certificate.ta.mjs";
// export { Certificate, _decode_Certificate, _encode_Certificate } from "../PKIX1Explicit88/Certificate.ta.mjs";
import { CtxParams1, _decode_CtxParams1, _encode_CtxParams1 } from "../RSPDefinitions/CtxParams1.ta.mjs";
// export { CtxParams1, _decode_CtxParams1, _encode_CtxParams1 } from "../RSPDefinitions/CtxParams1.ta.mjs";


/**
 * @summary InitiateAuthenticationOkEsipa
 * @description
 * 
 * ### ASN.1 Definition:
 * 
 * ```asn1
 * InitiateAuthenticationOkEsipa ::= SEQUENCE {
 *     transactionId [0] TransactionId OPTIONAL, -- The TransactionID generated by the SM-DP+
 *     serverSigned1 ServerSigned1, -- Signed information
 *     serverSignature1 [APPLICATION 55] OCTET STRING, -- Server Sign1, Tag '5F37'
 *     euiccCiPKIdentifierToBeUsed OCTET STRING, -- Key identifier (possibly truncated) of the CI Public Key to be used as required by ES10b.AuthenticateServer
 *     serverCertificate Certificate,
 *     matchingId UTF8String OPTIONAL,
 *     ctxParams1 [2] CtxParams1 OPTIONAL
 * }
 * ```
 * 
 * @class
 */
export
class InitiateAuthenticationOkEsipa {
    constructor (
        /**
         * @summary `transactionId`.
         * @public
         * @readonly
         */
        readonly transactionId: OPTIONAL<TransactionId>,
        /**
         * @summary `serverSigned1`.
         * @public
         * @readonly
         */
        readonly serverSigned1: ServerSigned1,
        /**
         * @summary `serverSignature1`.
         * @public
         * @readonly
         */
        readonly serverSignature1: OCTET_STRING,
        /**
         * @summary `euiccCiPKIdentifierToBeUsed`.
         * @public
         * @readonly
         */
        readonly euiccCiPKIdentifierToBeUsed: OCTET_STRING,
        /**
         * @summary `serverCertificate`.
         * @public
         * @readonly
         */
        readonly serverCertificate: Certificate,
        /**
         * @summary `matchingId`.
         * @public
         * @readonly
         */
        readonly matchingId: OPTIONAL<UTF8String>,
        /**
         * @summary `ctxParams1`.
         * @public
         * @readonly
         */
        readonly ctxParams1: OPTIONAL<CtxParams1>
    ) {}

    /**
     * @summary Restructures an object into a InitiateAuthenticationOkEsipa
     * @description
     * 
     * This takes an `object` and converts it to a `InitiateAuthenticationOkEsipa`.
     * 
     * @public
     * @static
     * @method
     * @param {Object} _o An object having all of the keys and values of a `InitiateAuthenticationOkEsipa`.
     * @returns {InitiateAuthenticationOkEsipa}
     */
    public static _from_object (_o: { [_K in keyof (InitiateAuthenticationOkEsipa)]: (InitiateAuthenticationOkEsipa)[_K] }): InitiateAuthenticationOkEsipa {
        return new InitiateAuthenticationOkEsipa(_o.transactionId, _o.serverSigned1, _o.serverSignature1, _o.euiccCiPKIdentifierToBeUsed, _o.serverCertificate, _o.matchingId, _o.ctxParams1);
    }


}

/**
 * @summary The Leading Root Component Types of InitiateAuthenticationOkEsipa
 * @description
 * 
 * This is an array of `ComponentSpec`s that define how to decode the leading root component type list of a SET or SEQUENCE.
 * 
 * @constant
 */
export
const _root_component_type_list_1_spec_for_InitiateAuthenticationOkEsipa: $.ComponentSpec[] = [
    new $.ComponentSpec("transactionId", true, $.hasTag(_TagClass.context, 0)),
    new $.ComponentSpec("serverSigned1", false, $.hasTag(_TagClass.universal, 16)),
    new $.ComponentSpec("serverSignature1", false, $.hasTag(_TagClass.application, 55)),
    new $.ComponentSpec("euiccCiPKIdentifierToBeUsed", false, $.hasTag(_TagClass.universal, 4)),
    new $.ComponentSpec("serverCertificate", false, $.hasTag(_TagClass.universal, 16)),
    new $.ComponentSpec("matchingId", true, $.hasTag(_TagClass.universal, 12)),
    new $.ComponentSpec("ctxParams1", true, $.hasTag(_TagClass.context, 2))
];

/**
 * @summary The Trailing Root Component Types of InitiateAuthenticationOkEsipa
 * @description
 * 
 * This is an array of `ComponentSpec`s that define how to decode the trailing root component type list of a SET or SEQUENCE.
 * 
 * @constant
 */
export
const _root_component_type_list_2_spec_for_InitiateAuthenticationOkEsipa: $.ComponentSpec[] = [
    
];

/**
 * @summary The Extension Addition Component Types of InitiateAuthenticationOkEsipa
 * @description
 * 
 * This is an array of `ComponentSpec`s that define how to decode the extension addition component type list of a SET or SEQUENCE.
 * 
 * @constant
 */
export
const _extension_additions_list_spec_for_InitiateAuthenticationOkEsipa: $.ComponentSpec[] = [
    
];

let _cached_decoder_for_InitiateAuthenticationOkEsipa: $.ASN1Decoder<InitiateAuthenticationOkEsipa> | null = null;

/**
 * @summary Decodes an ASN.1 element into a(n) InitiateAuthenticationOkEsipa
 * @function
 * @param el The element being decoded.
 * @returns The decoded data structure.
 */
export
function _decode_InitiateAuthenticationOkEsipa (el: _Element): InitiateAuthenticationOkEsipa {
    if (!_cached_decoder_for_InitiateAuthenticationOkEsipa) { _cached_decoder_for_InitiateAuthenticationOkEsipa = function (el: _Element): InitiateAuthenticationOkEsipa {
    let transactionId: OPTIONAL<TransactionId>;
    let serverSigned1!: ServerSigned1;
    let serverSignature1!: OCTET_STRING;
    let euiccCiPKIdentifierToBeUsed!: OCTET_STRING;
    let serverCertificate!: Certificate;
    let matchingId: OPTIONAL<UTF8String>;
    let ctxParams1: OPTIONAL<CtxParams1>;
    const callbacks: $.DecodingMap = {
        "transactionId": (_el: _Element): void => { transactionId = $._decode_implicit<TransactionId>(() => _decode_TransactionId)(_el); },
        "serverSigned1": (_el: _Element): void => { serverSigned1 = _decode_ServerSigned1(_el); },
        "serverSignature1": (_el: _Element): void => { serverSignature1 = $._decode_implicit<OCTET_STRING>(() => $._decodeOctetString)(_el); },
        "euiccCiPKIdentifierToBeUsed": (_el: _Element): void => { euiccCiPKIdentifierToBeUsed = $._decodeOctetString(_el); },
        "serverCertificate": (_el: _Element): void => { serverCertificate = _decode_Certificate(_el); },
        "matchingId": (_el: _Element): void => { matchingId = $._decodeUTF8String(_el); },
        "ctxParams1": (_el: _Element): void => { ctxParams1 = $._decode_explicit<CtxParams1>(() => _decode_CtxParams1)(_el); }
    };
    $._parse_sequence(el, callbacks,
        _root_component_type_list_1_spec_for_InitiateAuthenticationOkEsipa,
        _extension_additions_list_spec_for_InitiateAuthenticationOkEsipa,
        _root_component_type_list_2_spec_for_InitiateAuthenticationOkEsipa,
        undefined,
    );
    return new InitiateAuthenticationOkEsipa(
        transactionId,
        serverSigned1,
        serverSignature1,
        euiccCiPKIdentifierToBeUsed,
        serverCertificate,
        matchingId,
        ctxParams1
    );
}; }
    return _cached_decoder_for_InitiateAuthenticationOkEsipa(el);
}

let _cached_encoder_for_InitiateAuthenticationOkEsipa: $.ASN1Encoder<InitiateAuthenticationOkEsipa> | null = null;

/**
 * @summary Encodes a(n) InitiateAuthenticationOkEsipa into an ASN.1 Element.
 * @function
 * @param value The value being encoded.
 * @param elGetter A function that can be used to get new ASN.1 elements.
 * @returns {_Element} The InitiateAuthenticationOkEsipa, encoded as an ASN.1 Element.
 */
export
function _encode_InitiateAuthenticationOkEsipa (value: InitiateAuthenticationOkEsipa, elGetter: $.ASN1Encoder<any>): _Element {
    if (!_cached_encoder_for_InitiateAuthenticationOkEsipa) { _cached_encoder_for_InitiateAuthenticationOkEsipa = function (value: InitiateAuthenticationOkEsipa, elGetter: $.ASN1Encoder<InitiateAuthenticationOkEsipa>): _Element {
    return $._encodeSequence(([] as (_Element | undefined)[]).concat(
        [
            /* IF_ABSENT  */ ((value.transactionId === undefined) ? undefined : $._encode_implicit(_TagClass.context, 0, () => _encode_TransactionId, $.BER)(value.transactionId, $.BER)),
            /* REQUIRED   */ _encode_ServerSigned1(value.serverSigned1, $.BER),
            /* REQUIRED   */ $._encode_implicit(_TagClass.application, 55, () => $._encodeOctetString, $.BER)(value.serverSignature1, $.BER),
            /* REQUIRED   */ $._encodeOctetString(value.euiccCiPKIdentifierToBeUsed, $.BER),
            /* REQUIRED   */ _encode_Certificate(value.serverCertificate, $.BER),
            /* IF_ABSENT  */ ((value.matchingId === undefined) ? undefined : $._encodeUTF8String(value.matchingId, $.BER)),
            /* IF_ABSENT  */ ((value.ctxParams1 === undefined) ? undefined : $._encode_explicit(_TagClass.context, 2, () => _encode_CtxParams1, $.BER)(value.ctxParams1, $.BER))
        ],
    ).filter((c: (_Element | undefined)): c is _Element => (!!c)), $.BER);
}; }
    return _cached_encoder_for_InitiateAuthenticationOkEsipa(value, elGetter);
}


/* eslint-enable */
