/* eslint-disable */
import {
    ASN1Element as _Element,
    ASN1TagClass as _TagClass,
    ASN1Construction as _Construction,
    ASN1UniversalType as _UniversalType,
    ObjectIdentifier as _OID,
    External as _External,
    EmbeddedPDV as _PDV,
    ASN1ConstructionError as _ConstructionError,
} from '@wildboar/asn1';
import {
    EventTypeId,
    _decode_EventTypeId,
    _encode_EventTypeId,
} from '@wildboar/cmip';
/**
 * @summary non_delivery
 * @description
 *
 * `non_delivery`. This argument contains a code indicating the nature of the problem
 * which caused delivery or probing of delivery of the subject-message, to fail. It may
 * be generated by the MTS if the message was (or would have been) unsuccessfully
 * delivered. See ITU-T X.411 (1999), §8.3.1.2.1.12.
 *
 * ### ASN.1 Definition:
 *
 * ```asn1
 * non-delivery EventTypeId ::= localForm:21
 * ```
 *
 * @constant
 */
export const non_delivery: EventTypeId = { localForm: 21 };

/* eslint-enable */
