/* eslint-disable */
import {
    ASN1Element as _Element,
    ASN1TagClass as _TagClass,
    ASN1Construction as _Construction,
    ASN1UniversalType as _UniversalType,
    ObjectIdentifier as _OID,
    External as _External,
    EmbeddedPDV as _PDV,
    ASN1ConstructionError as _ConstructionError,
} from '@wildboar/asn1';
import * as $ from '@wildboar/asn1/functional';

/**
 * @summary SignalDirection
 * @description
 *
 * Direction of a resource-boundary signal at a PCO: `send`
 * inserts into the resource; `receive` is generated by the
 * resource and observed. ITU-T Rec. X.737 (11/95)
 * [§7.6.2.2](https://www.itu.int/rec/T-REC-X.737-199511-I), A.7.
 *
 * ### ASN.1 Definition:
 *
 * ```asn1
 * SignalDirection  ::=  ENUMERATED {send(0), receive(1)}
 * ```
 *
 * @enum {number}
 */
export enum _enum_for_SignalDirection {
    send = 0,
    receive = 1,
}

/**
 * @summary SignalDirection
 * @description
 *
 * Direction of a resource-boundary signal at a PCO: `send`
 * inserts into the resource; `receive` is generated by the
 * resource and observed. ITU-T Rec. X.737 (11/95)
 * [§7.6.2.2](https://www.itu.int/rec/T-REC-X.737-199511-I), A.7.
 *
 * ### ASN.1 Definition:
 *
 * ```asn1
 * SignalDirection  ::=  ENUMERATED {send(0), receive(1)}
 * ```
 *
 * @enum {number}
 */
export type SignalDirection = _enum_for_SignalDirection;

/**
 * @summary SignalDirection
 * @description
 *
 * Direction of a resource-boundary signal at a PCO: `send`
 * inserts into the resource; `receive` is generated by the
 * resource and observed. ITU-T Rec. X.737 (11/95)
 * [§7.6.2.2](https://www.itu.int/rec/T-REC-X.737-199511-I), A.7.
 *
 * ### ASN.1 Definition:
 *
 * ```asn1
 * SignalDirection  ::=  ENUMERATED {send(0), receive(1)}
 * ```
 *
 * @enum {number}
 */
export const SignalDirection = _enum_for_SignalDirection;

/**
 * @summary SignalDirection_send
 * @description
 *
 * Insert the signal at the PCO (0). X.737 §7.6.2.2.
 * @constant
 * @type {number}
 */
export const SignalDirection_send: SignalDirection =
    SignalDirection.send; /* LONG_NAMED_ENUMERATED_VALUE */

/**
 * @summary send
 * @description
 *
 * Insert the signal at the PCO (0). X.737 §7.6.2.2.
 * @constant
 * @type {number}
 */
export const send: SignalDirection =
    SignalDirection.send; /* SHORT_NAMED_ENUMERATED_VALUE */

/**
 * @summary SignalDirection_receive
 * @description
 *
 * Expect the signal from the resource at the PCO (1). X.737 §7.6.2.2.
 * @constant
 * @type {number}
 */
export const SignalDirection_receive: SignalDirection =
    SignalDirection.receive; /* LONG_NAMED_ENUMERATED_VALUE */

/**
 * @summary receive
 * @description
 *
 * Expect the signal from the resource at the PCO (1). X.737 §7.6.2.2.
 * @constant
 * @type {number}
 */
export const receive: SignalDirection =
    SignalDirection.receive; /* SHORT_NAMED_ENUMERATED_VALUE */


export const _decode_SignalDirection = $._decodeEnumerated;


export const _encode_SignalDirection = $._encodeEnumerated;


/* eslint-enable */
