/**
 * @packageDocumentation
 *
 * TypeScript encodings of ICAO Doc 9303 electronic Machine Readable Travel
 * Document (eMRTD) security structures: the LDS security object, CSCA master
 * lists, deviation lists, and the security infos and certificate extensions
 * collected from Parts 11 and 12.
 *
 * Import from `@wildboar/emrtd`. Per-module subpaths remain available.
 *
 * `AlgorithmIdentifier`, `Certificate`, `SubjectPublicKeyInfo`, and
 * `EXTENSION` are re-exported from `@wildboar/x500/AuthenticationFramework`.
 * `SubjectKeyIdentifier` is re-exported from
 * `@wildboar/x500/CertificateExtensions`. `IssuerAndSerialNumber` is
 * re-exported from `@wildboar/x500/EnhancedSecurity`.
 *
 * `id-icao`, `id-icao-mrtd`, and `id-icao-mrtd-security` are defined
 * with the same values in `LDSSecurityObjectV1` and `DeviationList`.
 * The package root exports them once. Both module subpaths still export them.
 *
 * The short integer name `v0` is omitted because it collides between
 * `CscaMasterListVersion`, `DeviationListVersion`,
 * `DocumentTypeListVersion`, and `LDSSecurityObjectVersion`. Use the
 * long forms. The short name `generic` is omitted because it collides
 * between `CertificateBodyField` and `MRZField`.
 */

export * from "./lib/modules/AuthenticationFramework/index.mjs";
export * from "./lib/modules/CertificateExtensions/index.mjs";
export {
    CscaMasterList,
    _root_component_type_list_1_spec_for_CscaMasterList,
    _root_component_type_list_2_spec_for_CscaMasterList,
    _extension_additions_list_spec_for_CscaMasterList,
    _decode_CscaMasterList,
    _encode_CscaMasterList,
    type CscaMasterListVersion,
    CscaMasterListVersion_v0,
    _decode_CscaMasterListVersion,
    _encode_CscaMasterListVersion,
    id_icao_cscaMasterList,
    id_icao_cscaMasterListSigningKey,
} from "./lib/modules/CscaMasterList/index.mjs";
export {
    type CertField,
    _decode_CertField,
    _encode_CertField,
    type CertificateBodyField,
    CertificateBodyField_generic,
    CertificateBodyField_version,
    version,
    CertificateBodyField_serialNumber,
    serialNumber,
    CertificateBodyField_signature,
    signature,
    CertificateBodyField_issuer,
    issuer,
    CertificateBodyField_validity,
    validity,
    CertificateBodyField_subject,
    subject,
    CertificateBodyField_subjectPublicKeyInfo,
    subjectPublicKeyInfo,
    CertificateBodyField_issuerUniqueID,
    issuerUniqueID,
    CertificateBodyField_subjectUniqueID,
    subjectUniqueID,
    _decode_CertificateBodyField,
    _encode_CertificateBodyField,
    type Datagroup,
    Datagroup_dg1,
    dg1,
    Datagroup_dg2,
    dg2,
    Datagroup_dg3,
    dg3,
    Datagroup_dg4,
    dg4,
    Datagroup_dg5,
    dg5,
    Datagroup_dg6,
    dg6,
    Datagroup_dg7,
    dg7,
    Datagroup_dg8,
    dg8,
    Datagroup_dg9,
    dg9,
    Datagroup_dg10,
    dg10,
    Datagroup_dg11,
    dg11,
    Datagroup_dg12,
    dg12,
    Datagroup_dg13,
    dg13,
    Datagroup_dg14,
    dg14,
    Datagroup_dg15,
    dg15,
    Datagroup_dg16,
    dg16,
    Datagroup_sod,
    sod,
    Datagroup_com,
    com,
    _decode_Datagroup,
    _encode_Datagroup,
    Deviation,
    _root_component_type_list_1_spec_for_Deviation,
    _root_component_type_list_2_spec_for_Deviation,
    _extension_additions_list_spec_for_Deviation,
    _decode_Deviation,
    _encode_Deviation,
    DeviationDescription,
    _root_component_type_list_1_spec_for_DeviationDescription,
    _root_component_type_list_2_spec_for_DeviationDescription,
    _extension_additions_list_spec_for_DeviationDescription,
    _decode_DeviationDescription,
    _encode_DeviationDescription,
    DeviationDocuments,
    _root_component_type_list_1_spec_for_DeviationDocuments,
    _root_component_type_list_2_spec_for_DeviationDocuments,
    _extension_additions_list_spec_for_DeviationDocuments,
    _decode_DeviationDocuments,
    _encode_DeviationDocuments,
    DeviationList,
    _root_component_type_list_1_spec_for_DeviationList,
    _root_component_type_list_2_spec_for_DeviationList,
    _extension_additions_list_spec_for_DeviationList,
    _decode_DeviationList,
    _encode_DeviationList,
    type DeviationListVersion,
    DeviationListVersion_v0,
    _decode_DeviationListVersion,
    _encode_DeviationListVersion,
    type Digest,
    _decode_Digest,
    _encode_Digest,
    type DocumentSignerIdentifier,
    _decode_DocumentSignerIdentifier,
    _encode_DocumentSignerIdentifier,
    IssuancePeriod,
    _root_component_type_list_1_spec_for_IssuancePeriod,
    _root_component_type_list_2_spec_for_IssuancePeriod,
    _extension_additions_list_spec_for_IssuancePeriod,
    _decode_IssuancePeriod,
    _encode_IssuancePeriod,
    type MRZField,
    MRZField_generic,
    MRZField_documentCode,
    documentCode,
    MRZField_issuingState,
    issuingState,
    MRZField_personName,
    personName,
    MRZField_documentNumber,
    documentNumber,
    MRZField_nationality,
    nationality,
    MRZField_dateOfBirth,
    dateOfBirth,
    MRZField_sex,
    sex,
    MRZField_dateOfExpiry,
    dateOfExpiry,
    MRZField_optionalData,
    optionalData,
    _decode_MRZField,
    _encode_MRZField,
    id_Deviation_CertOrKey_AAKeyCompromised,
    id_Deviation_CertOrKey_CSCAEncoding,
    id_Deviation_CertOrKey_DSEncoding,
    id_Deviation_CertOrKey_DSSignature,
    id_Deviation_CertOrKey,
    id_Deviation_Chip,
    id_Deviation_LDS_COMInconsistent,
    id_Deviation_LDS_DGHashWrong,
    id_Deviation_LDS_DGMalformed,
    id_Deviation_LDS_SODSignatureWrong,
    id_Deviation_LDS,
    id_Deviation_MRZ_WrongCheckDigit,
    id_Deviation_MRZ_WrongData,
    id_Deviation_MRZ,
    id_Deviation_NationalUse,
    id_icao_DeviationList,
    id_icao_DeviationListSigningKey,
} from "./lib/modules/DeviationList/index.mjs";
export * from "./lib/modules/Doc-9303-Part-11-Module/index.mjs";
export {
    type DocumentType,
    _decode_DocumentType,
    _encode_DocumentType,
    DocumentTypeListSyntax,
    _root_component_type_list_1_spec_for_DocumentTypeListSyntax,
    _root_component_type_list_2_spec_for_DocumentTypeListSyntax,
    _extension_additions_list_spec_for_DocumentTypeListSyntax,
    _decode_DocumentTypeListSyntax,
    _encode_DocumentTypeListSyntax,
    type DocumentTypeListVersion,
    DocumentTypeListVersion_v0,
    _decode_DocumentTypeListVersion,
    _encode_DocumentTypeListVersion,
    documentTypeList,
    id_icao_bSigner,
    id_icao_lds2Signer,
    id_icao_mrtd_security_extensions_documentTypeList,
    id_icao_mrtd_security_extensions_nameChange,
    id_icao_mrtd_security_extensions,
    id_icao_mrtd_security_lds2,
    id_icao_mrtd_security_vds,
    id_icao_tsSigner,
    id_icao_vSigner,
    id_icao_vdsSigner,
    nameChange,
} from "./lib/modules/Doc-9303-Part-12-Module/index.mjs";
export * from "./lib/modules/EnhancedSecurity/index.mjs";
export {
    DataGroupHash,
    _root_component_type_list_1_spec_for_DataGroupHash,
    _root_component_type_list_2_spec_for_DataGroupHash,
    _extension_additions_list_spec_for_DataGroupHash,
    _decode_DataGroupHash,
    _encode_DataGroupHash,
    type DataGroupNumber,
    DataGroupNumber_dataGroup1,
    dataGroup1,
    DataGroupNumber_dataGroup2,
    dataGroup2,
    DataGroupNumber_dataGroup3,
    dataGroup3,
    DataGroupNumber_dataGroup4,
    dataGroup4,
    DataGroupNumber_dataGroup5,
    dataGroup5,
    DataGroupNumber_dataGroup6,
    dataGroup6,
    DataGroupNumber_dataGroup7,
    dataGroup7,
    DataGroupNumber_dataGroup8,
    dataGroup8,
    DataGroupNumber_dataGroup9,
    dataGroup9,
    DataGroupNumber_dataGroup10,
    dataGroup10,
    DataGroupNumber_dataGroup11,
    dataGroup11,
    DataGroupNumber_dataGroup12,
    dataGroup12,
    DataGroupNumber_dataGroup13,
    dataGroup13,
    DataGroupNumber_dataGroup14,
    dataGroup14,
    DataGroupNumber_dataGroup15,
    dataGroup15,
    DataGroupNumber_dataGroup16,
    dataGroup16,
    _decode_DataGroupNumber,
    _encode_DataGroupNumber,
    type DigestAlgorithmIdentifier,
    _decode_DigestAlgorithmIdentifier,
    _encode_DigestAlgorithmIdentifier,
    LDSSecurityObject,
    _root_component_type_list_1_spec_for_LDSSecurityObject,
    _root_component_type_list_2_spec_for_LDSSecurityObject,
    _extension_additions_list_spec_for_LDSSecurityObject,
    _decode_LDSSecurityObject,
    _encode_LDSSecurityObject,
    type LDSSecurityObjectVersion,
    LDSSecurityObjectVersion_v0,
    LDSSecurityObjectVersion_v1,
    v1,
    _decode_LDSSecurityObjectVersion,
    _encode_LDSSecurityObjectVersion,
    LDSVersionInfo,
    _root_component_type_list_1_spec_for_LDSVersionInfo,
    _root_component_type_list_2_spec_for_LDSVersionInfo,
    _extension_additions_list_spec_for_LDSVersionInfo,
    _decode_LDSVersionInfo,
    _encode_LDSVersionInfo,
    id_icao_mrtd_security_ldsSecurityObject,
    id_icao_mrtd_security,
    id_icao_mrtd,
    id_icao,
    ub_DataGroups,
} from "./lib/modules/LDSSecurityObjectV1/index.mjs";
