/* eslint-disable */
import {
    ASN1Element as _Element,
    ASN1TagClass as _TagClass,
    ASN1Construction as _Construction,
    ASN1UniversalType as _UniversalType,
    ObjectIdentifier as _OID,
    External as _External,
    EmbeddedPDV as _PDV,
    ASN1ConstructionError as _ConstructionError,
} from '@wildboar/asn1';
import { ID, _decode_ID, _encode_ID } from '../MHSObjectIdentifiers/ID.ta.mjs';
import { id_att } from '../MSObjectIdentifiers/id-att.va.mjs';
/**
 * @summary id_att_delivered_EITs
 * @description
 *
 * OBJECT IDENTIFIER `id_att_delivered_EITs`. This general-attribute, which is
 * multi-valued, identifies the encoded-information-types in the content of a message as
 * delivered. It is generated by the MS, and is derived from the
 * original-encoded-information-types and the converted- encoded-information-types
 * arguments of the Message-delivery abstract-operation. See ITU-T X.413 (1999),
 * §11.2.25.
 *
 * ### ASN.1 Definition:
 *
 * ```asn1
 * id-att-delivered-EITs ID ::= {id-att  12}
 * ```
 *
 * @constant
 */
export const id_att_delivered_EITs: ID = _OID.fromParts([12], id_att);

/* eslint-enable */
