/* eslint-disable */
import {
    ASN1Element as _Element,
    ASN1TagClass as _TagClass,
    ASN1Construction as _Construction,
    ASN1UniversalType as _UniversalType,
    ObjectIdentifier as _OID,
    External as _External,
    EmbeddedPDV as _PDV,
    ASN1ConstructionError as _ConstructionError,
} from '@wildboar/asn1';
import { ID, _decode_ID, _encode_ID } from '../MHSObjectIdentifiers/ID.ta.mjs';
import { id_att } from '../MSObjectIdentifiers/id-att.va.mjs';
/**
 * @summary id_att_content_identifier
 * @description
 *
 * OBJECT IDENTIFIER `id_att_content_identifier`. This general-attribute contains the
 * content-identifier argument of the Message-submission, Probe-submission, Message-
 * delivery, and Report-delivery abstract-operations. It may be generated by the
 * originator. See ITU-T X.413 (1999), §11.2.14.
 *
 * ### ASN.1 Definition:
 *
 * ```asn1
 * id-att-content-identifier ID ::= {id-att  4}
 * ```
 *
 * @constant
 */
export const id_att_content_identifier: ID = _OID.fromParts([4], id_att);

/* eslint-enable */
