/* eslint-disable */
import {
    ASN1Element as _Element,
    ASN1TagClass as _TagClass,
    ASN1Construction as _Construction,
    ASN1UniversalType as _UniversalType,
    ObjectIdentifier as _OID,
    External as _External,
    EmbeddedPDV as _PDV,
    ASN1ConstructionError as _ConstructionError,
} from '@wildboar/asn1';
import { ID, _decode_ID, _encode_ID } from '../MHSObjectIdentifiers/ID.ta.mjs';
import { id_att } from '../MSObjectIdentifiers/id-att.va.mjs';
/**
 * @summary id_att_multiple_originator_certificates
 * @description
 *
 * This general-attribute contains the multiple-originator-certificates argument of the
 * Message-submission and Message- delivery abstract-operations. It is generated by a
 * trusted source (e.g. See ITU-T X.413 (1999), §11.2.47.
 *
 * ### ASN.1 Definition:
 *
 * ```asn1
 * id-att-multiple-originator-certificates ID ::= {id-att  81}
 * ```
 *
 * @constant
 */
export const id_att_multiple_originator_certificates: ID = _OID.fromParts(
    [81],
    id_att
);

/* eslint-enable */
