/* eslint-disable */
import {
    ASN1Element as _Element,
    ASN1TagClass as _TagClass,
    ASN1Construction as _Construction,
    ASN1UniversalType as _UniversalType,
    ObjectIdentifier as _OID,
    External as _External,
    EmbeddedPDV as _PDV,
    ASN1ConstructionError as _ConstructionError,
} from '@wildboar/asn1';
import { ID, _decode_ID, _encode_ID } from '../MHSObjectIdentifiers/ID.ta.mjs';
import { id_att } from '../MSObjectIdentifiers/id-att.va.mjs';
/**
 * @summary id_att_content_integrity_check
 * @description
 *
 * OBJECT IDENTIFIER `id_att_content_integrity_check`. This general-attribute contains
 * the content-integrity-check argument of the Message-delivery abstract-operation; it
 * provides the MS-user with a means of verifying that the content of a delivered-message
 * has not been modified. It may be generated by the originator of the message. See ITU-T
 * X.413 (1999), §11.2.15.
 *
 * ### ASN.1 Definition:
 *
 * ```asn1
 * id-att-content-integrity-check ID ::= {id-att  5}
 * ```
 *
 * @constant
 */
export const id_att_content_integrity_check: ID = _OID.fromParts([5], id_att);

/* eslint-enable */
