/* eslint-disable */
import {
    ASN1Element as _Element,
    ASN1TagClass as _TagClass,
    ASN1Construction as _Construction,
    ASN1UniversalType as _UniversalType,
    ObjectIdentifier as _OID,
    External as _External,
    EmbeddedPDV as _PDV,
    ASN1ConstructionError as _ConstructionError,
} from '@wildboar/asn1';
import { ID, _decode_ID, _encode_ID } from '../MHSObjectIdentifiers/ID.ta.mjs';
import { id_att } from '../MSObjectIdentifiers/id-att.va.mjs';
/**
 * @summary id_att_creation_time
 * @description
 *
 * OBJECT IDENTIFIER `id_att_creation_time`. This general-attribute indicates the time at
 * which an entry was created in the MS. It is generated by the MS. See ITU-T X.413
 * (1999), §11.2.21.
 *
 * ### ASN.1 Definition:
 *
 * ```asn1
 * id-att-creation-time ID ::= {id-att  11}
 * ```
 *
 * @constant
 */
export const id_att_creation_time: ID = _OID.fromParts([11], id_att);

/* eslint-enable */
