/* eslint-disable */
import {
    ASN1Element as _Element,
    ASN1TagClass as _TagClass,
    ASN1Construction as _Construction,
    ASN1UniversalType as _UniversalType,
    ObjectIdentifier as _OID,
    External as _External,
    EmbeddedPDV as _PDV,
    ASN1ConstructionError as _ConstructionError,
} from '@wildboar/asn1';
import { ID, _decode_ID, _encode_ID } from '../MHSObjectIdentifiers/ID.ta.mjs';
import { id_att } from '../MSObjectIdentifiers/id-att.va.mjs';
/**
 * @summary id_att_signature_verification_status
 * @description
 *
 * This general-attribute reports the outcome of verification by the MS that the content of
 * a delivered message has not been modified in the MTS, if the MS has the capability to
 * perform such verification and a signature of the content was present in
 * content-integrity-check, message-origin-authentication-check or message-token. It is
 * generated by the MS. See ITU-T X.413 (1999), §11.2.77.
 *
 * ### ASN.1 Definition:
 *
 * ```asn1
 * id-att-signature-verification-status ID ::= {id-att  79}
 * ```
 *
 * @constant
 */
export const id_att_signature_verification_status: ID = _OID.fromParts([79], id_att);

/* eslint-enable */
