/* eslint-disable */
import {
    ASN1Element as _Element,
    ASN1TagClass as _TagClass,
    ASN1Construction as _Construction,
    ASN1UniversalType as _UniversalType,
    ObjectIdentifier as _OID,
    External as _External,
    EmbeddedPDV as _PDV,
    ASN1ConstructionError as _ConstructionError,
} from '@wildboar/asn1';
import { ID, _decode_ID, _encode_ID } from '../MHSObjectIdentifiers/ID.ta.mjs';
import { id_att } from '../MSObjectIdentifiers/id-att.va.mjs';
/**
 * @summary id_att_proof_of_delivery_request
 * @description
 *
 * OBJECT IDENTIFIER `id_att_proof_of_delivery_request`. This general-attribute contains
 * the proof-of-delivery-request argument of the Message-delivery abstract-operation. It
 * may be generated by the originator of the message. See ITU-T X.413 (1999), §11.2.64.
 *
 * ### ASN.1 Definition:
 *
 * ```asn1
 * id-att-proof-of-delivery-request ID ::= {id-att  32}
 * ```
 *
 * @constant
 */
export const id_att_proof_of_delivery_request: ID = _OID.fromParts([32], id_att);

/* eslint-enable */
