/* eslint-disable */
import {
    ASN1Element as _Element,
    ASN1TagClass as _TagClass,
    ASN1Construction as _Construction,
    ASN1UniversalType as _UniversalType,
    ObjectIdentifier as _OID,
    External as _External,
    EmbeddedPDV as _PDV,
    ASN1ConstructionError as _ConstructionError,
} from '@wildboar/asn1';
import { ID, _decode_ID, _encode_ID } from '../MHSObjectIdentifiers/ID.ta.mjs';
import { id_att } from '../MSObjectIdentifiers/id-att.va.mjs';
/**
 * @summary id_att_recipient_names
 * @description
 *
 * OBJECT IDENTIFIER `id_att_recipient_names`. This general-attribute, which is
 * multi-valued, contains the recipient-name components specified in the per-recipient-
 * fields components of the Message-submission-envelope and Probe-submission-envelope. It
 * is generated by the MS. See ITU-T X.413 (1999), §11.2.67.
 *
 * ### ASN.1 Definition:
 *
 * ```asn1
 * id-att-recipient-names ID ::= {id-att  71}
 * ```
 *
 * @constant
 */
export const id_att_recipient_names: ID = _OID.fromParts([71], id_att);

/* eslint-enable */
