/* eslint-disable */
import {
    ASN1Element as _Element,
    ASN1TagClass as _TagClass,
    ASN1Construction as _Construction,
    ASN1UniversalType as _UniversalType,
    ObjectIdentifier as _OID,
    External as _External,
    EmbeddedPDV as _PDV,
    ASN1ConstructionError as _ConstructionError,
} from '@wildboar/asn1';
import { ID, _decode_ID, _encode_ID } from '../MHSObjectIdentifiers/ID.ta.mjs';
import { id_att } from '../MSObjectIdentifiers/id-att.va.mjs';
/**
 * @summary id_att_ac_uncorrelated_report_list
 * @description
 *
 * This general-attribute, which is multi-valued, identifies each of the
 * per-recipient-report-delivery-fields which have been correlated with a submitted message
 * or probe but which have not been correlated with any of its originally specified
 * recipients. It is generated by the MS. See ITU-T X.413 (1999), §11.2.4.
 *
 * ### ASN.1 Definition:
 *
 * ```asn1
 * id-att-ac-uncorrelated-report-list ID ::= {id-att  44}
 * ```
 *
 * @constant
 */
export const id_att_ac_uncorrelated_report_list: ID = _OID.fromParts([44], id_att);

/* eslint-enable */
