/**
 * @description
 *
 * ASN.1 module `CAP-operationcodes`.
 */
export * from "./opcode-activityTest.va.mjs";
export * from "./opcode-activityTestGPRS.va.mjs";
export * from "./opcode-applyCharging.va.mjs";
export * from "./opcode-applyChargingGPRS.va.mjs";
export * from "./opcode-applyChargingReport.va.mjs";
export * from "./opcode-applyChargingReportGPRS.va.mjs";
export * from "./opcode-assistRequestInstructions.va.mjs";
export * from "./opcode-callGap.va.mjs";
export * from "./opcode-callInformationReport.va.mjs";
export * from "./opcode-callInformationRequest.va.mjs";
export * from "./opcode-cancel.va.mjs";
export * from "./opcode-cancelGPRS.va.mjs";
export * from "./opcode-collectInformation.va.mjs";
export * from "./opcode-connect.va.mjs";
export * from "./opcode-connectGPRS.va.mjs";
export * from "./opcode-connectSMS.va.mjs";
export * from "./opcode-connectToResource.va.mjs";
export * from "./opcode-continue.va.mjs";
export * from "./opcode-continueGPRS.va.mjs";
export * from "./opcode-continueSMS.va.mjs";
export * from "./opcode-continueWithArgument.va.mjs";
export * from "./opcode-dFCWithArgument.va.mjs";
export * from "./opcode-disconnectForwardConnection.va.mjs";
export * from "./opcode-disconnectLeg.va.mjs";
export * from "./opcode-entityReleased.va.mjs";
export * from "./opcode-entityReleasedGPRS.va.mjs";
export * from "./opcode-establishTemporaryConnection.va.mjs";
export * from "./opcode-eventReportBCSM.va.mjs";
export * from "./opcode-eventReportGPRS.va.mjs";
export * from "./opcode-eventReportSMS.va.mjs";
export * from "./opcode-furnishChargingInformation.va.mjs";
export * from "./opcode-furnishChargingInformationGPRS.va.mjs";
export * from "./opcode-furnishChargingInformationSMS.va.mjs";
export * from "./opcode-initialDP.va.mjs";
export * from "./opcode-initialDPGPRS.va.mjs";
export * from "./opcode-initialDPSMS.va.mjs";
export * from "./opcode-initiateCallAttempt.va.mjs";
export * from "./opcode-moveLeg.va.mjs";
export * from "./opcode-playAnnouncement.va.mjs";
export * from "./opcode-playTone.va.mjs";
export * from "./opcode-promptAndCollectUserInformation.va.mjs";
export * from "./opcode-releaseCall.va.mjs";
export * from "./opcode-releaseGPRS.va.mjs";
export * from "./opcode-releaseSMS.va.mjs";
export * from "./opcode-requestReportBCSMEvent.va.mjs";
export * from "./opcode-requestReportGPRSEvent.va.mjs";
export * from "./opcode-requestReportSMSEvent.va.mjs";
export * from "./opcode-resetTimer.va.mjs";
export * from "./opcode-resetTimerGPRS.va.mjs";
export * from "./opcode-resetTimerSMS.va.mjs";
export * from "./opcode-sendChargingInformation.va.mjs";
export * from "./opcode-sendChargingInformationGPRS.va.mjs";
export * from "./opcode-specializedResourceReport.va.mjs";
export * from "./opcode-splitLeg.va.mjs";
