/* eslint-disable */
import {
    ASN1Element as _Element,
    ASN1TagClass as _TagClass,
    ASN1Construction as _Construction,
    ASN1UniversalType as _UniversalType,
    ObjectIdentifier as _OID,
    External as _External,
    EmbeddedPDV as _PDV,
    ASN1ConstructionError as _ConstructionError,
} from '@wildboar/asn1';
import { ID, _decode_ID, _encode_ID } from '../MhsAcctObjectIdentifiers/ID.ta.mjs';
import { id_attribute } from '../MhsAcctObjectIdentifiers/id-attribute.va.mjs';
/**
 * @summary id_attribute_messageSecurityLabel
 * @description
 *
 * This argument associates a security-label with the message (or probe). It may be
 * generated by the originator of the message (or probe), in line with the security-policy
 * in force. See ITU-T X.411 (1999), §8.2.1.1.1.30.
 *
 * ### ASN.1 Definition:
 *
 * ```asn1
 * id-attribute-messageSecurityLabel ID ::= {id-attribute  65}
 * ```
 *
 * @constant
 */
export const id_attribute_messageSecurityLabel: ID = _OID.fromParts(
    [65],
    id_attribute
);

/* eslint-enable */
