/* eslint-disable */
import {
    ASN1Element as _Element,
    ASN1TagClass as _TagClass,
    ASN1Construction as _Construction,
    ASN1UniversalType as _UniversalType,
    ObjectIdentifier as _OID,
    External as _External,
    EmbeddedPDV as _PDV,
    ASN1ConstructionError as _ConstructionError,
} from '@wildboar/asn1';
import { ID, _decode_ID, _encode_ID } from '../MhsAcctObjectIdentifiers/ID.ta.mjs';
import { id_attribute } from '../MhsAcctObjectIdentifiers/id-attribute.va.mjs';
/**
 * @summary id_attribute_reportIdentifier
 * @description
 *
 * This argument contains an MTS-identifier that distinguishes the report from all other
 * messages, probes and reports within the MTS. It shall be generated by the
 * originating-MTA of the report. See ITU-T X.411 (1999), §12.2.1.3.1.1.
 *
 * ### ASN.1 Definition:
 *
 * ```asn1
 * id-attribute-reportIdentifier ID ::= {id-attribute  103}
 * ```
 *
 * @constant
 */
export const id_attribute_reportIdentifier: ID = _OID.fromParts([103], id_attribute);

/* eslint-enable */
