/* eslint-disable */
import {
    ASN1Element as _Element,
    ASN1TagClass as _TagClass,
    ASN1Construction as _Construction,
    ASN1UniversalType as _UniversalType,
    ObjectIdentifier as _OID,
    External as _External,
    EmbeddedPDV as _PDV,
    ASN1ConstructionError as _ConstructionError,
} from '@wildboar/asn1';
import { ID, _decode_ID, _encode_ID } from '../MhsAcctObjectIdentifiers/ID.ta.mjs';
import { id_attribute } from '../MhsAcctObjectIdentifiers/id-attribute.va.mjs';
/**
 * @summary id_attribute_reportingMtaCertificate
 * @description
 *
 * This argument contains the certificate of the MTA that generated the report. It shall be
 * generated by a trusted source (e.g., a certification-authority), and may be supplied by
 * the reporting-MTA if a report-origin-authentication-check is supplied. See ITU-T X.411
 * (1999), §8.3.1.2.1.13.
 *
 * ### ASN.1 Definition:
 *
 * ```asn1
 * id-attribute-reportingMtaCertificate ID ::= {id-attribute  104}
 * ```
 *
 * @constant
 */
export const id_attribute_reportingMtaCertificate: ID = _OID.fromParts(
    [104],
    id_attribute
);

/* eslint-enable */
