/* eslint-disable */
import {
    ASN1Element as _Element,
    ASN1TagClass as _TagClass,
    ASN1Construction as _Construction,
    ASN1UniversalType as _UniversalType,
    ObjectIdentifier as _OID,
    External as _External,
    EmbeddedPDV as _PDV,
    ASN1ConstructionError as _ConstructionError,
} from '@wildboar/asn1';
import { ID, _decode_ID, _encode_ID } from '../MhsAcctObjectIdentifiers/ID.ta.mjs';
import { id_attribute } from '../MhsAcctObjectIdentifiers/id-attribute.va.mjs';
/**
 * @summary id_attribute_originatingMTACertificate
 * @description
 *
 * This result contains the certificate of the MTA to which the message has been submitted
 * (the originating-MTA). It shall be generated by a trusted source (e.g., a
 * certification-authority), and may be supplied by the originating-MTA, if the originator
 * of the message requested proof-of-submission (see 8.2.1.1.1.31) and an
 * asymmetric-encryption-algorithm is used to compute the proof-of-submission. See ITU-T
 * X.411 (1999), §8.2.1.1.2.3.
 *
 * ### ASN.1 Definition:
 *
 * ```asn1
 * id-attribute-originatingMTACertificate ID ::= {id-attribute  82}
 * ```
 *
 * @constant
 */
export const id_attribute_originatingMTACertificate: ID = _OID.fromParts(
    [82],
    id_attribute
);

/* eslint-enable */
