/* eslint-disable */
import {
    ASN1Element as _Element,
    ASN1TagClass as _TagClass,
    ASN1Construction as _Construction,
    ASN1UniversalType as _UniversalType,
    ObjectIdentifier as _OID,
    External as _External,
    EmbeddedPDV as _PDV,
    ASN1ConstructionError as _ConstructionError,
} from '@wildboar/asn1';
import { ID, _decode_ID, _encode_ID } from '../MhsAcctObjectIdentifiers/ID.ta.mjs';
import { id_attribute } from '../MhsAcctObjectIdentifiers/id-attribute.va.mjs';
/**
 * @summary id_attribute_permissibleSecurityContext
 * @description
 *
 * OBJECT IDENTIFIER `id_attribute_permissibleSecurityContext`. This argument identifies
 * the security-context that the initiator of the association proposes to operate at. It
 * may be generated by the initiator of the association. See ITU-T X.411 (1999),
 * §8.1.1.1.1.3.
 *
 * ### ASN.1 Definition:
 *
 * ```asn1
 * id-attribute-permissibleSecurityContext ID ::= {id-attribute  85}
 * ```
 *
 * @constant
 */
export const id_attribute_permissibleSecurityContext: ID = _OID.fromParts(
    [85],
    id_attribute
);

/* eslint-enable */
