/* eslint-disable */
import {
    ASN1Element as _Element,
    ASN1TagClass as _TagClass,
    ASN1Construction as _Construction,
    ASN1UniversalType as _UniversalType,
    ObjectIdentifier as _OID,
    External as _External,
    EmbeddedPDV as _PDV,
    ASN1ConstructionError as _ConstructionError,
} from '@wildboar/asn1';
import { ID, _decode_ID, _encode_ID } from '../MhsAcctObjectIdentifiers/ID.ta.mjs';
import { id_attribute } from '../MhsAcctObjectIdentifiers/id-attribute.va.mjs';
/**
 * @summary id_attribute_oldCredentials
 * @description
 *
 * OBJECT IDENTIFIER `id_attribute_oldCredentials`. This argument contains the current
 * (old) credentials of the invoker of the abstract-operation, held by the performer of
 * the abstract-operation. It shall be generated by the invoker of the
 * abstract-operation. See ITU-T X.411 (1999), §8.4.1.2.1.1.
 *
 * ### ASN.1 Definition:
 *
 * ```asn1
 * id-attribute-oldCredentials ID ::= {id-attribute  76}
 * ```
 *
 * @constant
 */
export const id_attribute_oldCredentials: ID = _OID.fromParts([76], id_attribute);

/* eslint-enable */
