/* eslint-disable */
import {
    ASN1Element as _Element,
    ASN1TagClass as _TagClass,
    ASN1Construction as _Construction,
    ASN1UniversalType as _UniversalType,
    ObjectIdentifier as _OID,
    External as _External,
    EmbeddedPDV as _PDV,
    ASN1ConstructionError as _ConstructionError,
} from '@wildboar/asn1';
import { ID, _decode_ID, _encode_ID } from '../MhsAcctObjectIdentifiers/ID.ta.mjs';
import { id_attribute } from '../MhsAcctObjectIdentifiers/id-attribute.va.mjs';
/**
 * @summary id_attribute_subjectIdentifier
 * @description
 *
 * OBJECT IDENTIFIER `id_attribute_subjectIdentifier`. This argument contains the
 * message-identifier (or probe-identifier) of the subject (an MTS-identifier). It shall
 * be generated by the originating-MTA of the subject. See ITU-T X.411 (1999),
 * §12.2.1.3.1.3.
 *
 * ### ASN.1 Definition:
 *
 * ```asn1
 * id-attribute-subjectIdentifier ID ::= {id-attribute  121}
 * ```
 *
 * @constant
 */
export const id_attribute_subjectIdentifier: ID = _OID.fromParts([121], id_attribute);

/* eslint-enable */
