/* eslint-disable */
import {
    ASN1Element as _Element,
    ASN1TagClass as _TagClass,
    ASN1Construction as _Construction,
    ASN1UniversalType as _UniversalType,
    ObjectIdentifier as _OID,
    External as _External,
    EmbeddedPDV as _PDV,
    ASN1ConstructionError as _ConstructionError,
} from '@wildboar/asn1';
import { ID, _decode_ID, _encode_ID } from '../MhsAcctObjectIdentifiers/ID.ta.mjs';
import { id_attribute } from '../MhsAcctObjectIdentifiers/id-attribute.va.mjs';
/**
 * @summary id_attribute_recipientCertificate
 * @description
 *
 * This argument contains a certificate of the recipient of the message and optionally its
 * certification path. The certificate shall be generated by a trusted source (e.g. See
 * ITU-T X.411 (1999), §8.2.1.1.1.42.
 *
 * ### ASN.1 Definition:
 *
 * ```asn1
 * id-attribute-recipientCertificate ID ::= {id-attribute  98}
 * ```
 *
 * @constant
 */
export const id_attribute_recipientCertificate: ID = _OID.fromParts(
    [98],
    id_attribute
);

/* eslint-enable */
