/* eslint-disable */
import {
    ASN1Element as _Element,
    ASN1TagClass as _TagClass,
    ASN1Construction as _Construction,
    ASN1UniversalType as _UniversalType,
    ObjectIdentifier as _OID,
    External as _External,
    EmbeddedPDV as _PDV,
    ASN1ConstructionError as _ConstructionError,
} from '@wildboar/asn1';
import { ID, _decode_ID, _encode_ID } from '../MhsAcctObjectIdentifiers/ID.ta.mjs';
import { mhs_management } from '../MhsAcctObjectIdentifiers/mhs-management.va.mjs';
/**
 * @summary id_information
 * @description
 *
 * OBJECT IDENTIFIER `id_information`. This argument may contain information supplied by
 * the originator of the report, as a printable string. It may be generated by the
 * originating-MTA of the report or an associated access-unit. See ITU-T X.411 (1999),
 * §8.3.1.2.1.7.
 *
 * ### ASN.1 Definition:
 *
 * ```asn1
 * id-information ID ::= {mhs-management  2}
 * ```
 *
 * @constant
 */
export const id_information: ID = _OID.fromParts([2], mhs_management);

/* eslint-enable */
