/* eslint-disable */
import {
    ASN1Element as _Element,
    ASN1TagClass as _TagClass,
    ASN1Construction as _Construction,
    ASN1UniversalType as _UniversalType,
    ObjectIdentifier as _OID,
    External as _External,
    EmbeddedPDV as _PDV,
    ASN1ConstructionError as _ConstructionError,
} from '@wildboar/asn1';
import { ID, _decode_ID, _encode_ID } from '../MhsAcctObjectIdentifiers/ID.ta.mjs';
import { id_accounting } from '../MhsAcctObjectIdentifiers/id-accounting.va.mjs';
/**
 * @summary id_notification
 * @description
 *
 * OBJECT IDENTIFIER `id_notification`. This argument indicates that the content is a
 * notification, and indicates that it is one of three types of notification (type-1,
 * type-2 or type-3); the use of these values is defined in the relevant content
 * specification. It may be generated by the originator of the message, but shall be
 * generated only if the content is a notification as defined in the relevant content
 * specification. See ITU-T X.411 (1999), §8.2.1.1.1.38.
 *
 * ### ASN.1 Definition:
 *
 * ```asn1
 * id-notification ID ::= {id-accounting  4}
 * ```
 *
 * @constant
 */
export const id_notification: ID = _OID.fromParts([4], id_accounting);

/* eslint-enable */
