/* eslint-disable */
import {
    ASN1Element as _Element,
    ASN1TagClass as _TagClass,
    ASN1Construction as _Construction,
    ASN1UniversalType as _UniversalType,
    ObjectIdentifier as _OID,
    External as _External,
    EmbeddedPDV as _PDV,
    ASN1ConstructionError as _ConstructionError,
} from '@wildboar/asn1';
import {
    SIGNATURE,
    _decode_SIGNATURE,
    _encode_SIGNATURE,
} from '@wildboar/x500/AuthenticationFramework';
export {
    SIGNATURE,
    _decode_SIGNATURE as _decode_BodyPartSignature,
    _encode_SIGNATURE as _encode_BodyPartSignature,
} from '@wildboar/x500/AuthenticationFramework';

/**
 * @summary BodyPartSignature
 * @description
 *
 * The-Body Part Signature Verification Status attribute reports the outcome of
 * verification by the IPMS-MS that body parts of a delivered IPM have not been modified in
 * the MTS, if the IPMS-MS has the capability to perform such verification and a signature
 * of the body part was present in the IPM. It is generated by the IPMS-MS. See ITU-T X.420
 * (1999), §19.6.1.5.
 *
 * ### ASN.1 Definition:
 *
 * ```asn1
 * BodyPartSignature  ::=
 *   SIGNATURE
 *     {SEQUENCE {signature-algorithm-identifier  AlgorithmIdentifier,
 *                body-part                       BodyPart,
 *                body-part-security-label        SecurityLabel OPTIONAL
 *     }}
 * ```
 */
export type BodyPartSignature = SIGNATURE; // DefinedType

/* eslint-enable */
