/* eslint-disable */
import {
    INTEGER,
    ASN1Element as _Element,
    ASN1TagClass as _TagClass,
    ASN1Construction as _Construction,
    ASN1UniversalType as _UniversalType,
    ObjectIdentifier as _OID,
    External as _External,
    EmbeddedPDV as _PDV,
    ASN1ConstructionError as _ConstructionError,
} from '@wildboar/asn1';

/**
 * @summary ub_bilateral_info
 * @description
 *
 * This argument contains information intended for MDs which the message will encounter as
 * it is transferred through the MTS. It may be generated by the originating-MD of the
 * message. See ITU-T X.411 (1999), §12.2.1.1.1.2.
 *
 * ### ASN.1 Definition:
 *
 * ```asn1
 * ub-bilateral-info INTEGER ::= 1024
 * ```
 *
 * @constant
 */
export const ub_bilateral_info: INTEGER = 1024;

/* eslint-enable */
