/* eslint-disable */
import {
    INTEGER,
    ASN1Element as _Element,
    ASN1TagClass as _TagClass,
    ASN1Construction as _Construction,
    ASN1UniversalType as _UniversalType,
    ObjectIdentifier as _OID,
    External as _External,
    EmbeddedPDV as _PDV,
    ASN1ConstructionError as _ConstructionError,
} from '@wildboar/asn1';

/**
 * @summary ub_content_types
 * @description
 *
 * ASN.1 upper-bound INTEGER `ub_content_types`. This result indicates the content-types
 * of any messages held by the MTS-user for submission to the MTS due to prevailing
 * controls. It may be generated by the MTS-user. See ITU-T X.411 (1999), §8.2.1.4.2.4.
 *
 * ### ASN.1 Definition:
 *
 * ```asn1
 * ub-content-types INTEGER ::= 1024
 * ```
 *
 * @constant
 */
export const ub_content_types: INTEGER = 1024;

/* eslint-enable */
