/* eslint-disable */
import {
    INTEGER,
    ASN1Element as _Element,
    ASN1TagClass as _TagClass,
    ASN1Construction as _Construction,
    ASN1UniversalType as _UniversalType,
    ObjectIdentifier as _OID,
    External as _External,
    EmbeddedPDV as _PDV,
    ASN1ConstructionError as _ConstructionError,
} from '@wildboar/asn1';

/**
 * @summary ub_content_length
 * @description
 *
 * This argument specifies the length, in octets, of the content of the subject-message. It
 * may be generated by the originator of the probe. See ITU-T X.411 (1999), §8.2.1.2.1.2.
 *
 * ### ASN.1 Definition:
 *
 * ```asn1
 * ub-content-length INTEGER ::= 2147483647
 * ```
 *
 * @constant
 */
export const ub_content_length: INTEGER = 2147483647;

/* eslint-enable */
