/* eslint-disable */
import {
    INTEGER,
    ASN1Element as _Element,
    ASN1TagClass as _TagClass,
    ASN1Construction as _Construction,
    ASN1UniversalType as _UniversalType,
    ObjectIdentifier as _OID,
    External as _External,
    EmbeddedPDV as _PDV,
    ASN1ConstructionError as _ConstructionError,
} from '@wildboar/asn1';

/**
 * @summary ub_certificates
 * @description
 *
 * This argument contains a certificate of the originator of the message, or the
 * directory-name of an entry in the Directory which contains a certificate of the
 * originator, or multiple certificates (or directory-names) where the certificates contain
 * different certification paths or are issued by different certification authorities or
 * have different purposes. Each certificate shall be generated by a trusted source (e.g.
 * See ITU-T X.411 (1999), §8.2.1.1.1.41.
 *
 * ### ASN.1 Definition:
 *
 * ```asn1
 * ub-certificates INTEGER ::= 64
 * ```
 *
 * @constant
 */
export const ub_certificates: INTEGER = 64;

/* eslint-enable */
