/* eslint-disable */
import {
    INTEGER,
    ASN1Element as _Element,
    ASN1TagClass as _TagClass,
    ASN1Construction as _Construction,
    ASN1UniversalType as _UniversalType,
    ObjectIdentifier as _OID,
    External as _External,
    EmbeddedPDV as _PDV,
    ASN1ConstructionError as _ConstructionError,
} from '@wildboar/asn1';

/**
 * @summary ub_encoded_information_types
 * @description
 *
 * ASN.1 upper-bound INTEGER `ub_encoded_information_types`. This argument identifies the
 * original encoded-information-types of the message content. It may be generated by the
 * originator of the message. See ITU-T X.411 (1999), §8.2.1.1.1.33.
 *
 * ### ASN.1 Definition:
 *
 * ```asn1
 * ub-encoded-information-types INTEGER ::= 1024
 * ```
 *
 * @constant
 */
export const ub_encoded_information_types: INTEGER = 1024;

/* eslint-enable */
