/* eslint-disable */
import {
    INTEGER,
    ASN1Element as _Element,
    ASN1TagClass as _TagClass,
    ASN1Construction as _Construction,
    ASN1UniversalType as _UniversalType,
    ObjectIdentifier as _OID,
    External as _External,
    EmbeddedPDV as _PDV,
    ASN1ConstructionError as _ConstructionError,
} from '@wildboar/asn1';

/**
 * @summary ub_recipients
 * @description
 *
 * ASN.1 upper-bound INTEGER `ub_recipients`. This argument indicates whether the
 * recipient-name of all recipients are to be indicated to each recipient MTS-user when
 * the message is delivered. It may be generated by the originator of the message. See
 * ITU-T X.411 (1999), §8.2.1.1.1.7.
 *
 * ### ASN.1 Definition:
 *
 * ```asn1
 * ub-recipients INTEGER ::= 32767
 * ```
 *
 * @constant
 */
export const ub_recipients: INTEGER = 32767;

/* eslint-enable */
