/* eslint-disable */
import {
    ASN1ConstructionError as _ConstructionError,
    ASN1Element as _Element,
    ASN1TagClass as _TagClass
} from "@wildboar/asn1";
import * as $ from "@wildboar/asn1/functional";
import { TransactionId, _decode_TransactionId, _encode_TransactionId } from "../RSPDefinitions/TransactionId.ta.mjs";
// export { TransactionId, _decode_TransactionId, _encode_TransactionId } from "../RSPDefinitions/TransactionId.ta.mjs";
import { CancelSessionReason, _decode_CancelSessionReason, _encode_CancelSessionReason } from "../RSPDefinitions/CancelSessionReason.ta.mjs";
// export { CancelSessionReason, CancelSessionReason_endUserRejection /* IMPORTED_LONG_NAMED_INTEGER */, endUserRejection /* IMPORTED_SHORT_NAMED_INTEGER */, CancelSessionReason_postponed /* IMPORTED_LONG_NAMED_INTEGER */, postponed /* IMPORTED_SHORT_NAMED_INTEGER */, CancelSessionReason_timeout /* IMPORTED_LONG_NAMED_INTEGER */, timeout /* IMPORTED_SHORT_NAMED_INTEGER */, CancelSessionReason_pprNotAllowed /* IMPORTED_LONG_NAMED_INTEGER */, pprNotAllowed /* IMPORTED_SHORT_NAMED_INTEGER */, CancelSessionReason_metadataMismatch /* IMPORTED_LONG_NAMED_INTEGER */, metadataMismatch /* IMPORTED_SHORT_NAMED_INTEGER */, CancelSessionReason_loadBppExecutionError /* IMPORTED_LONG_NAMED_INTEGER */, loadBppExecutionError /* IMPORTED_SHORT_NAMED_INTEGER */, CancelSessionReason_undefinedReason /* IMPORTED_LONG_NAMED_INTEGER */, undefinedReason /* IMPORTED_SHORT_NAMED_INTEGER */, _decode_CancelSessionReason, _encode_CancelSessionReason } from "../RSPDefinitions/CancelSessionReason.ta.mjs";


/**
 * @summary CancelSessionRequest
 * @description
 * 
 * ### ASN.1 Definition:
 * 
 * ```asn1
 * CancelSessionRequest ::= [65] SEQUENCE { -- Tag 'BF41'
 *     transactionId TransactionId,     -- The TransactionID generated by the RSP Server
 *     reason CancelSessionReason
 * }
 * ```
 * 
 * @class
 */
export
class CancelSessionRequest {
    constructor (
        /**
         * @summary `transactionId`.
         * @public
         * @readonly
         */
        readonly transactionId: TransactionId,
        /**
         * @summary `reason`.
         * @public
         * @readonly
         */
        readonly reason: CancelSessionReason
    ) {}

    /**
     * @summary Restructures an object into a CancelSessionRequest
     * @description
     * 
     * This takes an `object` and converts it to a `CancelSessionRequest`.
     * 
     * @public
     * @static
     * @method
     * @param {Object} _o An object having all of the keys and values of a `CancelSessionRequest`.
     * @returns {CancelSessionRequest}
     */
    public static _from_object (_o: { [_K in keyof (CancelSessionRequest)]: (CancelSessionRequest)[_K] }): CancelSessionRequest {
        return new CancelSessionRequest(_o.transactionId, _o.reason);
    }


}

/**
 * @summary The Leading Root Component Types of CancelSessionRequest
 * @description
 * 
 * This is an array of `ComponentSpec`s that define how to decode the leading root component type list of a SET or SEQUENCE.
 * 
 * @constant
 */
export
const _root_component_type_list_1_spec_for_CancelSessionRequest: $.ComponentSpec[] = [
    new $.ComponentSpec("transactionId", false, $.hasTag(_TagClass.context, 0)),
    new $.ComponentSpec("reason", false, $.hasTag(_TagClass.context, 1))
];

/**
 * @summary The Trailing Root Component Types of CancelSessionRequest
 * @description
 * 
 * This is an array of `ComponentSpec`s that define how to decode the trailing root component type list of a SET or SEQUENCE.
 * 
 * @constant
 */
export
const _root_component_type_list_2_spec_for_CancelSessionRequest: $.ComponentSpec[] = [
    
];

/**
 * @summary The Extension Addition Component Types of CancelSessionRequest
 * @description
 * 
 * This is an array of `ComponentSpec`s that define how to decode the extension addition component type list of a SET or SEQUENCE.
 * 
 * @constant
 */
export
const _extension_additions_list_spec_for_CancelSessionRequest: $.ComponentSpec[] = [
    
];

let _cached_decoder_for_CancelSessionRequest: $.ASN1Decoder<CancelSessionRequest> | null = null;

/**
 * @summary Decodes an ASN.1 element into a(n) CancelSessionRequest
 * @function
 * @param el The element being decoded.
 * @returns The decoded data structure.
 */
export
function _decode_CancelSessionRequest (el: _Element): CancelSessionRequest {
    if (!_cached_decoder_for_CancelSessionRequest) { _cached_decoder_for_CancelSessionRequest = $._decode_implicit<CancelSessionRequest>(() => function (el: _Element): CancelSessionRequest {
    const sequence: _Element[] = el.sequence;
    if (sequence.length < 2) {
        throw new _ConstructionError("CancelSessionRequest contained only " + sequence.length.toString() + " elements.");
    }
    sequence[0].name = "transactionId";
    sequence[1].name = "reason";
    let transactionId!: TransactionId;
    let reason!: CancelSessionReason;
    transactionId = _decode_TransactionId(sequence[0]);
    reason = _decode_CancelSessionReason(sequence[1]);
    return new CancelSessionRequest(
        transactionId,
        reason,

    );
}); }
    return _cached_decoder_for_CancelSessionRequest(el);
}

let _cached_encoder_for_CancelSessionRequest: $.ASN1Encoder<CancelSessionRequest> | null = null;

/**
 * @summary Encodes a(n) CancelSessionRequest into an ASN.1 Element.
 * @function
 * @param value The value being encoded.
 * @param elGetter A function that can be used to get new ASN.1 elements.
 * @returns {_Element} The CancelSessionRequest, encoded as an ASN.1 Element.
 */
export
function _encode_CancelSessionRequest (value: CancelSessionRequest, elGetter: $.ASN1Encoder<any>): _Element {
    if (!_cached_encoder_for_CancelSessionRequest) { _cached_encoder_for_CancelSessionRequest = $._encode_implicit(_TagClass.context, 65, () => function (value: CancelSessionRequest, elGetter: $.ASN1Encoder<CancelSessionRequest>): _Element {
    return $._encodeSequence(([] as (_Element | undefined)[]).concat(
        [
            /* REQUIRED   */ _encode_TransactionId(value.transactionId, $.BER),
            /* REQUIRED   */ _encode_CancelSessionReason(value.reason, $.BER)
        ],
    ).filter((c: (_Element | undefined)): c is _Element => (!!c)), $.BER);
}, $.BER); }
    return _cached_encoder_for_CancelSessionRequest(value, elGetter);
}


/* eslint-enable */
