/* eslint-disable */
import {
    OCTET_STRING,
    ASN1ConstructionError as _ConstructionError,
    ASN1Element as _Element,
    ASN1TagClass as _TagClass
} from "@wildboar/asn1";
import * as $ from "@wildboar/asn1/functional";
import { TransactionId, _decode_TransactionId, _encode_TransactionId } from "../RSPDefinitions/TransactionId.ta.mjs";
// export { TransactionId, _decode_TransactionId, _encode_TransactionId } from "../RSPDefinitions/TransactionId.ta.mjs";
import { ServerSigned1, _decode_ServerSigned1, _encode_ServerSigned1 } from "../RSPDefinitions/ServerSigned1.ta.mjs";
// export { ServerSigned1, _decode_ServerSigned1, _encode_ServerSigned1 } from "../RSPDefinitions/ServerSigned1.ta.mjs";
import { SubjectKeyIdentifier, _decode_SubjectKeyIdentifier, _encode_SubjectKeyIdentifier } from "../PKIX1Implicit88/SubjectKeyIdentifier.ta.mjs";
// export { SubjectKeyIdentifier, _decode_SubjectKeyIdentifier, _encode_SubjectKeyIdentifier } from "../PKIX1Implicit88/SubjectKeyIdentifier.ta.mjs";
import { Certificate, _decode_Certificate, _encode_Certificate } from "../PKIX1Explicit88/Certificate.ta.mjs";
// export { Certificate, _decode_Certificate, _encode_Certificate } from "../PKIX1Explicit88/Certificate.ta.mjs";


/**
 * @summary InitiateAuthenticationOkEs9
 * @description
 * 
 * ### ASN.1 Definition:
 * 
 * ```asn1
 * InitiateAuthenticationOkEs9 ::= SEQUENCE {
 *     transactionId [0]TransactionId, -- The TransactionID generated by the SM-DP+
 *     serverSigned1 ServerSigned1, -- Signed information
 *     serverSignature1 [APPLICATION 55] OCTET STRING, -- Server Sign1, tag '5F37'
 *     euiccCiPKIdToBeUsed SubjectKeyIdentifier, -- The CI Public Key to be used as required by ES10b.AuthenticateServer
 *     serverCertificate Certificate
 * }
 * ```
 * 
 * @class
 */
export
class InitiateAuthenticationOkEs9 {
    constructor (
        /**
         * @summary `transactionId`.
         * @public
         * @readonly
         */
        readonly transactionId: TransactionId,
        /**
         * @summary `serverSigned1`.
         * @public
         * @readonly
         */
        readonly serverSigned1: ServerSigned1,
        /**
         * @summary `serverSignature1`.
         * @public
         * @readonly
         */
        readonly serverSignature1: OCTET_STRING,
        /**
         * @summary `euiccCiPKIdToBeUsed`.
         * @public
         * @readonly
         */
        readonly euiccCiPKIdToBeUsed: SubjectKeyIdentifier,
        /**
         * @summary `serverCertificate`.
         * @public
         * @readonly
         */
        readonly serverCertificate: Certificate
    ) {}

    /**
     * @summary Restructures an object into a InitiateAuthenticationOkEs9
     * @description
     * 
     * This takes an `object` and converts it to a `InitiateAuthenticationOkEs9`.
     * 
     * @public
     * @static
     * @method
     * @param {Object} _o An object having all of the keys and values of a `InitiateAuthenticationOkEs9`.
     * @returns {InitiateAuthenticationOkEs9}
     */
    public static _from_object (_o: { [_K in keyof (InitiateAuthenticationOkEs9)]: (InitiateAuthenticationOkEs9)[_K] }): InitiateAuthenticationOkEs9 {
        return new InitiateAuthenticationOkEs9(_o.transactionId, _o.serverSigned1, _o.serverSignature1, _o.euiccCiPKIdToBeUsed, _o.serverCertificate);
    }


}

/**
 * @summary The Leading Root Component Types of InitiateAuthenticationOkEs9
 * @description
 * 
 * This is an array of `ComponentSpec`s that define how to decode the leading root component type list of a SET or SEQUENCE.
 * 
 * @constant
 */
export
const _root_component_type_list_1_spec_for_InitiateAuthenticationOkEs9: $.ComponentSpec[] = [
    new $.ComponentSpec("transactionId", false, $.hasTag(_TagClass.context, 0)),
    new $.ComponentSpec("serverSigned1", false, $.hasTag(_TagClass.universal, 16)),
    new $.ComponentSpec("serverSignature1", false, $.hasTag(_TagClass.application, 55)),
    new $.ComponentSpec("euiccCiPKIdToBeUsed", false, $.hasTag(_TagClass.universal, 4)),
    new $.ComponentSpec("serverCertificate", false, $.hasTag(_TagClass.universal, 16))
];

/**
 * @summary The Trailing Root Component Types of InitiateAuthenticationOkEs9
 * @description
 * 
 * This is an array of `ComponentSpec`s that define how to decode the trailing root component type list of a SET or SEQUENCE.
 * 
 * @constant
 */
export
const _root_component_type_list_2_spec_for_InitiateAuthenticationOkEs9: $.ComponentSpec[] = [
    
];

/**
 * @summary The Extension Addition Component Types of InitiateAuthenticationOkEs9
 * @description
 * 
 * This is an array of `ComponentSpec`s that define how to decode the extension addition component type list of a SET or SEQUENCE.
 * 
 * @constant
 */
export
const _extension_additions_list_spec_for_InitiateAuthenticationOkEs9: $.ComponentSpec[] = [
    
];

let _cached_decoder_for_InitiateAuthenticationOkEs9: $.ASN1Decoder<InitiateAuthenticationOkEs9> | null = null;

/**
 * @summary Decodes an ASN.1 element into a(n) InitiateAuthenticationOkEs9
 * @function
 * @param el The element being decoded.
 * @returns The decoded data structure.
 */
export
function _decode_InitiateAuthenticationOkEs9 (el: _Element): InitiateAuthenticationOkEs9 {
    if (!_cached_decoder_for_InitiateAuthenticationOkEs9) { _cached_decoder_for_InitiateAuthenticationOkEs9 = function (el: _Element): InitiateAuthenticationOkEs9 {
    const sequence: _Element[] = el.sequence;
    if (sequence.length < 5) {
        throw new _ConstructionError("InitiateAuthenticationOkEs9 contained only " + sequence.length.toString() + " elements.");
    }
    sequence[0].name = "transactionId";
    sequence[1].name = "serverSigned1";
    sequence[2].name = "serverSignature1";
    sequence[3].name = "euiccCiPKIdToBeUsed";
    sequence[4].name = "serverCertificate";
    let transactionId!: TransactionId;
    let serverSigned1!: ServerSigned1;
    let serverSignature1!: OCTET_STRING;
    let euiccCiPKIdToBeUsed!: SubjectKeyIdentifier;
    let serverCertificate!: Certificate;
    transactionId = $._decode_implicit<TransactionId>(() => _decode_TransactionId)(sequence[0]);
    serverSigned1 = _decode_ServerSigned1(sequence[1]);
    serverSignature1 = $._decode_implicit<OCTET_STRING>(() => $._decodeOctetString)(sequence[2]);
    euiccCiPKIdToBeUsed = _decode_SubjectKeyIdentifier(sequence[3]);
    serverCertificate = _decode_Certificate(sequence[4]);
    return new InitiateAuthenticationOkEs9(
        transactionId,
        serverSigned1,
        serverSignature1,
        euiccCiPKIdToBeUsed,
        serverCertificate,

    );
}; }
    return _cached_decoder_for_InitiateAuthenticationOkEs9(el);
}

let _cached_encoder_for_InitiateAuthenticationOkEs9: $.ASN1Encoder<InitiateAuthenticationOkEs9> | null = null;

/**
 * @summary Encodes a(n) InitiateAuthenticationOkEs9 into an ASN.1 Element.
 * @function
 * @param value The value being encoded.
 * @param elGetter A function that can be used to get new ASN.1 elements.
 * @returns {_Element} The InitiateAuthenticationOkEs9, encoded as an ASN.1 Element.
 */
export
function _encode_InitiateAuthenticationOkEs9 (value: InitiateAuthenticationOkEs9, elGetter: $.ASN1Encoder<any>): _Element {
    if (!_cached_encoder_for_InitiateAuthenticationOkEs9) { _cached_encoder_for_InitiateAuthenticationOkEs9 = function (value: InitiateAuthenticationOkEs9, elGetter: $.ASN1Encoder<InitiateAuthenticationOkEs9>): _Element {
    return $._encodeSequence(([] as (_Element | undefined)[]).concat(
        [
            /* REQUIRED   */ $._encode_implicit(_TagClass.context, 0, () => _encode_TransactionId, $.BER)(value.transactionId, $.BER),
            /* REQUIRED   */ _encode_ServerSigned1(value.serverSigned1, $.BER),
            /* REQUIRED   */ $._encode_implicit(_TagClass.application, 55, () => $._encodeOctetString, $.BER)(value.serverSignature1, $.BER),
            /* REQUIRED   */ _encode_SubjectKeyIdentifier(value.euiccCiPKIdToBeUsed, $.BER),
            /* REQUIRED   */ _encode_Certificate(value.serverCertificate, $.BER)
        ],
    ).filter((c: (_Element | undefined)): c is _Element => (!!c)), $.BER);
}; }
    return _cached_encoder_for_InitiateAuthenticationOkEs9(value, elGetter);
}


/* eslint-enable */
