/* eslint-disable */
import {
    ASN1Element as _Element,
    ASN1TagClass as _TagClass,
    ASN1Construction as _Construction,
    ASN1UniversalType as _UniversalType,
    ObjectIdentifier as _OID,
    External as _External,
    EmbeddedPDV as _PDV,
    ASN1ConstructionError as _ConstructionError,
} from '@wildboar/asn1';
import { ID, _decode_ID, _encode_ID } from '../MhsMTAObjectIdentifiers/ID.ta.mjs';
import { id_attribute } from '../MhsMTAObjectIdentifiers/id-attribute.va.mjs';
/**
 * @summary id_attribute_defaultPermissibleContentTypes
 * @description
 *
 * OBJECT IDENTIFIER `id_attribute_defaultPermissibleContentTypes`. This argument
 * indicates the only content-types that shall appear in messages that the MTS shall
 * deliver to the MTS-user via the Message-delivery abstract-operation. It may be
 * generated by the MTS-user. See ITU-T X.411 (1999), §8.3.1.3.1.5.
 *
 * ### ASN.1 Definition:
 *
 * ```asn1
 * id-attribute-defaultPermissibleContentTypes ID ::= {id-attribute  26}
 * ```
 *
 * @constant
 */
export const id_attribute_defaultPermissibleContentTypes: ID = _OID.fromParts(
    [26],
    id_attribute
);

/* eslint-enable */
