/* eslint-disable */
import {
    ASN1Element as _Element,
    ASN1TagClass as _TagClass,
    ASN1Construction as _Construction,
    ASN1UniversalType as _UniversalType,
    ObjectIdentifier as _OID,
    External as _External,
    EmbeddedPDV as _PDV,
    ASN1ConstructionError as _ConstructionError,
} from '@wildboar/asn1';
import { ID, _decode_ID, _encode_ID } from '../MhsMTAObjectIdentifiers/ID.ta.mjs';
import { id_attribute } from '../MhsMTAObjectIdentifiers/id-attribute.va.mjs';
/**
 * @summary id_attribute_newMessageOriginatorCertificate
 * @description
 *
 * This argument contains a certificate of the originator of the message. It shall be
 * generated by a trusted source (e.g., a certification-authority), and may be supplied by
 * the originator of the message. See ITU-T X.411 (1999), §8.2.1.1.1.25.
 *
 * ### ASN.1 Definition:
 *
 * ```asn1
 * id-attribute-newMessageOriginatorCertificate ID ::= {id-attribute  104}
 * ```
 *
 * @constant
 */
export const id_attribute_newMessageOriginatorCertificate: ID = _OID.fromParts(
    [104],
    id_attribute
);

/* eslint-enable */
