/* eslint-disable */
import {
    ASN1Element as _Element,
    ASN1TagClass as _TagClass,
    ASN1Construction as _Construction,
    ASN1UniversalType as _UniversalType,
    ObjectIdentifier as _OID,
    External as _External,
    EmbeddedPDV as _PDV,
    ASN1ConstructionError as _ConstructionError,
} from '@wildboar/asn1';
import { ID, _decode_ID, _encode_ID } from '../MhsMTAObjectIdentifiers/ID.ta.mjs';
import { id_attribute } from '../MhsMTAObjectIdentifiers/id-attribute.va.mjs';
/**
 * @summary id_attribute_initiatorCredentials
 * @description
 *
 * This argument contains the credentials of the initiator of the association. It shall be
 * generated by the initiator of the association. See ITU-T X.411 (1999), §8.1.1.1.1.2.
 *
 * ### ASN.1 Definition:
 *
 * ```asn1
 * id-attribute-initiatorCredentials ID ::= {id-attribute  43}
 * ```
 *
 * @constant
 */
export const id_attribute_initiatorCredentials: ID = _OID.fromParts(
    [43],
    id_attribute
);

/* eslint-enable */
