/* eslint-disable */
import {
    ASN1Element as _Element,
    ASN1TagClass as _TagClass,
    ASN1Construction as _Construction,
    ASN1UniversalType as _UniversalType,
    ObjectIdentifier as _OID,
    External as _External,
    EmbeddedPDV as _PDV,
    ASN1ConstructionError as _ConstructionError,
} from '@wildboar/asn1';
import { ID, _decode_ID, _encode_ID } from '../MhsMTAObjectIdentifiers/ID.ta.mjs';
import { id_attribute } from '../MhsMTAObjectIdentifiers/id-attribute.va.mjs';
/**
 * @summary id_attribute_defaultPermissibleMaxContentLength
 * @description
 *
 * OBJECT IDENTIFIER `id_attribute_defaultPermissibleMaxContentLength`. This argument
 * specifies the length, in octets, of the content of the subject-message. It may be
 * generated by the originator of the probe. See ITU-T X.411 (1999), §8.2.1.2.1.2.
 *
 * ### ASN.1 Definition:
 *
 * ```asn1
 * id-attribute-defaultPermissibleMaxContentLength ID ::= {id-attribute  29}
 * ```
 *
 * @constant
 */
export const id_attribute_defaultPermissibleMaxContentLength: ID = _OID.fromParts(
    [29],
    id_attribute
);

/* eslint-enable */
