/* eslint-disable */
import {
    INTEGER,
    ASN1Element as _Element,
    ASN1TagClass as _TagClass,
    ASN1Construction as _Construction,
    ASN1UniversalType as _UniversalType,
    ObjectIdentifier as _OID,
    External as _External,
    EmbeddedPDV as _PDV,
    ASN1ConstructionError as _ConstructionError,
} from '@wildboar/asn1';


/**
 * @summary redirectHoldingTime_Default
 * @description
 *
 * Default redirect holding time: 600 seconds. Holding time put in Redirect PDUs
 * generated by this system. PERMITTED 1..65535.
 * ITU-T Rec. X.283 (12/97)
 * [§5.7](https://www.itu.int/rec/T-REC-X.283-199712-I).
 *
 * ### ASN.1 Definition:
 *
 * ```asn1
 * redirectHoldingTime-Default INTEGER ::= 600
 * ```
 *
 * @constant
 */
export const redirectHoldingTime_Default: INTEGER = 600;

/* eslint-enable */
