name: Publish
on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package:
          - "acbio"
          - "acse"
          - "ansi-x9-42"
          - "ansi-x9-62"
          - "asn1soap"
          # - "attribute-asn1module"
          - "bip"
          - "cades"
          - "casscam"
          - "cbeff"
          - "ccr"
          - "cinf"
          - "clacse"
          - "clearance-sponsor-attribute"
          - "cmail"
          # - "cmip"
          # - "cmp"
          - "cms"
          - "copp"
          # - "crmf"
          - "device-owner-attribute"
          - "ec-private-key"
          - "ers"
          - "ess"
          - "fast-infoset"
          - "ftam"
          - "gmi-attributemodule"
          - "guls"
          - "isis"
          - "iso-9798-3-sasl"
          - "kerberos5"
          - "ldap"
          # - "m3100"
          # - "nlm"
          - "ocsp"
          - "pc"
          - "pkcs"
          - "pki-stub"
          - "qc"
          - "rinf"
          - "rose"
          - "rtse"
          - "safecurves-pkix-18"
          - "scrypt-0"
          # - "scvp"
          - "sec1"
          - "sio"
          - "snmp"
          - "spkac"
          - "t38"
          - "tai"
          - "tal"
          - "tcap"
          - "tsp"
          - "usm"
          # - "x1080"
          # - "x400"
          - "x500"
          # - "x700"
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '24'
      - name: Install dependencies for ${{ matrix.package }}
        working-directory: packages/${{ matrix.package }}
        run: npm install
      - name: Add commit hash to index.mts
        working-directory: packages/${{ matrix.package }}
        run: |
          COMMIT_HASH=$(git rev-parse HEAD)
          echo -e "\nexport const GIT_COMMIT_HASH = \"$COMMIT_HASH\";\n" >> src/index.mts
          cat src/index.mts
      - name: Publish package ${{ matrix.package }}
        working-directory: packages/${{ matrix.package }}
        # --allow-slow-types: because the generate code has way too many examples
        # --verbose: for some reason, it hangs without this.
        # --allow-dirty: just because of package-lock.json and the commit hash
        run: npx jsr publish --allow-slow-types --verbose --allow-dirty
