export {
    PerceivedSeverity,
    PerceivedSeverity_cleared,
    PerceivedSeverity_critical,
    PerceivedSeverity_indeterminate,
    PerceivedSeverity_major,
    PerceivedSeverity_minor,
    PerceivedSeverity_warning,
    _decode_PerceivedSeverity,
    _encode_PerceivedSeverity,
    _enum_for_PerceivedSeverity,
    cleared,
    critical,
    indeterminate,
    major,
    minor,
    warning,
} from "@wildboar/attribute-asn1module/src/lib/modules/Attribute-ASN1Module/PerceivedSeverity.ta.mjs";
